### ISSUE TITLE
How to make HTTP-POST preferred binding?

### ISSUE THREAD

**Issue by valiukevich** [Sustainsys/Saml2#1000]
Hi all,
Currently redirect endpoint is preferred over POST when loading identity provider metadata (see GetPreferredEndpoint method).

Is there any way to change this behavior or override the binding value after every time metadata is loaded to make POST endpoint selected?

**Comment by AndersAbel** [comment]
No, this is not possible for now. It would require code changes and is nothing I can currently prioritize.
