### ISSUE TITLE
Idp not honoring the RelayState on Idp Initiated flow

### ISSUE THREAD

**Issue by gavins** [Sustainsys/Saml2#1001]
I am using the Saml2 with Identity Server 3 to enable a client of ours to use SAML SSO for our application.  We have successfully got this intergration working for Okta, but when it came to real world testing with their provider, we got stuck in a redirection look.

Basically their Idp was not sending back the RelayState thats posted to their SSO endpoint on a SAML request.  This meant the callback inside Idsr was never called, so the redirection lool to authenticate continued.

Speaking with the customer, they use Ping Identity and the only way to get the RelayState sent back is to issue a query patameter on the SSO request (with a key ot TARGET).  If have made a fork and added the necessary hooks into the Saml middleware to get this working.

Please review the commit and let me know your thoughts.

Useage:

```
var notifications = new Saml2Notifications
{
	AuthenticationRequestCreated =
		(authnRequest, idp, relayData) =>
			{
				authnRequest.DestinationUrl = new Uri(
					authnRequest.DestinationUrl.ToString() + "&TARGET=" + Uri.EscapeDataString(
						"https://localhost?RelayState=" + authnRequest.RelayState));
			},
	GetRelayState = relayState =>
			{
				Uri url;
				if (Uri.TryCreate(relayState, UriKind.Absolute, out url))
				{
					var queryArgs = new NameValueCollection();
					foreach (string segment in url.Query.Split('&'))
					{
						var parts = segment.Split('=');
						if (parts.Length > 0)
						{
							string key = parts[0].Trim('?', ' ');
							string val = parts[1].Trim();

							queryArgs.Add(key, val);
						}
					}

					return queryArgs["relaystate"];
				}

				return relayState;
			}
};
```

This will produce the following request to the SSO:

https://hidden.com/idp/startSSO.ping?PartnerSpId=hidden&TARGET=https:%2F%2Flocalhost%3FRelayState%3Djj4fZ1vrpl1zUGI-3MRod0rX

and a reply containing the form data:

RelayState: https://localhost?RelayState=jj4fZ1vrpl1zUGI-3MRod0rX

Note: The TARGET needs to be a valid Url and the Idp is parsing this.

**Comment by AndersAbel** [comment]
To me this looks like Ping is not following the SAML2 spec. It is very clear that whatever the SP sends as RelayState MUST be returned back with the response.

Closing this (and the PR) as it is nothing I can spend time on for free. If you want help on a commercial basis to add this functionality as a compability setting, please mail me at anders@sustainsys.com.
