### ISSUE TITLE
Possible to pull signing certificate automatically from federation metadata?

### ISSUE THREAD

**Issue by UweKeim** [Sustainsys/Saml2#1003]
Having successfully implemented my first SAML integration in my web application, my customer asked me the following:

> Instead of specifying the signing certificate via the [`<signingCertificate>` element](https://github.com/Sustainsys/Saml2/blob/master/docs/config-elements/signing-certificate.rst), would it be possible instead to automatically download the file from the URL of the [federation metadata](https://github.com/Sustainsys/Saml2/blob/master/docs/config-elements/federations.rst)?

According to my customer, the signing certificate is contained within the federation metadata.

While I cannot judge his statement (I tend to believe that he's wrong), I still want to ask here.

**My question:**

Is it possible to get the signing certificate from the federation metadata from an AD FS server, instead of specifying it manually in the configuration?

**Comment by explunit** [comment]
Yes, and you should not even need to configure a federation in order to use ADFS's metadata. Just set the metadata url of your IDP config to `https://<your adfs server>/FederationMetadata/2007-06/FederationMetadata.xml`

**Comment by UweKeim** [comment]
Thanks, @explunit. In my tests, I always got an exception, when I omit the [`<signingCertificate>` element](https://github.com/Sustainsys/Saml2/blob/master/docs/config-elements/signing-certificate.rst).

But when providing the metadata URL inside the [`<identityProviders>...<add>` element](https://github.com/Sustainsys/Saml2/blob/master/docs/config-elements/identity-providers.rst), it worked:

```xml
metadataLocation="https://<my adfs server>/FederationMetadata/2007-06/FederationMetadata.xml"
```
