### ISSUE TITLE
Example IDP project for .Net Core

### ISSUE THREAD

**Issue by michael-ecb** [Sustainsys/Saml2#1005]
Hi,

is it possible to provide a new example "StubIdp" to help understand how to implement it or some documentation ?
How can we provide a metadata if classes like ExtendedEntityDescriptor not more exists ?

thanks

**Comment by AndersAbel** [comment]
I have some ideas on Idp functionality, but it is nothing I will be able to focus on for the near time. Right now I need to get .NET Core 2.X support working better first.
