### ISSUE TITLE
Logout URL in SampleMVC application

### ISSUE THREAD

**Issue by BadLambdaJamma** [Sustainsys/Saml2#1015]
There are two logout links available after using an IdP to sign into this sample application.  Link #1 is on the top menu bar of the application "**Logout**".  Link #2 is in the page that shows all the claims resulting from SSO "**You are signed in. Log out.**"

Link #1 has no **return URL** and works properly in all cases even when running in a virtual directory under IIS (versus IIS express). The Saml2 controller Logout action is only called once in this case.

Link #2 has a **return URL** and does not work when running in a virtual directory under IIS (versus IIS Express).  The Saml2 controller Logout action is called twice when logging out in this case.

I am using KeyCloak as my IdP and I have my logout URL Setup in the IdP as http://192.168.7.135/SampleMvcApplication/Saml2/Logout

It seems like a return URL is not required for logout and that the Logout action should not be called twice.  As such it seems like Link #1 is working properly and Link #2 is incorrect ?

Thanks
-Jonathan

**Comment by AndersAbel** [comment]
Marking that as a bug, will have to investigate. But the Logout action should not be called twice.

**Comment by AndersAbel** [comment]
Tested them and I don't see the double call. Can you please supply some logs from browser dev tools? Also the reason it doesn't work in  a virtual dir is because the return-url is hard coded to /. As it is a sample app I won't fix it.

**Comment by BadLambdaJamma** [comment]
Link #1 has no **return URL** and it seems to work properly.  Is **return URL** required  for logout?

**Comment by AndersAbel** [comment]
@BadLambdaJamma No, a return url is not required, but it is supported to have one.

**Comment by AndersAbel** [comment]
@BadLambdaJamma Do you have any update on this? To get any further I need a screen dump/log from your browser dev tools showing the issue.

**Comment by AndersAbel** [comment]
Closing due to lack of further info. Will reopen if details are provided.
