### ISSUE TITLE
Bug in documentaition

### ISSUE THREAD

**Issue by mkarnovan** [Sustainsys/Saml2#1019]
Thanks for your work. It's really helped me. But I found an error in documentation.
https://saml2.sustainsys.com/en/2.0/identity-server-3-okta.html#step-3-configure-your-identity-server-with-the-new-identity-provider
Could you please to rename **MetadataUrl** to **MetadataLocation** and use string instead of Uri?

**Comment by mkarnovan** [comment]
And change the **Signature Algorithm** from sha-1 to sha-256, because sha-1 doesn't support your applications.
I tested your library on AspNetCore application.

**Comment by AndersAbel** [comment]
This fix should go both into the 2.0 and 1.0 branch to also make sure the docs for 1.0 is correct.
