### ISSUE TITLE
[Asp.Net core] add support for idp selection

### ISSUE THREAD

**Issue by sandorfr** [Sustainsys/Saml2#1021]
Currently asp.net core handler takes the first idp. It's not very good when several are available.

It would be good to add a way to select Idp to be used in a similar fashion as https://github.com/Sustainsys/Saml2/blob/master/docs/owin-middleware.rst#selecting-idp

I've submitted a PR #1020 aiming at adding that capability.

```csharp
var properties = _signInManager.ConfigureExternalAuthenticationProperties(samlScheme, redirectUrl);
properties.Items.Add("idp", method.GetConfiguration<Saml2IdpConfiguration>().EntityId);
return new ChallengeResult(samlScheme, properties);
```

Let me know what you thing. Happy to improve / refactor based on feedback.

**Comment by AndersAbel** [comment]
Merged #1020.
