### ISSUE TITLE
Add back support for .NET 4.6.1

### ISSUE THREAD

**Issue by dburner** [Sustainsys/Saml2#1026]
I know the target framework just moved to 4.6.1 to 4.7 to fix a bug, but could we get another target for 4.6.1 with a known issue that that bug won't work?

**Comment by AndersAbel** [comment]
It might be possible, but would require to comment out some things. What is the reason that you cannot upgrade to 4.7? I would like to understand how many are affected by this.

**Comment by dburner** [comment]
I've worked for several companies that offer web apps with on premise deployments. From what I know big enterprise companies have rules strict rules and complicated procedures (security checks, approvals from different people, etc) that lead to very long upgrade times. So companies that sell software with on premise deployments struggle to keep the target framework as lower as possible to allow many potential customers.

So...yes upgrading the software to 4.7 would be quite easy but wont meet the customers requirements.

**Comment by AndersAbel** [comment]
Looks like you're not the only one needing this. I'll try to get another target in for the next release.

**Comment by dburner** [comment]
Thank you, any ideeas when would this be released? :)

**Comment by AndersAbel** [comment]
@dburner Next week.

**Comment by dburner** [comment]
@AndersAbel thanks, but the release notes are wrong, you said note 4.6.2 instead of 4.6.1.

**Comment by AndersAbel** [comment]
@dburner Too bad. I updated in the milestone. Unfortunately it's not possible to change the release notes on Nuget.org after the packages have been uploaded :(

**Comment by dburner** [comment]
@AndersAbel I think you can make another release 2.1.1 that states the correct version and the fact that the last one is not changed :D, I don't need that, but it may help this project, I don't know...it's up to you.

I have seen something like this in https://github.com/esvit/ng-table/releases, see release v3.1.0 but they entered the wrong version in the release.
