### ISSUE TITLE
Configuration property on Saml2PSecurityTokenHandler

### ISSUE THREAD

**Issue by sai450** [Sustainsys/Saml2#1029]
Prior to v2.0.0 of AspNetCore2 Handler, there used to be a Configuration property at SPOptions > Saml2PSecurityTokenHandler > Configuration
It looks like this property no longer exists in v2.0.0. Has this been relocated? If so, Can someone point me in the right direction?

I am specifically looking for MaxClockSkew setting. Is there an alternative way set this? What is the default?

**Comment by AndersAbel** [comment]
The default is 5 minutes.

I've planned to expose the `TokenValidationParameters` that contain these settings, but has not yet done so. If you need to be able to alter those settings, you have to remain on 1.0.0 for now.
