### ISSUE TITLE
Application enters an infinite redirect loop after successful login.  Using Owin & ADFS

### ISSUE THREAD

**Issue by rikrak** [Sustainsys/Saml2#1035]
**NuGet Package:** Sustainsys.Saml2: v1.0.0
**Framework target:** .net451
**Framework installed:** 4.7.2
**MVC:** v5.2.3
**Owin:** v3.0.1
**Browser:** Chrome

**Scenario:**
I have upgraded my application from Kentor.AuthServices v0.19.0 to Sustainsys.Saml2 v1.0.0.  Prior to the upgrade I had a working integration with an ADFS system (albeit in a development environment).  I am using the Owin package.
[OwinLog.txt](https://github.com/Sustainsys/Saml2/files/2496015/OwinLog.txt)

**Expected result:**
The integration should still work

**Actual result:**
When accessing my site I am redirected to the ADFS sign-on page.  After a successful authentication, I am redirected back to my site, which then initiates an infinite redirection loop between the IdP and itself.

**Analysis:**
On debugging the code, it appears my application authenticates the User and sets the ExternalCookie as expected, however after setting the external cookie the redirect response sets the location to the originally requested page, rather than the configured ReturnUrl.  This means the User arrives unauthenticated and the process starts again.

In `AcsCommand.ProcessResponse()` The value of `Location` on the `CommandResult` is set to the originally requested page, whereas I would expect it to use the `ReturnUrl` value of the `SPOptions` (Account/ExternalLoginCallback in my case).  

The redirect to the original page simply begins the authentication loop again.  The ExternalLogin cookie is set on the request but it isn't used to authenticate the user.

I've attached the Owin log (it's been anonymised, but contains the important info)

I've spent a few days debugging this and I have to be honest and say I can't tell whether this is a bug or a misconfiguration.

It appears that the ReturnUrl value is derived from the `Saml2AuthenticationHandler.ApplyResponseChallengeAsync()` Line:~127

    if (redirectUri == null && Options.AuthenticationMode == AuthenticationMode.Active)
    {
        redirectUri = Context.Request.Uri.ToString();
    }
I wondered if this should be something like:

    if (redirectUri == null && Options.AuthenticationMode == AuthenticationMode.Active)
    {
        redirectUri = Options.SPOptions.ReturnUrl + "?ReturnUrl=" +Context.Request.Uri.ToString();
    }

**Comment by rikrak** [comment]
One other thing to note is that I have set the Authentication Mode to Active, which seems to make a difference.  If I do the same with the Sample application I observe the same results:

            var Saml2Options = new Saml2AuthenticationOptions(false)
            {
                SPOptions = spOptions,
                AuthenticationMode = AuthenticationMode.Active
            };

**Comment by AndersAbel** [comment]
Excellent bug report. I recently did some changes to this, in #1018. But that was for 2.1.0 not, 1.0.0. I'll have a look and get back, but it will take a few days.
