### ISSUE TITLE
SAMLResponse using HTTP Redirect

### ISSUE THREAD

**Issue by j-hurst** [Sustainsys/Saml2#1036]
I am using HTTP Redirect binding, and when retrieving the SAML response, the assertion does not contain the signature.  However when I inspect the request, I see the signature being passed as another query string parameter in the HTTP redirect call.

But because I have an assertion with no signature in the SAML response, I am receiving the "The SAML Response is not signed and contains unsigned Assertions. Response cannot be trusted."  exception.

Is there a setting to have it look somewhere else, or bypass this exception altogether?

**Comment by AndersAbel** [comment]
Receiving Saml responses over the Http Redirect binding is not currently supported by the library. They are usually so large that they do not fit into URL length restrictions. Can you configure the Idp to use Http POST when sending the response? Http Artifact is also supported, although that adds some other complexity.

**Comment by j-hurst** [comment]
If it is sent through POST, does the Assertion endpoint become a POST call?
