### ISSUE TITLE
Description of nuget packages supported .NET is out of date

### ISSUE THREAD

**Issue by GavBurke** [Sustainsys/Saml2#1044]
I've been trying to install Sustainsys.Saml2.HttpModule, either version 2.0 or 2.1, but giving me the error of `Install-Package : Could not install package 'Sustainsys.Saml2 2.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.At line:1 char:1`

You package description specifically says .NET 4.5 is needed:
`A SAML2 Http Module for ASP.NET. Install in project and add sections to web.config. No coding required. The package adds an ASP.NET Http Authentication Module that handles the SAML SignIn and SignOut. It works with the claims model of .NET 4.5 and uses the present infrastructure for claims translation, session authentication cookies etc.`

Only after reading your issue 1024 do I find it's .NET 4.7 or newer - I had tried only 4.5, 4.5.1, 4.5.2 and 4.6 as I have nothing newer in my VS list...

**Comment by AndersAbel** [comment]
@GavBurke Thank you for noticing the incorrect description. I'll update it for the next release (due this week).

The lowest .NET Framework version supported is .NET 4.6.1 for the 2.1.0 package.

**Comment by GavBurke** [comment]
Thanks for the reply, I have tried .NET 4.6.1 now and seen it was happy now with the  Sustainsys.Saml2.HttpModule package, but the dependencies still has issues even with .NET 4.6.1:
`Could not install package 'Microsoft.Extensions.Caching.Memory 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework`

**Comment by AndersAbel** [comment]
Looks like another thing to add to the docs. That assembly targets .NET Standard 2.0, which is implemented by 4.6.1, but only if you have the .NET Core 2.0 SDK installed, see https://docs.microsoft.com/en-us/dotnet/standard/net-standard
