### ISSUE TITLE
Received message contains unexpected In Response To "#####".No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute 

### ISSUE THREAD

**Issue by telalwar** [Sustainsys/Saml2#1052]
Hello All,

**Exact Error message :**
Received message contains unexpected InResponseTo "id90f36b7499fe4b08a24b582bd682860a". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.

**Set up :** I'm using portal generated by **SampleMVCApplication**  to hit SP end point. (I modified index.cshtml page to add link to our(SP) end point), also using **Sustainsys.Saml2.StubIdp**  as IDP
Something like this,

![image](https://user-images.githubusercontent.com/5652906/51146894-3c3d8780-1826-11e9-9e1e-ddfd797a9617.png)

**Following is SP end point**
```
        [Route("test")]
        [HttpGet]
        public ActionResult foo()
        {
            var options = Saml2Controller.Options;
            options.SPOptions.PublicOrigin = new Uri("http://localhost:8181/api/sso");

            CommandResult result = CommandFactory.GetCommand(CommandFactory.SignInCommandName).Run(
                                                                 Request.ToHttpRequestData(),
                                                                 options);

            result.ApplyCookies(Response);
            return result.ToActionResult();
        }
```

**SP Web.config**
```
  <sustainsys.saml2 entityId="http://localhost:8181" returnUrl="http://localhost:8181">
    <identityProviders>
      <add entityId="http://localhost:52071/Metadata" signOnUrl="http://localhost:52071/" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/stubidp.sustainsys.com.cer" />
      </add>
    </identityProviders>
  </sustainsys.saml2>
```

SP end point is correctly redirecting request to IDP used for validation and authentication,  

**Incoming Auth Request at IDP :**

```
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="id9ab809e6d9434e708fac640d21072923" Version="2.0" IssueInstant="2019-01-14T22:44:22Z" Destination="http://localhost:52071/" AssertionConsumerServiceURL="http://localhost:8181/api/sso/Saml2/Acs">
  <saml2:Issuer>http://localhost:8181</saml2:Issuer>
</saml2p:AuthnRequest>
```

![image](https://user-images.githubusercontent.com/5652906/51147310-cf2af180-1827-11e9-87d3-461fcea12e14.png)

**When I hit log In**  request get redirected to this ACS end point and it is failing to authenticate here
```
[Route("saml2/ACS")]
[HttpPost]
public ActionResult zoo()
{
	// Request is  Failing on this command. Note that incoming Request now do not have any cookie
	CommandResult result = CommandFactory.GetCommand(CommandFactory.AcsCommandName).Run(
                                                                 Request.ToHttpRequestData(),
                                                                 options);
																 
-----																 
}
```

Cookie sessions for each request:
1.
![image](https://user-images.githubusercontent.com/5652906/51147840-c76c4c80-1829-11e9-8be4-156da6646419.png)

Things  I tried: 
1. All the browser
2. Tried it from clean slate
3. F5 , which few post mentioned that it worked for them
4. Tried solution mentioned in other posts

When the post from stub hits ACS end point , in debugging i Found that Request does not have any cookies in it. 
What I'm doing wrong ? Any lead is helpful .

**Comment by telalwar** [comment]
@AndersAbel I tried my solution on all the three browser i.e Chrome, Firefox and IE

**Comment by telalwar** [comment]
@AndersAbel Looks like problem/solution mentioned by Brock in his blog is for ASP.net core stack. We are on .net Framework 4.5.2 and Sustainsys version 0.23.0.0. I will try to upgrade project to 4.7 or port it to  netcore2.0 .

**Comment by telalwar** [comment]
@AndersAbel I could not solve the problem on .net framework 4.5.2 and we are in middle of porting our apps to netcore2.0 and my initial tests for SSO on net core apps looks good to me.  So i think we can close this ticket. Thank you!

**Comment by pragneshmpatel** [comment]
I am getting same error. did you managed to find any solution?

**Comment by jdusome** [comment]
Hello I am also receiving this same error on version 1.0.0 of the framework. Unfortunately, I cannot update to a higher version as we are stuck with the Owin version.

`Sustainsys.Saml2.Exceptions.UnexpectedInResponseToException: Received message contains unexpected InResponseTo "id964e7e7f6e544446ae8d46dbab6d1be1". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.
   at Sustainsys.Saml2.Saml2P.Saml2Response.ReadAndValidateInResponseTo(XmlElement xml, Saml2Id expectedInResponseTo, IOptions options)
   at Sustainsys.Saml2.Saml2P.Saml2Response..ctor(XmlElement xml, Saml2Id expectedInResponseTo, IOptions options)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.Owin.Saml2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
    ProcessId=79868
    DateTime=2020-11-27T17:47:53.8568554Z`

Is there any way to circumvent this error?

**Comment by AndersAbel** [comment]
@jdusome On 1.0.0 this is probably due to SameSite cookie behaviour. Update to 1.0.2. (actually 1.0.1 is the one that contains the SameSite fixes to work with modern browsers, but you want the 1.0.2 security update too).

**Comment by lballena** [comment]
Hello @AndersAbel.  I saw this post, and I am getting the error described this post:

 Exception message: Received message id1967830186762921733311736 contains unexpected InResponseTo "idc2e5a9bb4035423eaa4b059a8cdc8502". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.
   at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateInResponseTo(IOptions options, IEnumerable`1 claimsIdentities)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options, IDictionary`2 relayData)
   at Sustainsys.Saml2.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState, IdentityProvider identityProvider, String relayState)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

How I produced this was a redirect from one domain to the sp-initiated domain.  Basically we are migrating our web application to use saml and okta as the idp.  What we wanted to test was to redirect from our current application domain to the new application domain that will use saml/okta.  We just did this redirect from via dns as alias record.  The redirect worked, the sp-initiated login worked...but once into the application, the above error was logged.

Hopefully I explained this clearly, but any input would be appreciated.

**Comment by AhmedAssaf** [comment]
Same issue here,
Is there any solution?

**Comment by pb-atg** [comment]
I am also having the same issue.  I tried Brock's fix, but it didn't help.  I've tried on Chrome and Edge.  I am just trying to implement systainsys for the first time.  I like it, but this is my first test and I am getting this error.  .NET Core 3.1 mvc.  Any possible solutions for this?

**Comment by lgwakano** [comment]
Scenario:
.NET framework 4.7.2 ASP.NET MVC only for Http Calls.

The way I've workaround this issue I am intercepting the cookie and changing the cookie ```sameSite``` attribute 


On my Global.asax.cs
```c#
  protected void Application_BeginRequest(object sender, EventArgs e)
  {
      SameSiteCookieRewriter.FilterSameSiteNoneForIncompatibleUserAgents(sender);
      if (Request.Url.Host.Contains("www") && !Request.Url.IsLoopback)
      {
          UriBuilder builder = new UriBuilder(Request.Url);
          builder.Host = Request.Url.Host.Replace("www.", "");
          Response.Redirect(builder.ToString(), true);
      }
  }
```

**Intercept the HttpApp Sender and modify the Cookie SameSite attribute**
```c#
public static class SameSiteCookieRewriter
{
    public static void FilterSameSiteNoneForIncompatibleUserAgents(object sender)
    {
        HttpApplication application = sender as HttpApplication;
        if (application != null)
        {
            //var userAgent = application.Context.Request.UserAgent;
            //if (BrowserDetection.DisallowsSameSiteNone(userAgent))
            //{
                application.Response.AddOnSendingHeaders(context =>
                {
                    var cookies = context.Response.Cookies;
                    for (var i = 0; i < cookies.Count; i++)
                    {
                        var cookie = cookies[i];
                        if (cookie.SameSite == SameSiteMode.None)
                        {
                            cookie.SameSite = (SameSiteMode)(-1); // Unspecified
                        }
                    }
                });
            //}
        }
    }
}

```

You can notice the condition to check UserAgent is commented just to reduce the scope of test. The intercept snippet was copied from https://docs.microsoft.com/en-us/aspnet/samesite/csmvc#interception. (Specific for ```ASP.NET 4.7.2 C# MVC```)

Also I stumble with this post which relates to the same issue but is covering ```ASP.NET Core```: 
https://devblogs.microsoft.com/dotnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/


Hope that helps.

**Comment by JerkerPihl** [comment]
@lgwakano solution solved my problem
