### ISSUE TITLE
Question: How to connect an ILoggerAdapter in ASP.NET MVC application

### ISSUE THREAD

**Issue by perplexErik** [Sustainsys/Saml2#1053]
Hi,

I'm using the "Sustainsys.Saml2.Mvc" example application for testing the communication with an IDP, but right now i'm only getting an "An error occurred while processing your request" message in the browser when the IDP redirects the visitor to the AssertionConsumerService (/Saml2/Acs) URL. 
The Event Viewer "Application" logs don't contain an entry after the error occurred,

To diagnose what the heck is going on i would like to connect an ILoggerAdapter to the SPOptions.Logger (as is recommended on the troubleshooting page).

Is it possible to do this by configuring it in the web.config? Right now all configuration is done in de web.config file. If it needs to be done through code, where/when would i hook up my custom Logger?
(i'm using the ASP.NET MVC example , not OWIN)

**resources:**
- https://github.com/Sustainsys/Saml2/blob/master/Samples/SampleMvcApplication/Web.config
- https://saml2.sustainsys.com/en/2.0/troubleshooting.html

**Comment by AndersAbel** [comment]
ILoggerAdapter needs to be configured in code. In the Mvc library, the Options are a static property on the Saml2Controller. Set the ILoggerAdapter within the existing instance to something. That way you can have the rest of the config in web.config still.

The idea of the config going forward is to keep support for things that tend to change between environments in the web.config, but things that typically require code adaptions (such as a logger) will only be configurable through code.

**Comment by perplexErik** [comment]
Hi,
First of all, many thanks for your quick response!

So if i understood correctly, i can add the following line in the "Application_Start" in Global.asax?

`Sustainsys.Saml2.Mvc.Saml2Controller.Options.SPOptions.Logger = FilesystemLogger;`

Kind regards,
Erik

**Comment by AndersAbel** [comment]
@perplexErik Yes, that will work.
