### ISSUE TITLE
Package install issues Microsoft.Extensions.Caching.Memory on .NET Framework target.

### ISSUE THREAD

**Issue by Postal187** [Sustainsys/Saml2#1054]
Could not install package 'Microsoft.Extensions.Caching.Memory 2.0.1'.  You are trying to install this package into a project that targets '.NETFramework, Version=v4.6.1, but the package does not contain any assembly references or content files that are compatible with that framework. for more information, contact the package author.

I tried a few diff frameworks - even 4.7 and got the same error when trying to install this package.  I see that someone else had a similar issue in bug 1044 - but I don't see where that was fixed or what I need to do to make it work. 

I had to go back to version 1.0 of Saml2 to get a clean install.  Any help would be much appreciated.

**Comment by AndersAbel** [comment]
The Microsoft.Extensions.Caching.Memory requires a .NET Core SDK installed to work with .NET Framework.

In the next release I plan to remove that dependency completely when targeting .NET Framework, you're not the first one running into issues with this. Either install a .NET Core SDK or stay on 1.0 until I've made the next release available.

**Comment by Postal187** [comment]
Thank you!  I will give that a shot and see how it goes.

**Comment by TheCloudlessSky** [comment]
We're running into this too. @AndersAbel do you publish pre-release builds on MyGet or something similar. We'd like to use 2.2.0 on .NET 4.6.2 but this error is preventing us from installing since the packages on Nuget don't include this fix.

**Comment by barakakha** [comment]
version 3.1.1 still have this issue:

> Could not install package 'Microsoft.Extensions.Caching.Memory 3.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AndersAbel** [comment]
@barakakha version 3.1.1? There is no version 3.1.1 of the Sustainsys.Saml2 library.

**Comment by barakakha** [comment]
Sorry, stupid mistake, Deleted my comment
