### ISSUE TITLE
Cannot install Sustainsys.Saml2 in VS2015, .net 4.5.2

### ISSUE THREAD

**Issue by atollkuci** [Sustainsys/Saml2#1061]
I'm trying to install Sustainsys.Saml2 in a project that targets .NET 4.5.2 in Visual Studio 2015 and I get an error:

_Could not install package 'Sustainsys.Saml2 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

**Comment by blushingpenguin** [comment]
It doesn't support .NETFramework 4.5.2, update it to at least 4.6.1.  Look at:
https://www.nuget.org/packages/Sustainsys.Saml2/
and under dependencies for supported frameworks.

**Comment by atollkuci** [comment]
> It doesn't support .NETFramework 4.5.2, update it to at least 4.6.1. Look at:
> https://www.nuget.org/packages/Sustainsys.Saml2/
> and under dependencies for supported frameworks.

Sorry I missed that, but now with .NET 4.7 or 4.7.2 I get another error:

_Could not install package 'Microsoft.Extensions.Caching.Memory 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

**Comment by AndersAbel** [comment]
That package targets .NET Standard. It works on .NET 4.7, but you need the .NET Core SDK installed. That dependency will be removed in the next release. For now, I'd recommend that you use 1.0.0 to get a simple installation. The 1.X release is still fully supported. The 2.X is a major rewrite to support .NET Core. If you don't need .NET Core 1.X will work.

**Comment by atollkuci** [comment]
> That package targets .NET Standard. It works on .NET 4.7, but you need the .NET Core SDK installed. That dependency will be removed in the next release. For now, I'd recommend that you use 1.0.0 to get a simple installation. The 1.X release is still fully supported. The 2.X is a major rewrite to support .NET Core. If you don't need .NET Core 1.X will work.

Thanks. I don't need .NET core, so by using 1.0 it worked fine.
