### ISSUE TITLE
IgnoreAuthenticationContextInResponse not available in web.config (1.x)

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#1062]
The IgnoreAuthenticationContextInResponse compatibility flag cannot be set through web.config, only in code. Should be added to web.config.

**Comment by Bryan-Ketley** [comment]
I'm please this setting have been exposed to the Web.config.  What version will this be included in and when will it be released?

**Comment by AndersAbel** [comment]
There will be no further development of web.config. Even when using the HttpModule, the options can be set from code.
