### ISSUE TITLE
Can you please change to an Apache 2.0 license from GNU?

### ISSUE THREAD

**Issue by williamwsmith** [Sustainsys/Saml2#107]
The license makes it unlikely that this project can be used or contributed to from large companies like I work at.  An Apache 2.0 license would basically solve that issue.  Thanks.

**Comment by williamwsmith** [comment]
Sorry I didn't get back.  All GLP based licenses as a rule (again not in all case, but, most), are not compatible with commercial use.  There is little to no open source LGPL/GLP software approved for use by the large company I am working at.  There is a reason Microsoft has open sourced .NET lately on both MIT and Apache 2.0 licenses.  There is too much legal mumbo jumbo to list here, but, a cursory search on the web brings up many of the issues.
CoreCLR:  https://github.com/dotnet/coreclr  MIT license
MVC (OWIN) vNext: https://github.com/aspnet/Mvc  Apache 2.0 license.
Your great SAML2P library simply will not get used in most commercial settings.

**Comment by AndersAbel** [comment]
I still don't understand in what way LGPL is a problem for you. GPL is a completely other issue for commercial applications. That's why we chose LGPL.

I did some research before chosing LGPL, so if you have any favourite link to information on problems with LGPL, please share that. Can you also please provide a scenario where LGPL would be a problem whereas Apache 2.0 would work for you?

**Comment by williamwsmith** [comment]
Guess I don't have much to add other than I have been told my organization prefers Apache 2 or MIT.
I see very little GPL/LGPL on new projects anywhere.  So that is all I can add at this point.
One other thing (that probably doesn't add much), but, if you have to  have a web page this complex to define under what conditions you have to cough up proprietary source code on demand, then, it brings into question the viability of the license:  http://www.gnu.org/licenses/gpl-faq.html

**Comment by AndersAbel** [comment]
I've made another round checking out the differences between the licenses. Apache 2.0 is not a strong enough copy-left license for me.

For this project, I want a license that allows anyone to use the library, in any kind of software. But, I don't want someone to take (parts of) the library code and copy it into a commercial product. As far as I know LGPL does exactly what I want in this case.

If you provide more details on in what way LGPL is a problem, we can discuss that. But as long as you're only whining about GPL being too complex or non-preferred by your organization I won't change my mind.

**Comment by brendonparker** [comment]
Perhaps the concern is that it isn't clear (at least to me) if one would need to disclose any source code that took a dependency on Sustainsys.Saml2. Obviously if one were to modify code found in this repo, one would have to disclose that. However, if they are using the code as it exists in nuget (for example) would they be required to disclose their source?
