### ISSUE TITLE
Saml2 cookie is not marked as essential in ASP.NET Core 2.1+

### ISSUE THREAD

**Issue by thomaslevesque** [Sustainsys/Saml2#1075]
As discussed in https://github.com/Sustainsys/Saml2/issues/666#issuecomment-476652462

### Information needed
1. What nuget packages are you using : Sustainsys.Saml2.AspNetCore2 (2.2.0)
2. What is the expected behaviour : SP-initiated login should work even if the user didn't give their consent for cookies (GDPR consent banner)
3. What happens instead : if cookie consent is enabled and the user didn't give their consent, login doesn't work because the Saml2 cookie is missing (`UnexpectedInResponseToException`)

ASP.NET Core 2.1 introduced support for GDPR cookie consent. This feature is enabled by default in the project template. If it's enabled and the user didn't give their consent, non-essential cookies are not emitted. Since the Saml2 cookie is essential, it should be marked as such.

### Additional info
Please include
* .Net Framework your application is compiled against: `netcoreap2.1`
* .Net Framework installed: .NET Framework 4.7.2, many versions of .NET Core
* Version of Asp.Net MVC / Asp.NET Core used: ASP.NET Core 2.1

**Comment by thomaslevesque** [comment]
Normally the fix is as simple as setting `IsEssential` to true in the cookie's options. However, since Sustainsys.Saml2.AspNetCore2 references ASP.NET Core 2.0, this property is not available, since it was introduced in 2.1.

I see a few options, none of which is ideal...

* Upgrade the library to target ASP.NET Core 2.1 => breaking change for users still targeting 2.0
* Create a new `netcoreapp2.1` target => will solve the problem for apps targeting `netcoreapp2.1`, but not for those targeting `net4xx`
* Use reflection to set the property if it exists (possibly by generating and caching a delegate to avoid using reflection every time). It's a bit ugly, but would work for everyone without a breaking change.

What do you think?

**Comment by thomaslevesque** [comment]
I sent a tentative PR that implements the last suggested solution.

**Comment by AndersAbel** [comment]
Thanks. The reflection code is elegant, but it's still reflection...

What do you think the drawbacks are of requiring an upgrade to Asp.Net Core 2.1? If I understand correctly 2.0 isn't even officially supported any more, while 2.1 is an LTS release with support until 2021. (https://en.wikipedia.org/wiki/ASP.NET_Core)

**Comment by thomaslevesque** [comment]
> Thanks. The reflection code is elegant, but it's still reflection...

Yes... It shouldn't really affect performance, though, since it's only done once.

> What do you think the drawbacks are of requiring an upgrade to Asp.Net Core 2.1? If I understand correctly 2.0 isn't even officially supported any more, while 2.1 is an LTS release with support until 2021.

I guess it's a valid approach, but it would be a breaking change. As far as I remember, the migration from 2.0 to 2.1 is quite painless, but some users won't like being forced to migrate to get the fix.

I'm fine with either approach. Your project, your choice :wink:

**Comment by AndersAbel** [comment]
> I'm fine with either approach. Your project, your choice 😉
The advantage of being the maintainer...

I'll pick option 1 then, because 2.0 is no longer supported. In the past, I've had the policy for net4xx to target the lowest supported version so I would do the same here - even for a minor/patch version bump. If anyone wildly disagrees - now is the time to object.

So even though your reflection code is nice, it can be replaced by a simple property setter.

**Comment by thomaslevesque** [comment]
Fine by me. I'll update the PR.

**Comment by thomaslevesque** [comment]
The tests fail because the command to run them specifies "netcoreapp2.0" in the path to the assembly. But since it's not in the source code, I can't change it myself, you'll need to do it in AppVeyor. (If I can make a suggestion, you should consider using an appveyor.yml file instead of specifying everything in the AppVeyor UI. This way build settings are in source control and can be different for each branch if necessary.)
