### ISSUE TITLE
Servicecertificates certificate extract password

### ISSUE THREAD

**Issue by iherbak** [Sustainsys/Saml2#1082]
Is it possible to provide custom password to the component for loading servicecertificates?

Thanks

**Comment by AndersAbel** [comment]
No. Because if you have a password protected file, you will have to keep the password somewhere. For production, you should use the certificate store instead.

**Comment by iherbak** [comment]
Could someone provide an example how to add cert for an SP from the cert store? The documentation has no indication on that. Thanks

**Comment by fuzzzerd** [comment]
There's nothing stopping you from loading your own `X509Certificate` as a .pfx and loading that into the collection manually.

**Comment by iherbak** [comment]
From a pfx file thats fine. I could add the fileName attribute to the serviceCertificates element. But i would like to use the cert store
