### ISSUE TITLE
Whitespace issue in parsing Authn response

### ISSUE THREAD

**Issue by lscorcia** [Sustainsys/Saml2#1084]
### Information needed
1. What nuget packages are you using
Plain SampleHttpModuleApplication from the latest github repository. I'm testing the SP application, configured to connect to my organization IDP provider.

2. What is the expected behaviour
On successful authentication on the IDP side, my IDP provider returns "xml-indented" Authn responses, adding a bunch of whitespace in the xml response. This should not be a problem for the SAML library, which should decode the response correctly.

3. What happens instead.
Exception in Saml2PSerializer.cs, line 135. The problem is the line immediately above https://github.com/Sustainsys/Saml2/blob/8545f963edf646b09ba8c2a56af63be9a5fb6cfb/Sustainsys.Saml2/SAML2P/Saml2PSerializer.cs#L132

If there is some white space between tags, the envelopeReader.Read will advance to the whitespace node instead of the Issuer node.

This can be fixed by loading the XmlReader in a XmlDocument created with the PreserveWhiteSpace property to false, after decryption.

### Additional info
Please include
* .Net Framework your application is compiled against (e.g. `net472`, `netcoreap2.1`)
Using .net fw 4.7 as per default application settings.

* .Net Framework installed. This might be different than above. You can compile with net452, but have 4.7.2 installed.
Fw 4.7.2 is installed on the machine.

* Version of Asp.Net MVC / Asp.NET Core used.
The one used in the sample application.

**Comment by AndersAbel** [comment]
Thanks for a detailed report, will look at it when I have time. Or if you want to submit a PR with a fix that's of course welcome. I would appreciate then to have a test case that reproduces the bug as part of the PR.

**Comment by lscorcia** [comment]
Thank you for your quick reply!

You will find attached the SAML assertion received from the IDP. I am trying to work with the IDP provider to fix their broken Issuer tag in the reply (it includes a NameQualifier attribute that's not allowed per spec), but you can check the library behaviour with the whitespace-including assertion.

[token.txt](https://github.com/Sustainsys/Saml2/files/3123984/token.txt)

I'll have a look at producing a PR if I can, but I have to say your code quality is impressive and I don't know if I can match it.

Thanks for your help!

**Comment by lscorcia** [comment]
Today I tried to replicate the problem and I wasn't able to reproduce it. I will close the issue now.
My apologies for wasting your time.
