### ISSUE TITLE
IDX10214: Audience validation failed in Multitenant application

### ISSUE THREAD

**Issue by angelsegurag** [Sustainsys/Saml2#1099]
My application is a multitenant system, implemented as an standalone angular app and asp.net core in the backend. The multitenancy is implemented with subdomains. Every customer may or may not want to use Saml2 for authentication.

I expected the "https://example.com" entityId to be replaced with the one set in the "AuthenticationRequestCreated" method, so the audiences match, but eventually it is comparing "https://{tenantid}.example.com/Saml2" with "https://example.com", so audiences doesn't match.

These are my settings

           services.AddAuthentication()
            .AddSaml2(options =>
            {                    
                options.Notifications.MetadataCreated = (request, urls) =>
                {                        
                    request.EntityId = new EntityId($"https://{tenantid}.example.com/Saml2");                               
                };

                options.Notifications.AuthenticationRequestCreated = (request, a, dict) =>
                {
                    request.Issuer = new EntityId($"https://{tenantid}.example.com/Saml2");
                };                 

                options.SPOptions.EntityId = new EntityId("https://example.com/");

**Comment by weitzhandler** [comment]
Have you managed to solve this problem?
I have the same issue, I'm working on a multi-tenant app, here's my config:

```c#
services.AddIdentityServerAuthentication(o =>
{
  o.Authority = Consts.MainUrl;
  o.ApiName = Consts.ApiScope; //"api"
  o.ApiSecret = Consts.UnoClientSecret;
  o.EnableCaching = true;
  o.SupportedTokens = SupportedTokens.Jwt;        
  o.RequireHttpsMetadata = true;        
});
```

The access token contains the following data (used [jwt.io](jwt.io)):

```json
{
  "nbf": 1564067106,
  "exp": 1564070706,
  "iss": "https://test.mysite.com",
  "aud": "https://test.mysite.com/resources",
  "client_id": "83ecbcd0-2ae9-4dfd-995f-87c1b7cdf933",
  "sub": "1",
  "auth_time": 1564067106,
  "idp": "local",
  "scope": [
    "openid",
    "profile",
    "offline_access"
  ],
  "amr": [
    "pwd"
  ]
}
```

When I try to access a protected resource under the `api` route with an attached token, I get the following exception:

> Bearer was not authenticated. Failure message: IDX10214: Audience validation failed. Audiences: 'https://test.aqounts.com/resources'. Did not match: validationParameters.ValidAudience: 'api' or validationParameters.ValidAudiences: 'null'.

The problem is that I can't provide the full Url, because it's dynamic, subdomains are per-tenant.

**Comment by nmocruz** [comment]
I got this trying to connect azure ,

IDX10214: Audience validation failed. Audiences: 'spn:f58dc713-5c7e-42e9-8a4f-3691a7152be7'. Did not match: validationParameters.ValidAudience: 'f58dc713-5c7e-42e9-8a4f-3691a7152be7' or validationParameters.ValidAudiences: 'null'.

I'm missing something maybe

**Comment by mschwitzer-helmoperations** [comment]
Solved this for myself, the audience issue can be solved by either disabling audience restriction verification, or by adding tenant URIs to the list of accepted audience URIs.


If you do not know the tenants while setting up SAML2 authentication and do not care about audience restriction verification:

```
SPOptions spOptions = ...;
spOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction.AudienceMode = AudienceUriMode.Never;
```


If you do know the tenants while setting up SAML2 authentication and want to include them in the set of allowed audience URIs:

```
SPOptions spOptions = ...;
foreach (var tenantId in tenantIds) {
    var uri = new Uri($"https://{tenantId}.example.com/Saml2");
	spOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction.AllowedAudienceUris.Add(uri);
}
```

**Comment by schwitzerm** [comment]
Solved this for myself, the audience issue can be solved by either disabling audience restriction verification, or by adding tenant URIs to the list of accepted audience URIs.


If you do not know the tenants while setting up SAML2 authentication and do not care about audience restriction verification:

```
SPOptions spOptions = ...;
spOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction.AudienceMode = AudienceUriMode.Never;
```


If you do know the tenants while setting up SAML2 authentication and want to include them in the set of allowed audience URIs:

```
SPOptions spOptions = ...;
foreach (var tenantId in tenantIds) {
    var uri = new Uri($"https://{tenantId}.example.com/Saml2");
	spOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction.AllowedAudienceUris.Add(uri);
}
```

**Comment by lbelloq** [comment]
> If you do not know the tenants while setting up SAML2 authentication and do not care about audience restriction verification:
> 
> ```
> SPOptions spOptions = ...;
> spOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction.AudienceMode = AudienceUriMode.Never;
> ```

Hi, as far as I can see, the `SPOptions` object does not have a `SystemIdentityModelIdentityConfiguration` property. How do you set this up?

**Comment by mjorrens1** [comment]
I have the same question as lbelloq. Has AudienceRestriction/AudienceMode been deprecated?
