### ISSUE TITLE
ClaimsAuthenticationManager in version 2.2.0

### ISSUE THREAD

**Issue by kluthje** [Sustainsys/Saml2#1101]
Hi

I'm trying to upgrade my app to use version 2.2.0 from 1.0.0 (running on .net 4.6.1). The new version seems to be missing a way to set a custom ClaimsAuthenticationManager, which is still talked about in documentation https://saml2.sustainsys.com/en/2.0/claims-authentication-manager.html#claimsauthenticationmanager . We were using it to do some claims manipulation. Is there an alternate way to handle this in the new version?

**Comment by AndersAbel** [comment]
You are right, the ClaimsAuthenticationManager is no longer present in 2.0, as it is part of the System.IdentityModel concept and not present in the Microsoft.IdentityModel stack used by 2.X.

If you are targeting .net 4.6.1, remaining on 1.0.0 is perfectly fine. It is a fully supported and stable release. If you want to move to 2.2.0 to get new functionaly, you can implement the AcsCommandResultCreated notification instead. You can alter or replace the created identity in the CommandResult.

I'm filing this issue as a bug, as it is clear that the docs need to be updated.
