### ISSUE TITLE
Invalid documentation of cacheDuration value

### ISSUE THREAD

**Issue by danielvrsek** [Sustainsys/Saml2#1102]
Everywhere in the documentation is shown that the correct format of the value of the cacheDuration attribute is for example `cacheDuration="1:00:00"`, but I encountered exception that says `the duration string does not start with 'P'`. I then "corrected" the value to P1D and it stopped showing the error.

There is an issue from 2014 that might be related? https://github.com/Sustainsys/Saml2/issues/115

Targetted framework version is 4.7.2 and MVC version should be 5.2.7 even though I don't think it could be related.

**Comment by AndersAbel** [comment]
The format used in web.config is a regular .NET TimeSpan. The format use din the actual generated XML is an XML string that should start with a P. Where do you encounter this error? The right format to use depends on the context.

**Comment by danielvrsek** [comment]
Sorry for so vague description. I am getting error from configuration in web.config. My problem is, that putting example values from documentation (https://saml2.sustainsys.com/en/2.0/config-elements/metadata.html#attributes) results in error. I have to have this in my web.config in order for it to work. `<metadata cacheDuration="P1D" validDuration="7.12:00:00" wantAssertionsSigned="true">`. If I change the value of `cacheDuration` to `0:0:42` (like in the example from documentation), it results in error. I can send further details, but I honestly don't know which could be relevant.

**Comment by AndersAbel** [comment]
What version of the library are you using?

**Comment by danielvrsek** [comment]
Latest one, 2.2.0

**Comment by AndersAbel** [comment]
Probably a bug in the 2.X port then. I'll mark it as a bug, but cannot promise any timeline for fixing it.

**Comment by toxictouch** [comment]
Just noticing the dates on this bug and wanted to update it to say it still seems to occur. I'm running SustainSys.Saml2.HttpModule version 2.8 and just had the same error as danielvrsek. Here's the message: _The value of the property 'cacheDuration' cannot be parsed. The error is: the duration string does not start with 'P'_

I can convert it back to using a P, just wanted to give an FYI to someone
