### ISSUE TITLE
AuthnRequest's NameIdPolicy should allow "0" or "1" for AllowCreate attribute

### ISSUE THREAD

**Issue by dougkpowers** [Sustainsys/Saml2#1128]
1. What nuget packages are you using  

Sustainsys.Saml2 v2.2.0

2. What is the expected behaviour

When constructing a Saml2AuthenticationRequest, if the AuthnRequest has a NameIdPolicy tag with an AllowCreate attribute set to "1" or "0" then the attribute value should be treated as true or false, respectively.

For example, the following tag should be allowed
    <samlp:NameIDPolicy AllowCreate="1" />

3. What happens instead.

A format exception is thrown because bool.Parse fails to interpret "0" as false and "1" as true.

The SAML2 specification always uses the strings "true" and "false" in their examples.  However, the xsd for the SAML protocol (http://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd) specifies that AllowCreate is of type "boolean" and the XML standard states that the allowed values for a boolean type are true, false, 1, and 0 (https://www.w3.org/TR/xmlschema11-2/#boolean).  The Saml2AuthenticationRequest constructor is only honoring the values of "true" and "false."  It is not honoring the values of "0" and "1"

**Comment by AndersAbel** [comment]
Thanks for noticing, clearly a bug.
