### ISSUE TITLE
Documentation missing?

### ISSUE THREAD

**Issue by MaximilianoTarrabe** [Sustainsys/Saml2#1138]
Im completely new to SAML2 and SSO solutions, but I was tasked to add my asp.net project as a SP to a SSO that's currently working as IdP (written in php using SimpleSamlPHP).
Other SP have been added to the "main hub" website but they are all php based and I have no easy access to their source code (or any at all mostl likely).

I followed the instructions for a webforms based .net project (correct Nuget package and changes to the web.config) and it doesn't seem to be working. I can manage to make https://stubidp.sustainsys.com/ to redirect to my aspx website but it doesnt login. Im clearly missing something obvious (probably code, yet in many cases I heard that config is more than enough to have it working).

So I pretty much would like to know if there's online documentation since I have no idea what classes or objects to use (or if for real I only need to change the web.config and it should be working)

**Comment by Gillardo** [comment]
Be interesting to see what code you have added to your project so far, then we could tell you what is missing?

**Comment by AndersAbel** [comment]
Check out the docs at http://saml2.sustainsys.com/en/2.0/ or the SampleHttpApplication in the repo.
