### ISSUE TITLE
Use CookieManager in Asp.Net Core

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#1150]
Asp.Net Core uses a Cookie Manager that can intercept and alter cookies that are about to be set. The Sustainsys.Saml2 way to handle that is a notification that decided when to emit a SameSite=None header or not based on the user agent string. It would be good to offer the standard cookie manager for use with the Asp.Net Core module too.

Intention was to get this into the 2.4.0 version with the SameSite fix #1091. Unfortunately it didn't make it due to being pressed of time.

If this is a breaking issue for anyone, please comment - it might be possible to make another small release with this implemented.

**Comment by explunit** [comment]
`Microsoft.Owin.Infrastructure.ICookieManager` would be very useful for the OWIN mode too, for things like #594 which continues to cause problems for us.
