### ISSUE TITLE
Easy way to add/remove items from the metadata

### ISSUE THREAD

**Issue by therrealdude** [Sustainsys/Saml2#1155]
Hi,

This might just be a question, but I can't seem to find an easy way to overwrite the service provider metadata without creating a whole new route. Would it be possible to provide an easy way to override the function CreateMetadata in SPOptionExtensions or maybe add a new property for things like the AssertionConsumerServices in the service provider options object so that can be set there instead of being automatically added?

Thanks!

**Comment by AndersAbel** [comment]
There are two notifications that let you alter the metadata: `MetadataCreated` where you can modify the object structure before serializing to XML and `MetadataCommandResultCreated` after XML serialization. The first one is probably more useful. Would anyone of those be a solution for you?

**Comment by therrealdude** [comment]
Thanks @AndersAbel ! I will look into those to see if they help. Would those be added in the startup file somewhere?

**Comment by AndersAbel** [comment]
Yes, the callbacks are set as properties on `Options.Notifications`.
