### ISSUE TITLE
Connecting Auth0 (IDP) and the Sustainsys SAML v2.0

### ISSUE THREAD

**Issue by kkagill** [Sustainsys/Saml2#1159]
Following [this article](https://medium.com/the-new-control-plane/connecting-auth0-idp-and-the-sustainsys-saml-v2-0-for-net-core-stack-b09509270fd1) to use Auth0 as IDP. 

When testing with Sustainsys package, redirecting back to SP creates an error. 

`Saml2ResponseFailedValidationException: Expected message to contain InResponseTo "id6c1f9b4a6c3a401sa6db63710d114b07", but found none. If this error occurs due to the Idp not setting InResponseTo according to the SAML2 specification, this check can be disabled by setting the IgnoreMissingInResponseTo compatibility flag to true.`

I've added `options.SPOptions.Compatibility.IgnoreMissingInResponseTo = true;`, but this doesn't solve the problem. 

Tested within Auth0 that it returns SAML response, but I think service provider does not receive it somehow. Would this be related to call back URL?

**Comment by AndersAbel** [comment]
Please use Chrome SAML Dev tools or a similar tool to inspect the received SAML response to check what it looks like.

I'm closing this for now, as I am fairly sure that it will turn out the InResponseTo is missing in the response. If it is indeed present, please comment and I'll reopen.
