### ISSUE TITLE
Error from Saml2 when my JWT token expires

### ISSUE THREAD

**Issue by arthurmmedeiros** [Sustainsys/Saml2#1160]
I use the JWT authentication in my .Net Core Application to authenticate in my API. Now I'm also using the Saml2 library to authenticate in the Idp, return the credentials, and than generate the Jwt token.

I create a token when the user authenticates in the application, store it using redux, and for every new request to the back end I put the token in the header. My application has a configuration that allows the user to set an expiration time. Therefore, if this feature is being used and the token expires, the backend will return 401, and the front end will redirect the user to the login page.

This is working fine without SAML2. Now, if I activate Saml2, the user authenticates in the application, navigates normally, but when the token expires, the backend returns 500 with the error "Incorrect Content-Type: application/json".

It took me a while to figure that this error is being caused by the Saml2 library. 
Here's the description of the error.
![image](https://user-images.githubusercontent.com/11875984/74938021-ff9a7300-53cb-11ea-892a-2c094d0d1b17.png)

Now, I know this seems to be a support question, but I only need to know if the JWT I create to authenticate the user could have any relation to this issue. 

Here I'm using .net Core with react JS.

**Comment by AndersAbel** [comment]
That looks like a bug in this library. I think there already is an issue about incorrectly accessing the form data.

**Comment by tkallsen** [comment]
We have the same problem (wrong content-type when ToHttpRequestData tries to access form data) when a user's session has expired during a POST, and ChallengeAsync in AspNetCore2.Saml2Handler is called.
