### ISSUE TITLE
SPOptions.Logger null reference exception

### ISSUE THREAD

**Issue by Wolfthorne** [Sustainsys/Saml2#1161]
### Information needed
Sustainsys.Saml2 - 2.4.0
Should run without null reference exceptions.
Either require SPOptions Logger or null check because it causes null reference exceptions

Issue #731 seems very similar but I am using the web config to create my SPOptions.

### Additional info
.Net Framework 4.7.2
Aspnet MVC 5.2.7

I was able to solve the issue by null checking where logger is used. If this is required it should error before.

**Comment by AndersAbel** [comment]
SPOptions should default to a NullLoggerAdapter, which removes the need to have null checks everywhere. What package are you using? HttpModule? Owin? AspNetCore2?

**Comment by Wolfthorne** [comment]
I am using the Owin package. I am also using the config option when I do
not pass SPOptions.

**Comment by AndersAbel** [comment]
The Owin module relies on `app.CreateLogger<T>()` to build a default logger. I don't understand how there can be a null ref in that case.

Can you please share a stack trace?
