### ISSUE TITLE
LoadMetadata setter attribute ordering issues

### ISSUE THREAD

**Issue by galaxyAbstractor** [Sustainsys/Saml2#1163]
## Information needed
1. What nuget packages are you using

AspNetCore2 version 2.4

2. What is the expected behaviour

When setting up a IdentityProvider, it should not matter in which order you specify fields:

```
saml2Options.IdentityProviders.Add(new IdentityProvider(
  new EntityId("<OktaIssuerUri>"), saml2Options.SPOptions)  // from (F) above
  {
    LoadMetadata = true,
    MetadataLocation = "https://<OktaInstance>/app/<OktaAppId>/sso/saml/metadata" // see Metadata note above
  });
```

(taken from [documentation](https://saml2.sustainsys.com/en/2.0/identity-server-3-okta.html#step-3-configure-your-identity-server-with-the-new-identity-provider))

3. What happens instead.

Due to `LoadMetadata`  having a setter which loads the metadata when the attribute is set and it is set to true, it will try to download the metadata from the url provided as entityId instead of using the uri provided in `MetadataLocation`, since this is set after the setter has ran. 

This can lead to very confusing errors and time spent figuring out why the wrong metadata is loaded, even though you clearly at a quick glance do provide a different metadata location. What makes it even more confusing is that the documentation itself use this ordering.

Some IDP's like AWS SSO do not follow the Saml2 standard regarding `EntityId` == `MetadataLocation`, and in these cases you have to specify `MetadataLocation` yourself, and this will make the module throw an exception since the EntityId does not match when using the metadata url as EntityId.

### Additional info
Please include
* .Net Framework your application is compiled against (e.g. `net472`, `netcoreap2.1`)
* .Net Framework installed. This might be different than above. You can compile with net452, but have 4.7.2 installed.
* Version of Asp.Net MVC / Asp.NET Core used.

Netcoreapp3.1

**Comment by AndersAbel** [comment]
Thanks for noticing. In this case LoadMetadata should never be set. The only use for that property is when the Metadata address is derived from the EntityId.
