### ISSUE TITLE
404 error recieved during logout when the initial request was not a 30x redirect

### ISSUE THREAD

**Issue by duncanworthy** [Sustainsys/Saml2#1166]
### Expected

The 303 response from the Sustainsys Logout (e.g. http://myserver/myapp/Saml2/Logout?SAMLResponse=...) should point to the URL that was requested before the logout occurred.

### Actual

The application base path gets lost from the path issued in the 303 redirect response.
This means that the user's browser is directed to an invalid location and the user experiences a 404 error page.
This issue only occurs in the case where the request that resulted in the logout is not a 30x redirect.

### Additional info
Using Sustainsys.Saml2 and Sustainsys.Saml2.Owin version 2.4.0
ASP.NET MVC 4, compiled in VS 2019 against .NET 4.6.2 with .NET 4.6.2 SDK installed, but originally observed in production environments with different .NET framework versions installed

**Comment by AndersAbel** [comment]
Do I get this right if this happens after the redirect roundtrip to the Idp?

1. User initiates logout at /basepath/somepath/somepage
2. User is redirected to Idp
3. Idp responds by redirecting back to /basepath/Saml2/Logout?SAMLResponse=XYZ
4. The Logout redirects incorrectly to /somepath/somepage and lost /basepath?

**Comment by duncanworthy** [comment]
That is correct, except that the situations in which I've seen it are not "user initiated logout", in the sense that the user caused the logout indirectly.
When the user clicks the logout link in our application everything works fine.
I've seen it most frequently when the user has closed their browser without logging out and later tries to access the application after their session has expired.

**Comment by AndersAbel** [comment]
That sounds like a really weird scenario for the logout to be triggered. But nevertheless, I found the bug and will fix it. There's just some fiddling to do to ensure that PublicOrigin is handled correctly - it overrides PathBase if set.
