### ISSUE TITLE
Cookie is not created anymore in Chrome 80

### ISSUE THREAD

**Issue by Olko7** [Sustainsys/Saml2#1169]
Hello, 

After we got new Chrome version we cannot login anymore.
We made changes for normal ASP.Net Core login ( options.Cookie.SameSite = (SameSiteMode)(-1);) and it helped.

But with Sustainsys Saml2 there are problems:
It never worked for us if we set app.UseCookiePolicy(); (and this was mentioned earlier in other issues). 
Now if we remove app.UseCookiePolicy() we got 400 Bad request for SAML2 redirect (just at first step).
If we add  app.UseCookiePolicy() we can proceed to next step where Cookie should be created:
```
httpContext.Response.Cookies.Append(
                    commandResult.SetCookieName,
                    cookieData,
                    new CookieOptions()
                    {
                        HttpOnly = true,
                        Secure = commandResult.SetCookieSecureFlag,
                        // We are expecting a different site to POST back to us,
                        // so the ASP.Net Core default of Lax is not appropriate in this case
                        SameSite = emitSameSiteNone ? SameSiteMode.None : (SameSiteMode)(-1),
                       // IsEssential = true
                    });
```
But is not created at all and we got exception:
Sustainsys.Saml2.Exceptions.UnexpectedInResponseToException: 'Received message contains unexpected InResponseTo "id.........". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.'

**Comment by AndersAbel** [comment]
What version of Sustainsys.Saml2 are you running? Only 1.0.1 and 2.4.0 are compatible with the new SameSite rules.

**Comment by Olko7** [comment]
> 
> 
> What version of Sustainsys.Saml2 are you running? Only 1.0.1 and 2.4.0 are compatible with the new SameSite rules.

These tests are for 2.4.0

**Comment by Olko7** [comment]
I think earlier presense of line "app.UseCookiePolicy()" leads to the same exception so we deleted it.

But with new Chrome this is no more an option and this line should be included.

**Comment by AndersAbel** [comment]
I've seen cases where the owin cookie monster bug have occured in more deployments lately. So I guess that might be the reason that the cookie is lost.

Can you please try #1168 and see if that works?

Also please remove any usage of Kentor.OwinCookieSaver if you have it. It does not work with SameSite.

**Comment by Olko7** [comment]
We use Sustainsys.Saml2.AspNetCore2, are changes in #1168 applicable for this?

**Comment by AndersAbel** [comment]
> We use Sustainsys.Saml2.AspNetCore2, are changes in #1168 applicable for this?
No, sorry. I was just reviewing that PR so I mixed them up.

Can you please see if the set-cookie header is set when initiating the log in?

**Comment by Olko7** [comment]
Thanks,  no, this header is not set.

**Comment by AndersAbel** [comment]
Ok, then some debugging is needed of your environment to see why the cookie is lost.
1. What exactly is the problem if app.UseCookiePolicy() is used?
2. If the code you showed above is called - is there something else that later removes the cookie?

**Comment by Olko7** [comment]
1. Still checking
2. I copy here all things that can be related to cookies and login
` public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options => {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = (SameSiteMode)(-1);
                options.OnAppendCookie = cookieContext =>
                    CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
                options.OnDeleteCookie = cookieContext =>
                    CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
            });

            services.AddIdentity<User, Role>(options => {
			...
            })
                .AddDefaultTokenProviders()
                .Services.ConfigureApplicationCookie(options =>
                {
                    options.SlidingExpiration = true;
                    options.ExpireTimeSpan = TimeSpan.FromMinutes(Configuration.GetValue<int>("Identity:ExpireTimeSpan"));
                });


            services.ConfigureApplicationCookie(options => {
                options.SessionStore = new MemoryCacheTicketStore(Configuration.GetValue<int>("Identity:ExpireTimeSpan"));
                options.LoginPath = $"/";
                options.LogoutPath = $"/Identity/Account/Logout";
                options.AccessDeniedPath = $"/Identity/Account/AccessDenied";
            });

            services.AddAntiforgery(options =>
            {
                options.Cookie.SameSite = (SameSiteMode)(-1);
                // we supress antiforgery to allow use app in iframe
                // so we must setup this in iis: Content-Security-Policy, x-Content-Security-Policy, X-Frame-Options
                options.SuppressXFrameOptionsHeader = true;
            });

            services.ConfigureApplicationCookie(options => {
                options.Cookie.Name = "RcAuthCookie";
                options.Cookie.SameSite = (SameSiteMode)(-1);               
            });

            services.AddCors(options =>
            {
                options.AddPolicy("AllowSpecificOrigin", builder => builder.WithOrigins(Configuration.GetSection("CorsUrls").Get<string[]>()));
            });

            var samlOptions = new Saml2Options();
            var spOptions = new SPOptions();
            samlOptions.SPOptions = spOptions;

            spOptions.EntityId = new EntityId(Configuration["SsoConfiguration:EntityId"]);
            spOptions.ReturnUrl = new Uri(Configuration["SsoConfiguration:ReturnUrl"]);

            var idp = new IdentityProvider(new EntityId(Configuration["SsoConfiguration:MetadataAddress"]), spOptions)
            {
                AllowUnsolicitedAuthnResponse = true,
                SingleSignOnServiceUrl = new Uri(Configuration["SsoConfiguration:SingleSignOnServiceUrl"]),
                SingleLogoutServiceUrl = new Uri(Configuration["SsoConfiguration:SingleLogoutServiceUrl"]),
                Binding = Sustainsys.Saml2.WebSso.Saml2BindingType.HttpRedirect
            };
            idp.SigningKeys.AddConfiguredKey(new X509Certificate2(Configuration["SsoConfiguration:X509Certificate2Path"]));
            samlOptions.IdentityProviders.Add(idp);

            services.AddAuthentication()
                .AddCookie(o => o.SessionStore = new MemoryCacheTicketStore(Configuration.GetValue<int>("Identity:ExpireTimeSpan")))
                .AddSaml2("SSO", "Partner Provider", options => {
                    options.SPOptions = spOptions;
                    options.IdentityProviders.Add(idp);
                });

        }`




` public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCookiePolicy();

            app.UseCors(builder => builder.AllowAnyOrigin());

            app.UseAuthentication();

           
        }`

**Comment by Olko7** [comment]
`public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCookiePolicy();

            app.UseCors(builder => builder.AllowAnyOrigin());

            app.UseAuthentication();

           
        }`

**Comment by AndersAbel** [comment]
Just a question - the code snippet you showed above has commented out the IsEssential=true line. Are you experiencing this in a private build with that source? Or are you using the official Nuget package? If you have UseCookiePolicy and IsEssential is not set, the cookie is expected to be discarded...

**Comment by Olko7** [comment]
Thanks for notice! It's build from latest release source. This line was commented out because there is not such property in CookieOptions
![image](https://user-images.githubusercontent.com/34068382/76977928-112d5700-6947-11ea-8197-8667f8391c53.png)

**Comment by AndersAbel** [comment]
> Thanks for notice! It's build from latest release source. This line was commented out because there is not such property in CookieOptions

You are running on an unsupported version of Asp.NET Core. Upgrade to a supported version and use the official Sustainsys.Saml2 nuget packages (or a clean build from the source, without any modifications).

You stated that you are using 2.4.0, which is simply untrue. Don't waste my time by troubleshooting when you're running modified versions without telling.

**Comment by Olko7** [comment]
Thank you very much for help, sorry we didn't understood that problem was in unsupported version.
