### ISSUE TITLE
MetadataSerializationException: IndexedEndpoint element missing index attribute

### ISSUE THREAD

**Issue by emreaatalay22** [Sustainsys/Saml2#1171]
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadIndexedEntryWithDefaultAttributes(XmlReader reader, IIndexedEntryWithDefault entry)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadIndexedEndpointAttributes(XmlReader reader, IndexedEndpoint endpoint)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadWrappedIndexedEndpoint<T>(XmlReader reader, Func<T> createInstance)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadAssertionConsumerService(XmlReader reader)
Sustainsys.Saml2.Metadata.MetadataSerializer+<>c__DisplayClass141_0.<ReadSpSsoDescriptor>b__0()
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadChildren(XmlReader reader, Func<bool> childAction)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadSpSsoDescriptor(XmlReader reader)
Sustainsys.Saml2.Metadata.MetadataSerializer+<>c__DisplayClass118_0.<ReadEntityDescriptor>b__0()
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadChildren(XmlReader reader, Func<bool> childAction)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadEntityDescriptor(XmlReader reader, SecurityTokenResolver tokenResolver)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadMetadataCore(XmlReader reader, SecurityTokenResolver tokenResolver)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadMetadata(XmlReader reader, SecurityTokenResolver tokenResolver)
Sustainsys.Saml2.Metadata.MetadataSerializer.ReadMetadata(XmlReader reader)
Sustainsys.Saml2.Metadata.MetadataLoader.Load(XmlDictionaryReader reader)
Sustainsys.Saml2.Metadata.MetadataLoader.Load(string metadataLocation, IEnumerable<SecurityKeyIdentifierClause> signingKeys, bool validateCertificate, string minIncomingSigningAlgorithm)
Sustainsys.Saml2.Metadata.MetadataLoader.LoadIdp(string metadataLocation, bool unpackEntitiesDescriptor)
Sustainsys.Saml2.IdentityProvider.DoLoadMetadata()
Sustainsys.Saml2.IdentityProvider.set_LoadMetadata(bool value)
Sustainsys.Saml2.IdentityProvider.set_MetadataLocation(string value)
SamlClientCore2._2.Startup+<>c__DisplayClass4_0.<ConfigureServices>b__4(Saml2Options options) in Startup.cs
-
            })
            .AddSaml2(options =>
            {
                options.SPOptions.EntityId = new EntityId("http://localhost:61233");
                options.SPOptions.MinIncomingSigningAlgorithm = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
            options.IdentityProviders.Add(
            new IdentityProvider(
            new EntityId("http://localhost:61233"),
              options.SPOptions)
            {
                MetadataLocation = pathxml,
                LoadMetadata = true,
Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>.Configure(string name, TOptions options)
Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string name)
Sustainsys.Saml2.AspNetCore2.Saml2Handler+<>c__DisplayClass6_0.<InitializeAsync>b__0()
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy<T>.CreateValue()
Microsoft.Extensions.Options.OptionsCache<TOptions>.GetOrAdd(string name, Func<TOptions> createOptions)
Sustainsys.Saml2.AspNetCore2.Saml2Handler.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, string authenticationScheme)
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by AndersAbel** [comment]
I'm sorry but this lacks a lot of context needed. Please try again and this use the Bug Report issue template and answer the questions in there.
