### ISSUE TITLE
SAML2.httpmodule with windows authentication without prompting for user credential

### ISSUE THREAD

**Issue by anarshadali** [Sustainsys/Saml2#1172]
@AndersAbel Hi,
I have a web application on dotnet framework 4.7.2 now with windows authentication.
Now wanted it to move with ADFS Authentication using SAML2. Currently i am using [Sustainsys.Saml2.HttpModule](https://www.nuget.org/packages/Sustainsys.Saml2.HttpModule/) library
Query/Support/help: 
1. How can I achieve SSO without any login prompt (except the normal windows login after startup).
Right now I need to login once but I want to check against the currently logged in windows user.
2. what is should i put into **signingCertificate** and **serviceCertificates**. I have generated metadata from my IDP.

**Comment by AndersAbel** [comment]
1. Configure the ADFS server to support windows integrated sign on. How to do that and limitations to when it works is outside the scope of this library to discuss.
2. You don't need any of those for a simple setup. Just set the Idp metadatalocation and the needed certificate will be loaded automatically from there.
