### ISSUE TITLE
Cannot install Sustainsys.Saml2.MVC 2.4.0 .net Framework 4.6.1

### ISSUE THREAD

**Issue by leeolage** [Sustainsys/Saml2#1176]
I'm trying to install Sustainsys.Saml2.MVC in a project that targets .NETFramework 4.6.1 but get the error:

Could not install package 'Sustainsys.Saml2.Mvc 2.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

But I could install version 2.3.0

**Comment by AndersAbel** [comment]
2.4.0 requires 4.7.2 as that's the lowest version that supports the [HttpCookie.SameSite](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpcookie.samesite?view=netframework-4.8) property.
