### ISSUE TITLE
Trying to integrate Okta in IdentityServer4 sample. 

### ISSUE THREAD

**Issue by cehsonu100** [Sustainsys/Saml2#1177]
Trying to integrate Okta in IdentityServer4 sample. But in code, that is in doc - https://github.com/Sustainsys/Saml2/blob/master/docs/identity-server-3-okta.rst, for many methods it is saying : 
==>  ... does not contain a definition for "..."
or ==> The name '...' does not exist in the current context. 

It will be helpful if all assembly references are provided.

**Comment by AndersAbel** [comment]
IdentityServer4 and IdentityServer3 are different and IdentityServer3 is not even supported any more. For the Saml2 configuration, IdentityServer3 uses the Owin module while IdentitytServer4 uses AspNetCore and they are different. I think that it is about time to retire the IdentityServer3 documentation.

**Comment by cehsonu100** [comment]
OK thank you for your clarification. Is it any way to configure Okta SAML2 with .Net Core with help of Sustainsys?

**Comment by AndersAbel** [comment]
Yes, the .NET Core library has the same SAML2 protocol capabilities, but I have no step-by-step documentation for it.
