### ISSUE TITLE
 database operation failed while processing the request.

### ISSUE THREAD

**Issue by thstopinski** [Sustainsys/Saml2#1179]
When I try to run the saml2 .net core sample I get following error after clicking the register button on the register new user page:

SqlException: Cannot open database "aspnet-SampleAspNetCore2ApplicationNETFramework-53bc9b9d-9d6a-45d4-8429-2a2761773502" requested by the login. The login failed.
 Login failed for user 'UK-2019920297\thstopinski'.
 
Applying existing migrations for ApplicationDbContext may resolve this issue
There are migrations for ApplicationDbContext that have not been applied to the database
• 00000000000000_CreateIdentitySchema
Apply Migrations 
In Visual Studio, you can use the Package Manager Console to apply pending migrations to the database:
PM> Update-Database
Alternatively, you can apply pending migrations from a command prompt at your project directory:
> dotnet ef database update

**Comment by AndersAbel** [comment]
That is how Asp.Net Core applications work with Asp.Net Identity and is not a Saml2-specific issue. Please follow the instructions or find some information on Asp.Net Identity.
