### ISSUE TITLE
Artifact binding throws NotImplementedException

### ISSUE THREAD

**Issue by djmnz** [Sustainsys/Saml2#1180]
Version sustainsys 2.6
Using the sample AspNetCoreNetFramework

```
                    options.IdentityProviders.Add(
                        new IdentityProvider(
                            new EntityId($"http://something.com/"), options.SPOptions)
                        {
                            MetadataLocation = $"http://something.com/",
                            LoadMetadata = true,
                            Binding = Saml2BindingType.Artifact,
                        });
```

It looks like the ArtifactBinding class doesn't implement the Bind method from the abstract class :(
```

NotImplementedException: The method or operation is not implemented.
Sustainsys.Saml2.WebSso.Saml2Binding.Bind<TMessage>(TMessage message, ILoggerAdapter logger, Action<TMessage, XDocument, Saml2BindingType> xmlCreatedNotification) in Saml2Binding.cs
+
            throw new NotImplementedException();
Sustainsys.Saml2.IdentityProvider.Bind<TMessage>(TMessage message, Action<TMessage, XDocument, Saml2BindingType> xmlCreatedNotification) in IdentityProvider.cs
+
            return Saml2Binding.Get(Binding).Bind(message, spOptions.Logger, xmlCreatedNotification);
Sustainsys.Saml2.WebSso.SignInCommand.InitiateLoginToIdp(IOptions options, IDictionary<string, string> relayData, Saml2Urls urls, IdentityProvider idp, Uri returnUrl, HttpRequestData request) in SignInCommand.cs
+
            var commandResult = idp.Bind(authnRequest, options.Notifications.AuthenticationRequestXmlCreated);
Sustainsys.Saml2.WebSso.SignInCommand.Run(EntityId idpEntityId, string returnPath, HttpRequestData request, IOptions options, IDictionary<string, string> relayData) in SignInCommand.cs
+
            return InitiateLoginToIdp(options, relayData, urls, idp, returnUrl, request);
Sustainsys.Saml2.AspNetCore2.Saml2Handler.ChallengeAsync(AuthenticationProperties properties) in Saml2Handler.cs
+
            var result = SignInCommand.Run(

```

**Comment by AndersAbel** [comment]
Is this something that have changed after an upgrade to 2.6.0? Or is this new code?

I don't think that it has ever worked, artifact binding is only supported for receiving message from the Idp, not for sending messages to the Idp.

**Comment by djmnz** [comment]
Yep, this is new code.

So initialising the artifact binding flow needs to be done outside sustainsys ? Sorry couldn't find any example :(

**Comment by AndersAbel** [comment]
Typically the Artifact binding is used when the Idp sends the response back. So the configuration for that is done in the Idp. The Sustainsys.Saml2 library lists Artifact as a supported binding for responses in the generated metadata.

Technically there request to the idp could be sent via Artifact to, but I have never seen it being done. Usually Http Redirect is used for the request to the Idp (that's what you should enter in the config) and then the Idp can be configured for Artifact.

The reason I'm asking if this is new code or not, and why i added the bug label is that i made quite extensive changes to the binding code for version 2.6.0. So first I thought this was a bug I introduced.
