### ISSUE TITLE
Break out Metadata to separate library

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#1181]
The first step on the v3 road map is to break out the metadata to a separate library.

## Suggested features
* Metadata data classes, based off the Saml2 metadata spec.
* Support for extensions (where the metadata spec allows)
* Deserializing from XML, including signature validation.
* Serializing to XML, including signature creation.
* Metadata refresh timing helpers based on cacheDuration and validUntil.

## Technical choices
* All reading/writing should be done to XmlReaders/Writers.
* Use XmlDocument and SignedXml for signature handling.

## Questions to discuss
* Should WS-Federation Metadata be supported too?
* What test framework and assertion library should be used? MsTest is too unflexible. XUnit + FluentAssertions?

## Not in this library
My intention is to have this is a pure metadata library that can be used in other products as well. So I think it should not have dependencies on Asp.Net Core or the Microsoft DI model. Constructor DI may be used though as that is a generic pattern.
* Actual Metadata loader and refresh scheduler, that is a concern for the protocol implementations.
* Creation of configuration objects (such as Sustainsys.Saml2's IdentityProvider or Asp.Net Core's WSFederation configuration) from Metadata.

**Comment by rpmansion** [comment]
> Should WS-Federation Metadata be supported too?

I think we  should as some of the clients I have worked with the SAML2 integration uses WS-Federation -- they are universities.

**Comment by rpmansion** [comment]
> Actual Metadata loader and refresh scheduler, that is a concern for the protocol implementations.
Since protocol implementation will not be added, I also like to add (for consideration) that there are metadata with EntityId that does not conform with 'http://' instead they use XML namespace convention.

**Comment by AndersAbel** [comment]
> > Actual Metadata loader and refresh scheduler, that is a concern for the protocol implementations.
> 
> Since protocol implementation will not be added, I also like to add (for consideration) that there are metadata with EntityId that does not conform with 'http://' instead they use XML namespace convention.

Yes, validation should be very flexible/lax. Maybe issue errors on totally invalid or things that could break security. But issue rest as warnings and have some kind of treat-warnings-as-errors setting.

**Comment by rpmansion** [comment]
Referencing to support #1040

**Comment by rpmansion** [comment]
Helpful utility for attributes 
[AttributeMapper.txt](https://github.com/Sustainsys/Saml2/files/4430670/AttributeMapper.txt)

**Comment by rpmansion** [comment]
@AndersAbel I'm in progress working with the Metadata. I also created a branch for Metadata and would need permission to push this.

**Comment by rpmansion** [comment]
referencing #1182 for initial changes.
