### ISSUE TITLE
Sample Custom IdentityProvider (IDP) for SAML 2.0

### ISSUE THREAD

**Issue by martinkoslof** [Sustainsys/Saml2#1186]
Hello, I just ran across this library and it looks interesting. I'm trying to decipher the full functionality and what this library supports and provides. I need to create my own SAML 2.0 IdentityProvider (IDP). I actually need to wrap windows/kerberos authentication and provide a SAML 2.0 compliant end point.

I was looking at the samples and I wasn't sure which one was an actual IDP implementation. It appears the samples stem around external logins, existing providers and middleware.  Can this library be used to expose an actual IDP endpoint? Are there any examples of using Active Directory, SQL Server, really any actual "login source" and then wrapping this in a IDP Server layer?

Thanks for your help.

**Comment by AndersAbel** [comment]
The library is mostly an SP implementation. But the protocol parts needed to implement an Idp are available. The StubIdp is a dummy Idp implementation that works on the protocol level. But to make a proper production Idp would require quite a lot of work to implement all the security measure needed.
