### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ganinja** [Sustainsys/Saml2#1187]
Does SustainSys only support a single cert.  For instance what if you have a SaaS and each company using it has its own Azure AD account wouldn't you have to support multiple certificates?

**Comment by AndersAbel** [comment]
Can you please be a bit more clear about what cert you are thinking of? There is support for cert/key rollover for both the SP, Idp and Federation certificates.

**Comment by hgomez01** [comment]
Quick question @AndersAbel Do you know if is possible to extend and create a custom ACS implementation?
