### ISSUE TITLE
Unable to install the MVC NuGet pacakage on a .net framework 4.7.1 project.

### ISSUE THREAD

**Issue by amiteshramname** [Sustainsys/Saml2#1190]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Sustainsys.Saml2.Mvc 2.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by AndersAbel** [comment]
The MVC package requires at least .NET Framework 4.7.2.
