### ISSUE TITLE
harmonize path comparison

### ISSUE THREAD

**Issue by brockallen** [Sustainsys/Saml2#1193]
In the ASP.NET Core auth handler we have a case-sensitive check like this:

```
if (context.Request.Path.StartsWithSegments(options.SPOptions.ModulePath, StringComparison.Ordinal))
```

But in the command factory we have a check like this:

```
if(commandName.StartsWith("/", StringComparison.OrdinalIgnoreCase))
```

So perhaps we might want both to be the same? I'd guess case insensitive would be preferred?

**Comment by explunit** [comment]
HttpModule has ignore case too https://github.com/Sustainsys/Saml2/blob/v2.7.0/Sustainsys.Saml2.HttpModule/Saml2AuthenticationModule.cs#L62
