### ISSUE TITLE
Right way to perform local logout with SustainSys HttpModule

### ISSUE THREAD

**Issue by billmcknight1953** [Sustainsys/Saml2#1196]
I am using the SustainSys HTTPModule in an ASP.NET MVC 5 web application.  The HTTPModule works very well with my IdP and successfully establishes User.Identity.IsAuthenticated and the claims returned by the IdP.

Now I want the application to logout locally, so that it behaves as it would if one closed the browser.  I do not want to perform an SLO (Single Logout ) with the IdP, but I do want to "sign out".  **What is the correct way to do that ?**  I am aware there are cookies (at least two of them) established on each sign in with the IdP, whose expiration date is "session".

**Comment by AndersAbel** [comment]
To make a local-only logout, use the API of the `SessionAuthenticationModule` to logout (that's the module in charge of the cookie).

**Comment by billmcknight1953** [comment]
I know this issue is closed but  I had a followup question.  I added logout code using the same code as found in the mvc saml2controller logout method.  This indeed removed the cookies.  However, it seems that User.Identity.IsAuthenticated is still true after the cookies are removed, and consequently the user still has to close the browser to force re-signin to IdP.  if the browser (Chrome) is still open then just going to the main page refreshes the cookies immediately,
