### ISSUE TITLE
Add Custom Assertion Consumer URL

### ISSUE THREAD

**Issue by RoLYroLLs** [Sustainsys/Saml2#1198]
I wanted to know if it was possible to add multiple Assertion Consumer URLs programmatically, or through the Web.config file. For example, I want my metadata to contain urls to my multiple dev and QA sites (not production), so that it's easier to test on my dev and QA IDP by only adding 1 SP on it.

Thanks.

**Comment by AndersAbel** [comment]
Hook the `MetadataCreated` notification and add the endpoints for your other environments to get them in metadata. Then load that metadata into your Idp.
