### ISSUE TITLE
Missing signing certificate

### ISSUE THREAD

**Issue by selvakumar79** [Sustainsys/Saml2#1199]
I'm getting the below issue from Saml2 1.0 version in my Asp.net MVC project 
I'm using A SAML2 Service Provider for ASP.NET MVC
Please help me reslove the issue
Missing signing certificate configuration on Idp  
[ConfigurationErrorsException: Missing signing certificate configuration on Idp  https://econnectnext09.amat.com/dana-na/auth/saml-endpoint.cgi.]
   Sustainsys.Saml2.IdentityProvider.Validate() +322
   Sustainsys.Saml2.IdentityProvider.set_LoadMetadata(Boolean value) +37
   Sustainsys.Saml2.IdentityProvider..ctor(IdentityProviderElement config, SPOptions spOptions) +895
   Sustainsys.Saml2.Configuration.IdentityProviderCollection.RegisterIdentityProviders(IOptions options) +184
   Sustainsys.Saml2.Configuration.Options.LoadOptionsFromConfiguration() +127
   System.Lazy`1.CreateValue() +734
   System.Lazy`1.LazyInitValue() +189
   Sustainsys.Saml2.Mvc.Saml2Controller.get_Options() +80
   Sustainsys.Saml2.Mvc.Saml2Controller.SignIn() +57
   lambda_method(Closure , ControllerBase , Object[] ) +87
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +77
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__11_0() +72
   System.Web.Mvc.Async.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +396
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__3() +50
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +431
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +75
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +158

**Comment by KayodeBakker** [comment]
Just trying to help while being inexperienced myself but does the metadata of the IDP even mention certificate data? If not, maybe it has something to do with that?

**Comment by selvakumar79** [comment]
Hi Kayode,

Thanks for your mail.
Yes in  IDP metadata there is a X509 data certificate.
I did not get any cer and pfx file from my IDP provider, so i did not
include  <signingCertificate > and <serviceCertificates> in my webconfig.
Also which location i have to mention in below metadatalocation
<federations>
<add metadataLocation="" allowUnsolicitedAuthnResponse="true" /> </
federations>

Thanks
Selva

**Comment by selvakumar79** [comment]
Hi ,

After added the certificate i'm getting the below error

SAML Transfer Failed. Please contact your administrator.Details: Incompatible SAML Authentication request. (ACS http://mytestapp.com/Saml2/Acs requested in unsigned AuthnRequest is not configured for SP metadata present on SA)
--

**Comment by AndersAbel** [comment]
@selvakumar79 That looks like the Idp is not configured with your location `http://mytestapp.com/Saml2/Acs`. Although it mentions signing, there is probably no need to sign the AuthnRequest - instead ask the Idp admin to add that location as a valid response location.

**Comment by selvakumar79** [comment]
Hi AndersAbel,
Thanks for the reply.
Now i'm getting the below error.
SAML Transfer Failed. Please contact your administrator.

Details: Incompatible SAML Authentication request. (IdP is not configured to support SP-initiated SSO for http://mytestapp.com/Saml2)

Selva

**Comment by AndersAbel** [comment]
Please read the error message: The Idp is not configured for what you are trying to do. Talk to the Idp admin.
