### ISSUE TITLE
Service provider and SingleLogOutService

### ISSUE THREAD

**Issue by KayodeBakker** [Sustainsys/Saml2#1200]
I am currently trying to make use of the Sustainsys.Saml2.Owin nuget package but honestly have never really used Saml2 in general before. I am in kind of a discussion with someone more experienced in Saml2 (not necessarily Sustainsys.Saml2.Owin) and while discussing the SP metadata I showcased I received a remark regarding to the SingleLogOutService. It was stated that it is abnormal for the SingleLogOutService to be defined in the SP metadata as this should normally be something for the IDP metadata to define. He also stated that he in general only expected the SP metadata to have the AssertionConsumerService.

Mainly because I severly lack the experience and he seems to have more, I tend to believe what he's saying but that does raise an interesting question in my opinion. When defining the SPOptions in C#, the SingleLogOutService is automatically added to my SP metadata as part of the functionality provided by the nuget package. My question mainly is, why is this and if this is correct behaviour, could you help speculate why I am getting remarks such as these?

Hopefully you can help shed some light on this matter as I thought I was following examples and instructions fairly well.

At this moment I am using Sustainsys.Saml2.Owin version 2.3.0 and plan on updating to 2.7.0 in the near future.

**Comment by AndersAbel** [comment]
The Idp admin is wrong.

For single logout to work both the Idp and the SP need to define a SingleLogoutService. If the logout is initiated from the SP, the SP redirects to the Idp's single logout service. Once the Idp is done, it redirects back to the SPs single logout service. So both need to define a SingleLogoutService for SLO to work.
