### ISSUE TITLE
Request Signing Configuration Expiring?

### ISSUE THREAD

**Issue by benmann497** [Sustainsys/Saml2#1202]
Hello,

We are using the Saml2 library to integrate with ADFS for SAML authentication in a .Net Core 3.1 MVC application, using the standard AuthenticationBuilder AddSaml2 in Startup. Our ADFS requires requests to be signed, so we have set up the IdentityProvider configuration to read the metadata and set the "WantAuthnRequestsSigned" as well as the configuring the required certificates. This all works fine, handing over the ADFS for credentials etc and returning the required Claims.

The destination of our AuthnRequests being Destination="https://xxxx/adfs/ls/idpinitiatedsignon"

However after ~ 30 mins, the auth requests stop including the signature and change to Destination="https://xxxx/adfs/ls/" - this causes ADFS to reject the request complaining that the request is not signed.

I'm trying to work out whether there is some metadata timeout that I am missing, or something like that? Hopefully there is a simple setting that we are missing.

Thanks,

**Comment by AndersAbel** [comment]
If it changes after that time I would definitely guess that Metadata is reloaded and overwrites any manual settings you have applied.

To preserve your custom settings, don't load metadata (neither set `MetadataLocation` nor `LoadMetadata` on the IdentityProvider object). Instead you'll have to set the relevant properties yourself.

**Comment by benmann497** [comment]
Hi @AndersAbel 

Many thanks for this, it has highlighted to our AD team where the metadata isn't reflecting the signing requirement in the first place and this is in fact what needed to be updated.

[ADFS metadata](https://stackoverflow.com/questions/43808902/how-to-configure-adfs-so-that-it-indicates-authentication-requests-should-be-sig) - was handy in working out the metadata issue and a global setting not agreeing with the particular trust setting.

Thanks.
