### ISSUE TITLE
Sampe AspNetCore2 Example Requires Encyrption?

### ISSUE THREAD

**Issue by cbadger360** [Sustainsys/Saml2#1204]
Hello,

I was able to get the _SampleMvcApplication_ project up and running with Okta as the IdP with no problems.  However, trying the same thing with the _SampleAspNetCore2ApplicationNETFramework_ project is proving more difficult.  This example seems to register the signing certificate in such a way that it's also required to be usable for encryption. I have a cert from Okta that I can use for the signing, but no pfx file that can be used for encrypting/decrypting.

Is there any way register my certificate in this sample in a way where it won't insist on it being usable for encryption/decryption?

Thanks.

**Comment by AndersAbel** [comment]
Yes, the certificate handling is somewhat confusing. The one you are adding on the Idp level is the public key of the Idp that is used to verify incoming messages from the Idp. The one in SPOptions is for signing outbound messages (mostly used for logout) or enabling encryption of received messages (don't do that if you don't really have to, it makes things complicated).
