### ISSUE TITLE
[Question] From documentation it's unclear if .NET Core 3.x is supported by v2 of Sustainsys.Saml2

### ISSUE THREAD

**Issue by nzhuravel** [Sustainsys/Saml2#1211]
Hi! 
My team is considering opensource solutions to add SAML2.0 support to our IdentityServer4. It is currently based on .NET Core 2.2, but we will soon migrate to .NET Core 3.x. I looked through documents and I am under impression that:
Sustainsys.Saml2 (v2) is only for .NET Core 2.x, 
Sustainsys.Saml2 (v3), which is still in development phase, will be for .NET Core 3.x. 
Is that assumption correct?
Thanks.

**Comment by blushingpenguin** [comment]
Sustainsys.Saml2 (v2) works fine with .NET Core 3.x
v3 is for an API overhaul leaving some of the legacy frameworks behind (as I understand it).

**Comment by nzhuravel** [comment]
Hi! One more question from our team:
Are there any proves that implementation of SAML follows security guidelines (maybe some certification was passed etc.). We are trying to compare opensource solution vs those under licence and this was a question from our security engineers.
I haven't found any information on that in [here ](https://saml2.sustainsys.com/en/stable/index.html)

**Comment by AndersAbel** [comment]
There have been independent professional security reviews of the library done, but unfortunately nothing I can share details of (it was done by an organization evaluation the library, it is up to them if they want to publish the result they paid for).

**Comment by drowhunter** [comment]
Hi , im i the same boat as the OP,  but my question is will the v3/develop branch also support net.core 2.2 or will it only support v3?
as we will eventually upgrade to v3 but have no plans to as of yet?

**Comment by AndersAbel** [comment]
@drowhunter I think that v3 will require .NET Core 3 or higher. But there is no decision yet, it depends on if we need features that are only available on .NET Core 3. If we can implement all the features and stay on .Net Core 2.1 we will do that.
