### ISSUE TITLE
ToHttpRequestData extension method shows as ambiguous to itself.

### ISSUE THREAD

**Issue by cccsdh** [Sustainsys/Saml2#1215]
I believe you have a a problem with the ToHttpRequestData extension method as defined.

You should remove:
        public static HttpRequestData ToHttpRequestData(this HttpRequestBase requestBase)
        {
            return requestBase.ToHttpRequestData(false);
        }

and change the signature of:
        public static HttpRequestData ToHttpRequestData(
            this HttpRequestBase requestBase,
            bool ignoreCookies)

To 

        public static HttpRequestData ToHttpRequestData(
            this HttpRequestBase requestBase,
            bool ignoreCookies=false)

Otherwise you will get an ambiguous error:
![Capture2](https://user-images.githubusercontent.com/7432539/85030934-0f448100-b14c-11ea-94a8-2b091b04ed4b.PNG)

**Comment by leotohill** [comment]
@cccsdh , I have the same issue, but how is it that this reference resolves without issue in the code of SustainSys itself?   See 
HttpModule.RequestBaseExtensionsTests.cs line 48 

`var actual = request.HttpRequestData();
`
which compiles fine in this project.  I'm still trying to figure this out... some project property?

**Comment by leotohill** [comment]
I got to the bottom of this, and I don't think it's a bug.  And since it's a support issue, I've posted a Q and A in stackoverflow: 

https://stackoverflow.com/questions/62603855/compile-error-call-is-ambiguous-using-sustainsys-saml2-extension-method-tohttp/62603856#62603856

**Comment by explunit** [comment]
Thanks for documenting your solution to this.
