### ISSUE TITLE
Decouple IOptions from Service Provider

### ISSUE THREAD

**Issue by xr280xr** [Sustainsys/Saml2#1218]
I am just learning SAML 2.0 and this project so I apologize if I am not yet understanding correctly. I am looking at using it to implement a simple Idp and notice that the `Saml2RedirectBinding.Unbind` method is capable of handling either a `"SAMLRequest"` QS argument or a `"SAMLResponse"`. My understanding, which may be incorrect, is a `"SAMLRequest"` would only received by the Idp? But this method, of the abstract `Saml2Binding` class, accepts an `IOptions` which is Service-Provider-specific. What I've seen so far is this seems to mean the binding is not capable of handling (determining the `TrustLevel` of) a signed Authn request or logging? I see the StubIdp just passes a null value for the options parameter, but since requests may be signed, and it would be nice to have logging, maybe decoupling these would be an appropriate enhancement to better support Idp implementations?

**Comment by AndersAbel** [comment]
The support for incoming SamlRequests in the library is a hack that was created to support the StubIdp. This kind of cleanup sounds like a good candidate for v3, now when there is a possibility to make breaking changes.

**Comment by AndersAbel** [comment]
Closing as separate issue, will not make the same design in v3.
