### ISSUE TITLE
Exposing certificate digestvalue and signatureValue in metadata xml

### ISSUE THREAD

**Issue by KayodeBakker** [Sustainsys/Saml2#1230]
I'm using the Sustainsys.Saml2.Owin version 2.3.0 at the moment and I've noticed that I'm unable to stop exposing our certificate the digestvalue and signaturevalue in our metadata file. The IP to which we connect doesn't require us to expose this as it only needs the SPSSODescriptor.KeyDescriptor so why can't we stop exposing this? Is there any way of removing this because it really isn't something we'd like to show on an endpoint that everyone using our application can access if they know the ModulePath.

Example:
```xml
<EntityDescriptor cacheDuration="PT1H" entityID="https://localhost/Saml2" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns="urn:oasis:names:tc:SAML:2.0:metadata" ID="_id">
	<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
			<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
			<Reference URI="#_id">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
				<DigestValue>digestvalue</DigestValue>
			</Reference>
		</SignedInfo>
		<SignatureValue>signaturevalue</SignatureValue>
		<KeyInfo>
			<X509Data>
				<X509Certificate>certificate</X509Certificate>
			</X509Data>
		</KeyInfo>
	</Signature>
	<SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
		<KeyDescriptor>
			<KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
				<X509Data>
					<X509Certificate>certificate</X509Certificate>
				</X509Data>
			</KeyInfo>
		</KeyDescriptor>
		<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://localhost/Saml2/Logout" />
		<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost/Saml2/Logout" />
		<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost/Saml2/Acs" isDefault="true" index="0" />
		<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://localhost/Saml2/Acs" isDefault="false" index="1" />
	</SPSSODescriptor>
</EntityDescriptor>
`

Please let us know if you have any suggestions as we think that this can be hurtful for security.

**Comment by explunit** [comment]
You might be able to suppress this by hooking into the `MetadataCreated` or `MetadataCommandResultCreated` notifications. But for myself I would question whether the effort is worth it. The certificate published here is only the public key and is expected to be public.

**Comment by KayodeBakker** [comment]
> You might be able to suppress this by hooking into the `MetadataCreated` or `MetadataCommandResultCreated` notifications. But for myself I would question whether the effort is worth it. The certificate published here is only the public key and is expected to be public.

Well the MetadataCommandResultCreated helped with removing it like you said. Reason why I'm asking is because as far as I've always known and have been taught by more experienced programmers is that you do not want the digestvalue and signaturevalue to be available even if it were only to be a small risk not worth mentioning.

It's a small effort te remove it via the MetadataCommandResultCreated though I wonder why it is even shown in the first place.
Thanks for the reaction and for now this is enough for me :).
