### ISSUE TITLE
Saml2.HttpModule v1.0.2 is compiled in .NET v4.7.2 not v4.5.2

### ISSUE THREAD

**Issue by ymlai87416** [Sustainsys/Saml2#1232]
I use this library for work, which upgrading to IIS server to .NET v4.7.2 is difficult. 

I find that the only feature requires v4.7.2 is the use of HttpCookie.SameSite. I don't know why can't we just append this information as text instead of relying on this variable and upgrade the whole library from v4.5.2 to v4.7.2...

I think v1.0.x branch is to allow .NET v4.5 app to use your library, so please don't easily give up this for a fancy feature.

**Comment by AndersAbel** [comment]
The cookie handling in IIS/System.Web is horribly complex. To do that through text would be a nightmare.

I'm sorry, but the only viable option for you is to update your target framework of your app.

The v1.0.x branch is for the full .NET Framework, using the System.IdentityModel SAML2 processing libraries that are included in the framework.
