### ISSUE TITLE
Adding an HTTP_REFERER header on the Authn request

### ISSUE THREAD

**Issue by my-kel** [Sustainsys/Saml2#1235]
Hi,

On the project I'm working, we need to add an **HTTP_REFERER** header to the **Authn request**, to allow the IdP identifying the application doing the request. Multiple SP can do Authn request to the same IdP and such it's a crucial technical requirement.

After reading the source code, I wasn't capable to figure out how to add an HTTP_REFERER header to the Authn request. Is it possible?

Thanks for any help.

**Comment by AndersAbel** [comment]
Override `AuthnRequestCreated` and make your own implementation of `CommandResult.Apply` that sets the additional header.
