### ISSUE TITLE
Large number of user claims prevents user to login

### ISSUE THREAD

**Issue by michalzubkowicz** [Sustainsys/Saml2#1243]
Used software:
Nuget Package: Sustainsys.Saml2
.Net Core 2.2

Problem:
User claims are serialized in session cookie by DataProtector, but when there is a large number of claims (for example user with 30 diffrent roles), generated cookie is too large to pass as request and web server rejects it with http error "413 Request Entity Too Large". 

Workaround:
In our case we provided own implementation of Data Protector which stores user claims data server side instead of in cookie.

**Comment by AndersAbel** [comment]
This is not a bug in this library - it is a known limitation of the cookie authentication handler. The built in way to solve this is to set a `SesssionStore` in the `CookieAuthenticationOptions`.
