### ISSUE TITLE
Respect SP Options WantAssertionsSigned

### ISSUE THREAD

**Issue by cscharf** [Sustainsys/Saml2#1244]
Having gone through a few SAML implementations now where the IdP will not or cannot implement signing, however when our SP receives an assertion that is not signed and no signature or key exists in the response, we're getting the following exception coming from `Saml2Response.ValidateSignature()`:

> The SAML Response is not signed and contains unsigned Assertions. Response cannot be trusted.

It's apparent this is expected behavior as the exception and validation around signatures are hard-coded (generally industry best practice). It would be nice, however, if the `SPOptions.WantAssertionsSigned` was consulted in this case to determine if this scenario _should_ be allowed anyway. We currently provide a unique SP to every IdP configured so cross-over security concerns would be minimal but ultimately up to each partner/integrator (IdP). It would seem a smart default for that property of `true` would also be the way to go. It appears today that `SPOptions.WantAssertionsSigned` is only ever used for generating/parsing metadata and not for anything else... So if it's `false` and we generate metadata for the IdP, and they don't sign the assertion and get this exception, that would also be a perplexing/surprising result for the IdP admin.

**Comment by AndersAbel** [comment]
No. The basis for the entire trust of Saml2 is that there is a signature, either on the entire response or on the contained assertion. If there is no signature, there is no trust.

**Comment by cscharf** [comment]
Thanks for the follow up Anders. While I don't disagree with your statement/sentiments, reality has proven quite the opposite in real-world application of SAML2; will work around it for the time being. Thanks for the consideration.

**Comment by AndersAbel** [comment]
Ok, this is an important issue from a security perspective, so I'll give it some more thoughts. The basis for security in Saml2 is that the SP can know for sure that the assertion was issued by the Idp. That can be achieved in three ways:
1. The Assertion XML node is signed by an Xml signature - supported.
2. The Response XML node (which is the parent of the Assertion node) is signed by an Xml signature - supported.
3. The Response was retreived using the Artifact binding and the artifact resolve is signed (TLS certificate, signed SOAP message or simply trust in HTTP GET) - not supported by the library (yet).

If it is 3 that you are looking after that can be achieved, but not by a setting to ignore missing signatures.

**Comment by cscharf** [comment]
Thanks, it was definitely not 3 mentioned there, although that would be good to have; there are literally some IdPs that don't support 1 or 2 and we have to rely on the nonce in the Response and clock for trust verification; that the assertion was expected (time) and contains the material expected (nonce) in those scenarios the IdP can't support a signed assertion. I'll have to dig through my conversation/email histories to figure out which IdP this was (the last example I have) and get back to you.

**Comment by AndersAbel** [comment]
What you describe is inherently unsafe. With the POST binding (which is the one you use if you're not using Artifact), the Idp is not really "sending" the response to the SP. The users web browser is getting the response from the Idp and then POSTing it to the SP. A user with knowledge can alter what is POSTed. That's what the signature protects for. The RelayState/InResponseTo are also security mechanisms, but they do not protect against the user altering the message contents.

**Comment by cscharf** [comment]
> What you describe is inherently unsafe.

Yes, absolutely 😉 . It's not a hill I'm willing to die on either to have an underlying framework in this case support it as it's a good security posture if anything based on what you've described above, among many other risks.

Reviewing the [docs from OASIS](https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#4.6.Security%20in%20SAML|outline) on the subject, they clearly state:

> When a response message containing an assertion is delivered to a relying party via a user's web browser (for example using the HTTP POST binding), then to ensure message integrity, it is mandated that the response message be digitally signed using XML Signature

I appreciate the follow up on this Anders. We've found a way to support these other customers with distinct or unique needs around signatures and thankfully at least for Bitwarden, Authentication (SSO) is a very different mechanism from Decryption, which still requires a master password/decryption key that is not provided through SSO itself.

**Comment by cscharf** [comment]
Although from [this document](https://docs.oasis-open.org/security/saml/v2.0/saml-sec-consider-2.0-os.pdf) (page 19, under Countermeasures; line 654) states signatures, among other security measures are not required. So 🤷🏻 .

> Countermeasures: In order to address these potential threats, a system that guarantees in-transit
message integrity must be used. **The SAML protocol and the SOAP binding neither require nor forbid the
deployment of systems that guarantee in-transit message integrity**, but due to this large threat, it is highly
recommended that such a system be used. At the SOAP binding level, this can be accomplished by
digitally signing requests and responses with a system such as XML Signature [XMLSig]. The SAML
specification allows for such signatures; see the SAML assertion and protocol specification [SAMLCore]
for further information.

**Comment by AndersAbel** [comment]
In the context of the Web SSO SAML profile (which is what this library is built for), the only place where the SOAP binding is used is for resolving artifacts. So that is actually the same as I stated as 3. above.
