### ISSUE TITLE
.NET 5: EnvironmentHelpers.IsNetCore bad implementation

### ISSUE THREAD

**Issue by Softwaretom007** [Sustainsys/Saml2#1252]
Hi,
implementation of flag `EnvironmentHelpers.IsNetCore` in `Saml2.Internal` and `Saml2.Metadata` isn't good.
If main application is in .net 5, detection fails and library crashes. 

After forking project and fixing bug, library starts to working properly.

**Comment by AndersAbel** [comment]
Thanks for noticing. .NET 5 is coming and should definitely work. Would you mind sending a pull request with the new detection logic?

Are there any other issues or incompatibilities you've seen so far?

**Comment by dlemstra** [comment]
Is there a reason this is a runtime check instead of a compile time check @AndersAbel? I could open a PR to change this into a compile time check.

**Comment by creste** [comment]
Hi @AndersAbel, I also ran into this issue.  I created a pull request with a fix: https://github.com/Sustainsys/Saml2/pull/1254.

I haven't seen any other issues or incompatibilities so far but will let you know if I do.

**Comment by AndersAbel** [comment]
@dlemstra For the .NET Standard target it is not known at compile time if the runtime is .Net Core or .Net Framework. That's the historical reason. But the .NET Standard target might be something to discuss if it's worth keeping - we're already multi-targeting because how .NET Framework does not implement .Net Standard very nicely in some versions.

**Comment by MatiSanchez** [comment]
Hi guys! 

Any news about this changes? Any estimated day about next release?

**Comment by AndersAbel** [comment]
My intention is to get a 2.8.0 out next week containing this fix and a few others urgent updates.

**Comment by dlemstra** [comment]
I dont know if you noticed @AndersAbel but I opened a PR to fix this issue.

**Comment by AndersAbel** [comment]
@dlemstra Yes I did, it's that PR that I intend to use.

**Comment by DavidBasarab** [comment]
I moved my code to .net this weekend and ran into this same issue.  Do you know when this PR will be released?

**Comment by AndersAbel** [comment]
@DavidBasarab ASAP - got piled up with too much work, but working on it.

**Comment by gsitv** [comment]
Any news about this PR?

**Comment by AndersAbel** [comment]
Fixed in db3d5ec9184f5 for v2 branch. develop is left open, will review the larger PR for that.

**Comment by samisq** [comment]
@AndersAbel Thank you so much for the fix! Any idea when the new nuget packages will be available?

**Comment by AndersAbel** [comment]
@samisq I'm working on the final PR that needs to get into 2.8.0 - it's the AES GCM support in #1251, then I'll make a release.

**Comment by MatiSanchez** [comment]
Hi @AndersAbel .. I confirm that is working good with the new version.

Thanks and happy holidays!

**Comment by wggley** [comment]
Any status about 2.8.0?

I can't find the source.
