### ISSUE TITLE
Silent Authentication - Question

### ISSUE THREAD

**Issue by vinujosey** [Sustainsys/Saml2#1253]
Hi,

I am building an Intranet application which needs to authenticate using ADFS
after identifying them through their Windows login username. Below are the series of events that need to happen:

1. User logs onto their Windows desktop within the company.

2. The user pulls up a web browser and enters the Intranet app URL e.g. http://companyintranet

3. As soon as the user request the application, the authentication module fetches the windows login information and needs to do a authentication from ADFS without redirecting to ADFS login page.

Can we do this using Sustainsys Saml2 middleware ? 
I have successfully implemented the redirect login using Sustainsys.

Thanks.

**Comment by AndersAbel** [comment]
Yes.
