### ISSUE TITLE
Notifications.GetIdentityProvider default callback is called and errors with KeyNotFoundException when dynamically loading all IdentityProviders

### ISSUE THREAD

**Issue by demyte** [Sustainsys/Saml2#1258]
Hi there,

We are dynamically loading in Identity Providers on the fly using the Notification callbacks `SetIdentityProvider` and `GetIdentityProvider` so that the right provider is used just in time for the user based on their orgs SSO configuration stored in our database.

With the `GetIdentityProvider` Notification, I am running into an issue where the default callback is being called first and it is looking for an Identity Provider using the current EntityId but we have none registered so it throws a `KeyNotFoundException` and then never passes on to call the callback we register that will provide the correct Identity Provider, just in time.

I have worked around this by changing the `IdentityProviderDictionary` to return `null` if there is a `KeyNotFoundException` in a local version so that we can move past this, but as I do not know enough about the library and the ramifications of this beyond our use case, so, I am reluctant to submit a PR for just that change.

I am happy to put together a PR with a bit of guidance about how you want to solve this issue in general in the library.

**Information as requested:**
I am using v2.70 netstandard20 in a netcore2.2 app of:
- Sustainsys.Saml2.AspNetCore2
- Sustainsys.Saml2

**Stack trace:**
```
KeyNotFoundException: The given key 'Sustainsys.Saml2.Metadata.EntityId' was not present in the dictionary.
System.Collections.Generic.Dictionary<TKey, TValue>.get_Item(TKey key)
Sustainsys.Saml2.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId) in IdentityProviderDictionary.cs
+
                        return dictionary[entityId];

Show raw exception details
KeyNotFoundException: No Idp with entity id "***REDACTED***" found.
Sustainsys.Saml2.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId) in IdentityProviderDictionary.cs
+
                        throw new KeyNotFoundException(
Sustainsys.Saml2.Configuration.Saml2Notifications+<>c.<.ctor>b__84_18(EntityId ei, IDictionary<string, string> rd, IOptions opt) in Saml2Notifications.cs
+
            = (ei, rd, opt) => opt.IdentityProviders[ei];
Sustainsys.Saml2.WebSso.AcsCommand.GetIdpContext(XmlElement xml, HttpRequestData request, IOptions options) in AcsCommand.cs
+
            var identityProvider = options.Notifications.GetIdentityProvider(entityId, request.StoredRequestState?.RelayData, options);
Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) in AcsCommand.cs
+
                    var idpContext = GetIdpContext(unbindResult.Data, request, options);
Sustainsys.Saml2.AspNetCore2.Saml2Handler.HandleRequestAsync() in Saml2Handler.cs
+
                var commandResult = CommandFactory.GetCommand(commandName).Run(
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### Information needed
1. What nuget packages are you using
2. What is the expected behaviour
3. What happens instead. In the case of an exception, this includes the exception typ, complete exception message (personal information may be redacted) and a stack trace.

### Additional info
Please include
* .Net Framework your application is compiled against (e.g. `net472`, `netcoreap2.1`)
* .Net Framework installed. This might be different than above. You can compile with net452, but have 4.7.2 installed.
* Version of Asp.Net MVC / Asp.NET Core used.

**Comment by PaulBol** [comment]
Same problem here. My workaround was to keep a reference to `Saml2Options` and then in `SelectIdentityProvider` set 

`_saml2Options.IdentityProviders[identityProvider.EntityId] = null;`

Doesn't look nice but seems to work.

**Comment by AndersAbel** [comment]
The behaviour for multiple Identity Providers will be completely redesigned, closing this as not relevant.
