### ISSUE TITLE
SSL certificate is expired on stubidp.sustainsys.com

### ISSUE THREAD

**Issue by samjetski** [Sustainsys/Saml2#1259]
The SSL certificate on https://stubidp.sustainsys.com has expired on 21 Nov 2020. Looks like this is a wildcard certificate so it's also affecting https://www.sustainsys.com.

@AndersAbel could this please be renewed? Alternatively, would you consider hosting this behind Cloudflare as is already done for the [Saml2 docs](https://saml2.sustainsys.com/) site?

**Comment by AndersAbel** [comment]
Thanks for commenting. It's just me that forgot to purchase a new cert in time. It's now done and updated.
