### ISSUE TITLE
Null reference exception on missing discoveryServiceResponseUrl

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#126]
Using the owin middleware version 0.7.0 without specifying a discoveryServiceResponseUrl causes the owin middleware to crash with any request with a null reference exception. It doesn't matter if a discovery service is used or not or whether any kind of authentication sequence is initiated. It crashes any request.

**Comment by mrchief** [comment]
The same issue exists in Kentor.AuthServices.Mvc version 0.12.0.
