### ISSUE TITLE
Sustainsys.Saml2.Owin.csproj not included in repository.

### ISSUE THREAD

**Issue by samunro** [Sustainsys/Saml2#1260]
I am having problems working out how to control the path to the attribute consuming service (ACS) and was hoping to find some clues in the source code. I was not able to find the source code for the Sustainsys.Saml2.Owin.csproj project in this repository, though. From what I can work out, that is the project upon which the following NuGet package is based.

https://www.nuget.org/packages/Sustainsys.Saml2.Owin/

Saml2AuthenticationOptions is an example of a class that I am interested in. I could not find it in the Sustainsys.Saml2 solution.

Should this project be included in this repository? Is it available elsewhere?

**Comment by explunit** [comment]
To see the OWIN project source you'll need to the v2 branch since it's been removed from develop: https://github.com/Sustainsys/Saml2/tree/v2

**Comment by samunro** [comment]
Perfect. Thanks for the feedback.

**Comment by explunit** [comment]
Correction: Anders mentioned in https://github.com/Sustainsys/Saml2/pull/1256#issuecomment-734306365 that OWIN may be coming back to v3. But as it stands today, my comment is correct about where to find the code.
