### ISSUE TITLE
Question - reach 404 when trying to get project meta

### ISSUE THREAD

**Issue by bczm8703** [Sustainsys/Saml2#1262]
I am trying to retrieve the metadata to import to my ADFS by going to https://localhost:44342/saml2 but I keep receiving 404. 

not sure if it is related but how do I get the pfx from my ADFS? 

I try to export the token signing cert from adfs but it seems to only also cer format and the service communication cert from the ADFS does not seem to allow me to export with the key

**Comment by wylermat** [comment]
Hi, 
the handler is case-sensitive. Try  https://localhost:44342/Saml2 
The tokoens are not signed with the adfs-certificate. you should create your own and register your application with that in adfs.

**Comment by Nanferten** [comment]
Hello folks,

I'm experiencing a similiar issue. As OP, my ACS and Metadata are not mapped. (e.g. localhost:5001/Saml2, localhost:5001/Saml2/acs)

I've tried multiple things:

- Looked up documentation (https://readthedocs.org/projects/saml2/downloads/pdf/latest/)
- Different methods of mapping controller (https://stackoverflow.com/questions/57684093/using-usemvc-to-configure-mvc-is-not-supported-while-using-endpoint-routing)
- Usage of Sustainsys.SAML2.MVC
- Change ModulePath
- Validate SAML Responses
- Custom SAML Reponse controller
- Tested everything in configured case

My interpretation:

I'm pretty certain, that only the mapping is not working. The generated SAML Request is working and the response from my designated IdP is also looking like expected. As the application is not serving the metadata I'm convinced there is either an issue with the mapping of the controller or on the site of configuration.

**I'm hopping anyone can provide some knowledge for further debugging or a solutions. Following are some technical informations.**

<hr/> 

Technical details

Application:

- .NET Core 3.1
- Sustainsys.Saml2.AspNetCore2 2.7.0
- Kestrel / IIS hosted

Mapping:

``` csharp
services.AddControllersWithViews(options =>
			{
				options.Filters.Add(new AuthorizeFilter());
			})
```

``` csharp
app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllers();

				endpoints.MapHealthChecksUI();
			});
```

Saml Integration:

``` csharp
 .AddSaml2(options =>
				{
					options.SPOptions.EntityId = new EntityId("EntityId");

					options.IdentityProviders.Add(
						new IdentityProvider(new EntityId(authSettings.SamlSettings.IdPEntityId), options.SPOptions)
						{
							MetadataLocation = "res\\metadata.xml"
						});
				});
```

**Comment by bczm8703** [comment]
> Hi,
> the handler is case-sensitive. Try https://localhost:44342/Saml2
> The tokoens are not signed with the adfs-certificate. you should create your own and register your application with that in adfs.

hi thanks for the help I am able to load the saml XML now. just checking how do I create the pfx cert. 

i am receiving the exception: CryptographicException: Invalid provider type specified.


is it possible to use my ADFS token signing cert and make it into pfx?

**Comment by wylermat** [comment]
Are you using .net5?

**Comment by bczm8703** [comment]
> Are you using .net5?

i run the sample provided here. the only changes done is the adfs URL and tired to change to pfx file

**Comment by AndersAbel** [comment]
Closing this as the original issue was case sensitivity.
