### ISSUE TITLE
Mapping of default controller missing ("/Saml2*")

### ISSUE THREAD

**Issue by Nanferten** [Sustainsys/Saml2#1263]
Posting this from : https://github.com/Sustainsys/Saml2/issues/1262#issuecomment-744373790 , due to different issue.

Hello folks,

my ACS and Metadata are not mapped. (e.g. localhost:5001/Saml2, localhost:5001/Saml2/acs)

I've tried multiple things:

- Looked up documentation (https://readthedocs.org/projects/saml2/downloads/pdf/latest/)
- Different methods of mapping controller (https://stackoverflow.com/questions/57684093/using-usemvc-to-configure-mvc-is-not-supported-while-using-endpoint-routing)
- Usage of Sustainsys.SAML2.MVC
- Change ModulePath
- Validate SAML Responses
- Custom SAML Reponse controller
- Tested everything in configured case

My interpretation:

I'm pretty certain, that only the mapping is not working. The generated SAML Request is working and the response from my designated IdP is also looking like expected. As the application is not serving the metadata I'm convinced there is either an issue with the mapping of the controller or on the site of configuration.

**I'm hopping anyone can provide some knowledge for further debugging or a solutions. Following are some technical informations.**

<hr/> 

Technical details

Application:

- .NET Core 3.1
- Sustainsys.Saml2.AspNetCore2 2.7.0
- Kestrel / IIS hosted

Mapping:

``` csharp
services.AddControllersWithViews(options =>
			{
				options.Filters.Add(new AuthorizeFilter());
			})
```

``` csharp
app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllers();

				endpoints.MapHealthChecksUI();
			});
```

Saml Integration:

``` csharp
 .AddSaml2(options =>
				{
					options.SPOptions.EntityId = new EntityId("EntityId");

					options.IdentityProviders.Add(
						new IdentityProvider(new EntityId(authSettings.SamlSettings.IdPEntityId), options.SPOptions)
						{
							MetadataLocation = "res\\metadata.xml"
						});
				});
```

**Comment by MatiSanchez** [comment]
I don't know if I'm wrong, but it seems to me that LoadMetadata is missing:

```
 .AddSaml2(options =>
				{
					options.SPOptions.EntityId = new EntityId("EntityId");

					options.IdentityProviders.Add(
						new IdentityProvider(new EntityId(authSettings.SamlSettings.IdPEntityId), options.SPOptions)
						{
							MetadataLocation = "res\\metadata.xml",
                                                        LoadMetadata = true
						});
				});
```

**Comment by Nanferten** [comment]
Thanks @MatiSanchez  for your reply:

I've "anonymized" the SPEntityId. It's set to a 'valid' entity ID for my IdP. Sorry, should have made that clear.

'LoadMetadata' is automatically set, if MetadataLocation is defined. https://github.com/Sustainsys/Saml2/blob/a54415126a093b6fdebc1a38e01ca34110906efb/Sustainsys.Saml2/IdentityProvider.cs

```csharp
// Summary:
//     Location of metadata for the Identity Provider. Automatically enables Sustainsys.Saml2.IdentityProvider.LoadMetadata.
//     The location can be a URL, an absolute path to a local file or an app relative
//     path (e.g. ~/App_Data/IdpMetadata.xml). By default the entity id is interpreted
//     as the metadata location (which is a convention).
public string MetadataLocation { get; set; }
```

Either way, tried it anyways and didn't change a thing.

Thanks for your help, but this could not solve my issue.

**Comment by AndersAbel** [comment]
Do you have `app.UseAuthentication()`?

**Comment by Nanferten** [comment]
Thanks @AndersAbel  for your reply, yes I had this activated.

During my evening tests it seems the "Saml2" Endpoint is mapped, but I can't identify exactly which change fixed it.
To help other I will list following all changes I've made that could have led to solving this issue:

- Change order of Startup.cs (FROM `Configure(...)` - [Autofac] `ConfigureContainer(...)`  - `ConfigureServices(...)` | TO  `ConfigureServices(...)`  - [Autofac] `ConfigureContainer(...)`  - `Configure(...)` 
- _Minor CORS changes (very unlikely to affect SAML2)_
- _NuGet complete reset on local device_

Might check in early 2021 to determine what it actually caused, but can't promise.

Thanks for your help and happy holidays!
