### ISSUE TITLE
connect Azure AD use .net core 3.1  login error, there was an error with my configuration?

### ISSUE THREAD

**Issue by EasonRen** [Sustainsys/Saml2#1264]
![image](https://user-images.githubusercontent.com/8588276/103076906-baf1f080-4609-11eb-95c6-42c181b3bd24.png)

login error

![image](https://user-images.githubusercontent.com/8588276/103076996-e674db00-4609-11eb-991b-34609510f596.png)

**Comment by AlexAlexGoTO** [comment]
Have the same issue, can't understand what Reply URL I should specify in Azure I'm using https://my-site/saml2/Acs but looks like it's not correct one...
