### ISSUE TITLE
user.identity.name is blank in return url.

### ISSUE THREAD

**Issue by thisisata** [Sustainsys/Saml2#1265]
In My MVC App, after a successful response from Idp, I am printing the value of user.Identity.Name that should give me the autheticated user details [ assertion.Subject.Value]. But its a blank value,

**Comment by pagetangalin** [comment]
have you found a solution to your issue? im facing this issue in the iis server i deployed to but when I run it locally it works

**Comment by AlexAlexGoTO** [comment]
How actually I can get that assertion ?

**Comment by AndersAbel** [comment]
Too little information.
