### ISSUE TITLE
SPSSODescriptors aren't ignored on metadata parsing

### ISSUE THREAD

**Issue by BenediktHeinrichs** [Sustainsys/Saml2#1270]
In the issue https://github.com/Sustainsys/Saml2/issues/408 the functionality of creating SPSSODescriptors was excluded since metadata from federations sometimes include SPs which have duplicate index numbers on their AssertionConsumerServices.

This however was "removed" in https://github.com/Sustainsys/Saml2/commit/535c5703bc8385a1dabdb7742411493bd2be352c#diff-73db87bfa67a498d11677ba605dea2195bc0d42eed151ae28de5498255e69d69R59 and since then this does not work anymore this way.

Since we stumbled upon this issue while including the DFN-AAI federation, this issue proposes to reenable the previous functionality and to adapt a previous test which should deal with checking this.

**Comment by BenediktHeinrichs** [comment]
Added two merge request, so that this can be merged into [develop (v3)](https://github.com/Sustainsys/Saml2/pull/1271) for future usage and [v2](https://github.com/Sustainsys/Saml2/pull/1272) for direct adoption.

**Comment by AndersAbel** [comment]
The new metadata reader that's now in `develop` contains functionality to ignore/supress errors, so this won't be needed.
