### ISSUE TITLE
SP initiated SSO with multiple schemes and multiple IDps

### ISSUE THREAD

**Issue by EugenGu** [Sustainsys/Saml2#1274]
Hello I have a IdentityServer4 that is working as a Service provider, I am currently using Saml2.AspnetCore2 version 2.8. I am trying to register multiple Saml2 schemes in startup to be able to use multiple IDps. When I try to challenge with the second registered scheme the response from Idp is then redirected to Saml2Handler to HandleRequestAsync which is correct, but the instance of that Saml2Handler is for the first registered scheme.
I have attached a screenshot with configuration from startup.
![samlConfig](https://user-images.githubusercontent.com/68546086/108184671-20e38b80-7114-11eb-8dc0-9be7b6711b40.JPG)

**Comment by AlexOliinyk1** [comment]
@EugenGu  Hello, how I can contact you? It same issue for me...
