### ISSUE TITLE
Received message XXX contains unexpected InResponseTo XXX. No cookie preserving state from the request...

### ISSUE THREAD

**Issue by Gillardo** [Sustainsys/Saml2#1278]
### Information needed

1. What nuget packages are you using
`<PackageReference Include="Sustainsys.Saml2.AspNetCore2" Version="2.7.0" />`

2. What is the expected behaviour
Not to get the error message and to login normal.

3. What happens instead. In the case of an exception, this includes the exception type, complete exception message (personal information may be redacted) and a stack trace.

I am getting this error message.
![image](https://user-images.githubusercontent.com/7406381/110812014-277ea200-827f-11eb-956b-f7bf026e2509.png)

I have set this up on live and its working fine.  But this seems to happen when i am running it locally on my machine using localhost:5000 (`dotnet run`)

No idea what it is

## Additional info
Please include
using `net5`

**Comment by Gillardo** [comment]
Any news on this please?

**Comment by explunit** [comment]
Have you traced the cookie set during the initiation of the login flow and verified that it is being successfully sent back to your server in the Acs request? Cookie handling has become more difficult lately with Chrome and their SameSite restrictions, e.g. for non-SSL such as localhost.

**Comment by Gillardo** [comment]
Can see here that the calls seem fine.  The one in red is the one that is reporting the error and that is to the saml2/acs route

![image](https://user-images.githubusercontent.com/7406381/110978732-a6e1a380-835b-11eb-92b8-5d44f71affd3.png)

The details of the one in red looks fine ? ( i have blanks out the idP as its our customers url)

![image](https://user-images.githubusercontent.com/7406381/110978881-d09aca80-835b-11eb-9af3-ff1f81550f89.png)

**Comment by explunit** [comment]
Have you checked the cookies related to those requests? I find that the Chrome dev tools options for showing blocked cookies can sometimes be helpful:

![image](https://user-images.githubusercontent.com/2872623/111053798-e16b3f00-8434-11eb-93c1-803de9d1390f.png)

There is a Saml2.xxxxx cookie written when the sign-on sequence starts, and you should see it in ACS request. If you don't, then that's the cause of the error.

**Comment by Gillardo** [comment]
On the original signOn request, i can see the cookie
![image](https://user-images.githubusercontent.com/7406381/111145416-218b0880-8580-11eb-93f6-220b44139e87.png)

![image](https://user-images.githubusercontent.com/7406381/111145525-3f586d80-8580-11eb-87d7-62143762349c.png)

But i cannot see this anywhere else in a response or request when Acs is called....

Acs request
![image](https://user-images.githubusercontent.com/7406381/111145662-6747d100-8580-11eb-81ff-775959ef94d7.png)

How can i fix this?

**Comment by explunit** [comment]
You can see the cookie alert in the first screenshot showing that SameSite on non-SSL is going to be blocked later.

The easiest solution is probably to run SSL even on localhost so that it's a better simulation of what you're running in production.

**Comment by Gillardo** [comment]
Is this the correct way to pass something to the callback though?

**Comment by Gillardo** [comment]
Right, i have done that and set to use https, that is all fine.  But how come my AuthenticationProperties of clientId is not passed back?

**Comment by Gillardo** [comment]
Never mind, i added it to `Items` and works
