### ISSUE TITLE
Validate Saml Xml With Certificate And Certificate Chain

### ISSUE THREAD

**Issue by imranbaloch** [Sustainsys/Saml2#1286]
I have the below XML,

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <Response xmlns="http://www.site.ae/g">
      <Message xml:id="message">
        <Header>
          <Service>Read</Service>
          <Action>SomeAction</Action>
        </Header>
        <Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="SomeDataType">
          <Status>Success</Status>
          <Data>
            <Id>123</Id>
          </Data>
        </Body>
      </Message>
      <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
          <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/>
          <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
          <Reference URI="#message">
            <Transforms>
              <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            </Transforms>
            <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
            <DigestValue>SomeValue</DigestValue>
          </Reference>
        </SignedInfo>
        <SignatureValue>
          SomeValue
        </SignatureValue>
        <KeyInfo>
          <X509Data>
            <X509Certificate>
              SomeValue
            </X509Certificate>
          </X509Data>
        </KeyInfo>
      </Signature>
    </Response>

Currently, I am using one C# library `SomeSignatureValidation(certificateData, certificateChain).Validate()` which is just Pinvoke wrapper of a native library. The problem with native library is that it keep crashing the IIS process.

https://stackoverflow.com/questions/67344508/validate-xml-with-certificate-data-and-certificate-chain-in-c-sharp

Can we use Saml2 library to validate the signature? If yes how can I?

The certificate and certificate chain is provided third party company to verify the xml.

**Comment by explunit** [comment]
You'll find some code related to xml signatures in this library, but the public API is designed around the SAML protocol, not xml signatures in general. Your stackoverflow question is probably the best place to find an answer.
