### ISSUE TITLE
PR proposal for removing read-only settings to allow programmatically updating web.config for MVC

### ISSUE THREAD

**Issue by heathem** [Sustainsys/Saml2#1288]
I'm opening this issue to discuss my proposal to create a PR that would basically add Add, Remove, Update methods to SustainsysSaml2Section and IdentityProviderElement and add a "set" to their properties.

I have an app that uses MVC and I want to be able to programmatically update the web.config sustainsys.saml2 section with adding an identity provider. The idea is that users can use my app to navigate to an "Identity Provider Settings" page, enter their IdP information in a form, press "Save", and the code will add a new IdP or modify an existing one, and the web.config will be updated accordingly.

Currently, I am able to modify other sections of my web.config programmatically from a form entry with .NET WebConfigurationManager, but am not able to do this with the sustainsys.saml2 section because all the properties are set to read-only.

Are there reasons why these properties are read only? If not, I propose that I will create a PR to submit that will make these properties modifiable. Thoughts? 

Thanks,
Heather

**Comment by explunit** [comment]
Hello @heathem, I can't speak for Anders, but my initial impression is that this is not a direction that the library will go. The library can be configured either via web.config or via using the c# objects directly. I believe the general guidance is that if you need dynamic functionality then you are configuring via c# and reading from your own custom data/configuration store. It would not be typical to write back to the web.config.

**Comment by heathem** [comment]
Thanks for the input @explunit. Any other thoughts @AndersAbel ?

**Comment by heathem** [comment]
I decided to just update the web.config sustainsys.saml2 section programmatically with .NET's XMLDocument.
