### ISSUE TITLE
Using Asp.Net WebForms - RelayState etc

### ISSUE THREAD

**Issue by marktur** [Sustainsys/Saml2#1291]
Hi there, very new to SAML2.  I have  Asp.Net WebForm app that has several customers.  One of them wants to do SSO via SAML, and for that customer, they would have a number of flavours to log in based on country. My questions are:
1.  How do I enable Sustainsys just for this customer
2.  Can I use relaystate to pass in via the url the country so that when we get the response we can see the url used to log in, so we can apply appropriate code?
Thank you.
(This is SP initiated approach)

**Comment by lochuynh** [comment]
Hi there, I also have the same  question for legacy WebForms app. How do I only enable SSO for once customer (the are having the same email domain) while still keep the Username, Password login for these others.
Thank you in advance!
