### ISSUE TITLE
Logout issue - Federated logout not possible.

### ISSUE THREAD

**Issue by adeshpande84** [Sustainsys/Saml2#1293]
When I hit the saml2/logout route, I am being logged out of the SP but not from IDP. Looks like no request goes out to the IDP. 
I looked at few similar questions here. I can see that the SessionIndex and LogoutNameIdentifier claims are there. But still I am getting the Federated logout not possible issue.

After logging in, inside the AcsCommandResultCreated, I am printing out the claims. This is the name/value pairs I see:

```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier PAPAJOHN
http://Sustainsys.se/Saml2/LogoutNameIdentifier ,,urn:ibm:names:ITFIM:5.1:accessmanager,,PAPAJOHN
http://Sustainsys.se/Saml2/SessionIndex uuid8e850fe-017a-158d-bee1-8231ff21e34d

```
In the firefox saml tracer, I see that the name identifier and session index are there. 

```
<saml:NameID Format="urn:ibm:names:ITFIM:5.1:accessmanager">PAPAJOHN</saml:NameID>

<saml:AuthnStatement AuthnInstant="2021-06-14T05:04:53Z"
                             SessionIndex="uuid8e850fe-017a-158d-bee1-8231ff21e34d"
                             SessionNotOnOrAfter="2021-06-14T06:04:53Z"
                             >
```

Below is the logs pertaining to the issue:

```
10988 23:10:23 DEBUG Sustainsys.Saml2.Owin.Saml2AuthenticationMiddleware - Initiating logout, checking requirements for federated logout
  Issuer of LogoutNameIdentifier claim (should be Idp entity id): 
  Issuer is a known Idp: False
  Session index claim (should have a value): 
  Idp has SingleLogoutServiceUrl: 
  There is a signingCertificate in SPOptions: False
  Idp configured to DisableOutboundLogoutRequests (should be false): 
10988 23:10:23 INFO  Sustainsys.Saml2.Owin.Saml2AuthenticationMiddleware - Federated logout not possible, redirecting to post-logout and clearing local session

```

The signing certificate, SingleLogoutUrl are all configured in the IDP metadata XML. I am setting the MetadataLocation in the IDP config. Also I have set DisableOutboundLogoutRequests to false, but in the sustainsys logs, it doesn't seem to recognize it.

Any help will be greatly appreciated.

Thank you.

My environment:
ASP.Net MVC 4.7.2
Sustainsys Saml2 2.8.0

**Comment by adeshpande84** [comment]
After some more changes to my source code, i was finally able to get a bit closer. Now I am getting this in the logs:

```
14652 00:41:15 DEBUG Sustainsys.Saml2.Owin.Saml2AuthenticationMiddleware - Initiating logout, checking requirements for federated logout
  Issuer of LogoutNameIdentifier claim (should be Idp entity id): https://idp.org/sps/idp/saml20
  Issuer is a known Idp: True
  Session index claim (should have a value): http://Sustainsys.se/Saml2/SessionIndex: uuid8e850fe-017a-158d-bee1-8231ff21e34d
  Idp has SingleLogoutServiceUrl: https://idp.org/sps/idp/saml20/slo
  There is a signingCertificate in SPOptions: False
  Idp configured to DisableOutboundLogoutRequests (should be false): False
```

**Comment by pagetangalin** [comment]
hi @adeshpande84  how does your claims look like in adfs? is your idp adfs? i don't have the SessionIndex on my saml:AuthnStatement. im also having issues with logout

**Comment by AndersAbel** [comment]
If you are running on ADFS you need to enable the NameId claim. If it is enabled, the SessionIndex will be generated too.
