### ISSUE TITLE
MVC application -  SAML response does not set Identity

### ISSUE THREAD

**Issue by shweinfeld** [Sustainsys/Saml2#1304]
I've been trying to connect Azure AD to a .NET Framework application. I have managed to replace the idP information into the sample MVC project successfully, however, when I attempt to do so in my actual application, the Identity is not set. I've verified that I do receive the SAML Response and that authorization was successful. I'd appreciate any insight. I've looked through pertinent issues and nothing I try fixes the problem.  I've attached a picture of the User.Identity values for reference.

![image](https://user-images.githubusercontent.com/53020099/130834674-8a7a3e44-62fd-4b74-939f-f021720e32a3.png)

I have also noticed some owin references in the application (I inherited the application, so I don't know it inside and out). Could it be that I should be using the Owin Middleware version? The application does not currently have a Startup.Auth.cs.

**Comment by AndersAbel** [comment]
You're going down the wrong path. Parsing and validating the SAML XML correctly is *hard*. That is why this library exists and why it took a few years to harden it and get it secure.

It looks like you need some help getting the different components wired up correctly. Drop me a mail at anders@sustainsys.com if you are interested in my commercial services.
