### ISSUE TITLE
Sustainsys.Saml2.Mvc v1.0.2 does not work with .NET Framework 4.5.1

### ISSUE THREAD

**Issue by kalluu-ck** [Sustainsys/Saml2#1309]
I'm using `Sustainsys.Saml2.Mvc`: https://www.nuget.org/packages/Sustainsys.Saml2.Mvc/1.0.2.
I see in the description that this library is supported to work with .NET Framework 4.5.
But when I was trying to install this package to my MVC application (.NET Framework 4.5.1), there's an error: `Could not install package 'Sustainsys.Saml2 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Is there anything that I was missing?

Thanks for your help,
Anh

**Comment by AndersAbel** [comment]
The description is a bit outdated (and can unfortunately not be changed once it's published to Nuget).

Version 1.0.2 requires .Net Framework 4.7.2 or later. That is the lowest version that supports SameSite attributes on cookies, which are now required to be set to work with modern browsers.
