### ISSUE TITLE
ForceAuthentication not setting ForceAuthn flag

### ISSUE THREAD

**Issue by shweinfeld** [Sustainsys/Saml2#1314]
I'm working on a .NET MVC application. I need to Force Authentication. I looked through the previous issues that dealt with this and tried adding the following code to Startup.cs and Global.asax.cs, both of which have no effect on the SAML Request. Any guidance would be appreciated.
```
Sustainsys.Saml2.Mvc.Saml2Controller.Options.Notifications.AuthenticationRequestCreated = (request, provider, dictionary) =>
            {
                request.ForceAuthentication = true;
            };
```

**Comment by AndersAbel** [comment]
Can you set a breakpoint to validate if the code in the notification is run?

**Comment by AndersAbel** [comment]
Won't fix any bugs in 1.x or 2.x, hopefully won't write buggy code in the next version.
