### ISSUE TITLE
Project status: Co-maintainers welcome

### ISSUE THREAD

**Issue by freshe** [Sustainsys/Saml2#1319]
Great library! Seems to work fine with .NET 5. 
.NET 6.0 is now released (which is LTS). Is the project still active?
If not, I think it would be helpful to communicate it so people can move on to something else.

**Comment by AndersAbel** [comment]
The project is alive, but I have not been able to put as much time needed into it lately. If more people would be interested in taking active part in maintaining/coding I am definitely open for help.

**Comment by milkshakeuk** [comment]
@AndersAbel are you still working on a release which fixes net6 support?

**Comment by AndersAbel** [comment]
Yes. I've merged the PR needed to `v2`. I'm now listening in on more comments before I do release a `2.9.0` on nuget.

**Comment by milkshakeuk** [comment]
@AndersAbel ah yes makes sense, should have thought about that for a second ☺️

**Comment by samisq** [comment]
@AndersAbel Is there any chance you can publish `2.9.0` or perhaps a pre-release version of it? I'd also be more than happy to help with that. This dependency is blocking our .NET 6 upgrade.

**Comment by AndersAbel** [comment]
@samisq Yes, help would be welcome. I've created a separate issue #1327 about the work for a release (why did I never think of publishing my todo-list in an issue to be able to receive help?)
