### ISSUE TITLE
Step by step implement in asp.net core application

### ISSUE THREAD

**Issue by Mateusz19021996** [Sustainsys/Saml2#1323]
Hi, 

is there possibility to just type few steps what and where to implement in our webApplication in .net? 

To use this nugett we need only to configure it in startup.cs?
We should add something else?
We just have to use [authorize] to use it in our endpoints?

Is there a difference between for example using octa or some another IDp?

**Comment by AlexAlexGoTO** [comment]
I didn't find any step by step examples in this repo. Can't really understand how to configure it. 
For example

            // It's enough to just create the federation and associate it
            // with the options. The federation will load the metadata and
            // update the options with any identity providers found.
            new Federation("https://localhost:44300/Federation", true, Saml2Options);
            
           I don't understand what does it mean ' just create the federation'. Trying to figure out for few days already.

**Comment by AlexAlexGoTO** [comment]
Yes, that would be nice... I'm struggling with Owin Middleware I found some sampl but I can't understand lot of lines like this one for example, what is Federation and how should I create it...

            // It's enough to just create the federation and associate it
            // with the options. The federation will load the metadata and
            // update the options with any identity providers found.
            new Federation("https://localhost:44300/Federation", true, Saml2Options);
