### ISSUE TITLE
IDP-initiated backchannel SLO :  How to hook handler on incoming SLO calls

### ISSUE THREAD

**Issue by IncoFB** [Sustainsys/Saml2#1325]
Hello,

I managed to set up an ASP.NET web application with sustainsys with SAML2 authentication.
I imported the sustainsys nuget package and configured everything in app's web.config file.
Everything works as expected, including front-channel SLO.

Now trying to find a way to perform backchannel SLO (either IDP or SP initiated)
As incoming "server-to-server" SLO calls are not relayed by any web browser, we are supposed to register SAML sessions somewhere (like in application cache) for maintaining a list of "invalid sessions". 
Also, in my application I would like to remove third-party cookies and session variables for a clean logout.
This means we have to write additional server-side code for this logic.
But having no idea where to hook that logic in the sustainsys SAML client, and I found no sample code for this.

Could you help, please ?

Thanks in advance

**Comment by AndersAbel** [comment]
The library does not support back-channel single logout. As you've figured out, that would require server-side session storage instead of just cookies. To implement it would be a major effort.
