### ISSUE TITLE
v2.9.0 release

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#1327]
What's needed for the release is:

1. Testing that confirms that the new version works on .NET 6, .Net Core and .NET Framework. Should be possible to validate by simply running the sample applications that target different versions.
2. Updates that are needed for a release - see https://github.com/Sustainsys/Saml2/commit/c04b0eaa18cebcff11abb3d2e87a4eb8cd5f1f24 for an example. A PR with corresponding updates for 2.9.0 would be helpful.

**Comment by samisq** [comment]
@AndersAbel I verified the fix on .NET 6 and .Net Core 3.1 using OKTA Idp. Still need to verify against .NET framework (I dont have it installed on my machine).
I also opened a [PR](https://github.com/Sustainsys/Saml2/pull/1328) with the updated version and release notes

**Comment by freshe** [comment]
Downloaded the 'develop'-repo and tested the sample project which targets .NET Framework 4.7 (had to download .NET Dev pack 4.6.1 + 4.7 to get it running in VS2022)

I can sign in to work via Saml2 (POST) as usual.

https://youtu.be/TZHet95t7V4

**Comment by AndersAbel** [comment]
Thanks a lot @freshe and @samisq.
