### ISSUE TITLE
Azure - The reply URL specified in the request does not match the reply URLs configured for the application

### ISSUE THREAD

**Issue by AlexAlexGoTO** [Sustainsys/Saml2#1335]
Hi,

I'm using Sustainsys.Saml2.Owin 2.9.0

I created application in azure and now I'm trying to login with your library but I'm getting error

 AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'https://my-site/saml2'.
 
 Here is my configuration
![image](https://user-images.githubusercontent.com/18060095/150815451-e1087bed-d768-497b-bdf9-5b0626accc0a.png)

When it's make request to Azure sign-in I don't see any redirect url in request string so I can't even understand what should I add to azure reply URLs.

I decided that it should be Assertion endpoint so I'm using '**https://my-site/saml2/Acs**' but it doesn't work

Cas someone help me to understand what reply URL should I use or where can I check it ?

I found similar issue here https://github.com/Sustainsys/Saml2/issues/1264

**Comment by AndersAbel** [comment]
The path is case sensitive, the correct one is `https://my-site/Saml2/Acs`.

**Comment by AlexAlexGoTO** [comment]
Thanks, I'll try tomorrow and give you feedback :)

**Comment by AlexAlexGoTO** [comment]
My Azure

![image](https://user-images.githubusercontent.com/18060095/150959646-6911c993-5478-492e-99ed-972e024af048.png)

My .NET

![image](https://user-images.githubusercontent.com/18060095/150960060-31997a7a-ebb9-4efa-ad37-07d79d3c3112.png)

My .NET Controller

![image](https://user-images.githubusercontent.com/18060095/150961010-4acd07bd-91fb-4c38-a61b-2ff6b85b7c69.png)

My error

![image](https://user-images.githubusercontent.com/18060095/150961181-1a91f8ca-c996-4433-be86-d0167b8661e7.png)

**Comment by AlexAlexGoTO** [comment]
Looks like azure see Acs as http when I make an request... So maybe something wrong with configuration. Continue investigating it

**Comment by AlexAlexGoTO** [comment]
I removed RedirectUri and ReturnUrl and now I don't have that error.
But now I have another one from library:
No Idp with entity id "https://sts.windows.net/xxxxxxxxxxxx/" found

**Comment by AlexAlexGoTO** [comment]
If I'm trying to set LoadMetadata = true - I'm getting
Unexpected entity id "https://sts.windows.net/xxxxxxx-xxxxx-xxxxx-xxxx-xxxxx/" found when loading metadata for "https://login.microsoftonline.com/xxxxxxx-xxxxx-xxxxx-xxxx-xxxxx/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxxx-xxxxx-xxxxx-xxxx-xxxxx".

**Comment by AndersAbel** [comment]
The Idp EntityId you've configured is obviously wrong. The one from the logs is the one received in metadata and in actual SAML2 message. I really hope that those have the same value - if not, you're configuration is really messed up.

**Comment by AlexAlexGoTO** [comment]
Thanks, I'll continue investigation and write something later here, when understand what is going on...

**Comment by AndersAbel** [comment]
Please keep each issue to one subject, I'm closing this. 

You might want to look at #666.
