### ISSUE TITLE
Issue Configuring Google Suite Applications

### ISSUE THREAD

**Issue by joaorsfonseca** [Sustainsys/Saml2#1342]
I'm trying to implement this with Google Suite Applications but no luck yet. I'm always getting the error No Idp with entity id "https://accounts.google.com/o/saml2?idpid=xxxx" found 

I was able to configure it for Okta.

**Comment by AndersAbel** [comment]
https://gitter.im/Sustainsys/Saml2?at=62543d523ae95a1ec1e178a2
