### ISSUE TITLE
Salesforce back promote gives error on dev instances

### ISSUE THREAD

**Issue by afandre** [Sustainsys/Saml2#1350]
We use Sustainsys with Salesforce as Idp to authenticate to a 4.7.2 MVC application.

We recently upgraded our .crt file in Salesforce production which had no impacts to our production environment. But when we back promoted to our DEV environment we receive the following error.

**Sustainsys.Saml2.Exceptions.InvalidSignatureException: Signature didn't verify. Have the contents been tampered with?**

I have tried pulling the new .crt file from SF and adding it to the MVC application. I have tried removing and replacing the .crt file. I've checked the systainsys.saml2 and identityProvider attributes and they're all correct.

What else can I try to resolve this issue?

**Comment by afandre** [comment]
Salesforce Summer 22 has a known issue which was related to the SAML response signature value tag containing characters "&#13;" before each "\n". It's now fixed.

**Comment by AndersAbel** [comment]
Thanks for reporting back, helping others confronted with the same issue.
