### ISSUE TITLE
No Controller Added in MVC Project

### ISSUE THREAD

**Issue by shnal** [Sustainsys/Saml2#1357]
Created a new .NET 4.72 web application.

Added package Sustainsys.Saml2.Mvc

Checked under /Controllers

No new controller added.

Is this intended behaviour?

![image](https://user-images.githubusercontent.com/12751143/182799705-53f89bcc-61be-419e-90c2-08f5521af7dc.png)

**Comment by shnal** [comment]
Sustainsys.Saml2.Mvc version 2.9.0

**Comment by shnal** [comment]
![image](https://user-images.githubusercontent.com/12751143/182800427-554aeb86-ef3b-489a-8d5c-ac08ca28be11.png)

**Comment by AndersAbel** [comment]
The controller is in the binary package, it does not show up in your source. Try accessing /Saml2 when the package is installed and it should give you the Metadata (if configuration is correct)

**Comment by shnal** [comment]
Thanks @AndersAbel 

In this case, how should I go about adding custom actions during the signon process?

**Comment by AndersAbel** [comment]
@shnal for better control, use the Owin package instead.

**Comment by shnal** [comment]
Thanks @AndersAbel
