### ISSUE TITLE
Federations element?

### ISSUE THREAD

**Issue by JerkerPihl** [Sustainsys/Saml2#1371]
I'am using the  Sustainsys.Saml2.HttpModule with asp.net 4.72
Iam trying to login to a single IDP, and my guess is that would make the federations element unnecessary?
Since its also branded as optional?

If I try to test this against the stupidp it breaks(with no federations)

If I dont use the federation element I get the Metadata.xml downloaded and nothing happens.

**Comment by AndersAbel** [comment]
No, with a single Idp you  should not use the Federation feature.

To start the sign in with the HttpModule, use the `/Saml2/Signin` endpoint. `/Saml2` gives you the SP metadata.
