### ISSUE TITLE
Logout SAML Request

### ISSUE THREAD

**Issue by bhumaanu** [Sustainsys/Saml2#1376]
I am trying to achieve saml request for signout using sustainsys. Is there a code snippet that I can refer to? Basically, I need to invoke a logut url by providing encoded logout saml as querystring. 

![image](https://user-images.githubusercontent.com/57880513/199838817-76131ba2-961e-4098-a69d-97953eae0c0d.png)

**Comment by AndersAbel** [comment]
The library supports single logout, but you need to add a service certificate to enable those endpoints as logout requests/responses should always be signed.
