### ISSUE TITLE
Duende IdentityServer Compatibility

### ISSUE THREAD

**Issue by raxit-technosouls** [Sustainsys/Saml2#1383]
Is this implementation compatible with Duende IdentityServer?

**Comment by AndersAbel** [comment]
Yes, an example with Duende's dynamic providers is available at https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/DuendeDynamicProviders

**Comment by raxit-technosouls** [comment]
That is great, thank you! just a quick follow up I see that is a dynamic provider which requires Enterprise license of Duende identity server. Is there a way to make it work with Business or Starter edition of Duende Identity Server which does not have dynamic provider support?

**Comment by AndersAbel** [comment]
It works as an normal provider too, check https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/AspNetCore for a normal wire-up.
