### ISSUE TITLE
About SampleOwinApplication running issue

### ISSUE THREAD

**Issue by jedi0605** [Sustainsys/Saml2#1388]
It's my first time using SAML so deeply.
I run demo project "SampleOwinApplication"  and Use another service to log in.
And see a page about "dummy discovery service".
I click  "Redirct back to SP" and recive "Unknown idp https://localhost:44300/Metadata"
How can I fix it?
Thanks a lot.

**Comment by AndersAbel** [comment]
To run the SampleOwinApplication you also need to run the local StubIdp on port 44300 on the same time.
