### ISSUE TITLE
Installing sustainsys.saml2 HTTPModule V1

### ISSUE THREAD

**Issue by adkessell** [Sustainsys/Saml2#1393]
I have successfully implemented version 2.0 of HTTPModule for my latest code base using .net framework 4.8.

I am now trying to install the version 1.0.2 from Nuget for the HTTPModule on my current version that is using .net framework 4.5.2, however I am getting the following error.

Could not install package 'Sustainsys.Saml2.HttpModule 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 

Thanks
Anthony

**Comment by AndersAbel** [comment]
I guess there's a typo and you mean you are using 1.0 currently?

v1.0.2 adds support for the SameSite attribute on cookies. Support for that was added in .NET 4.7.2 so the target framework had to be raised.

**Comment by adkessell** [comment]
I took nuget v2.9.0 of HTTPModule and am using that in my latest code base that is using .net framework 4.8 and it works just fine.

I need a version that works on .net framework 4.5.2 and I thought that was v1 of the code base.

Is there a version of sustainsys.saml2 HTTPModule that works with .net framework 4.5.2?

Thanks
Anthony

**Comment by AndersAbel** [comment]
Unfortunately not as the Saml2 workflow requires SameSite cookie support, so only versions .Net Framework that supports the SameSite attribute on cookies work.
