### ISSUE TITLE
Single Log Out

### ISSUE THREAD

**Issue by SahilDhingraa** [Sustainsys/Saml2#1394]
I am implementing saml2 on my project which is based on .net core and I made the login method but I'm facing multiple issues in logOut (Single LogOut) method). I checked everywhere on the internet but found nothing that can help me. so can you please share the implementation of SLO

**Comment by AndersAbel** [comment]
https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/AspNetCore

**Comment by SahilDhingraa** [comment]
this is not helping

**Comment by AndersAbel** [comment]
It is .Net Core example, which is what you asked for.

If you want further help on how to design your authentication system to make Saml2 work with a web api, I can provide that as a commercial consulting service. Please mail support@sustainsys.com for information.
