### ISSUE TITLE
Is there a public api exposed by Sustainsys to validate a SAML assertion?

### ISSUE THREAD

**Issue by arnab-1995** [Sustainsys/Saml2#1404]
Does Sustainsys library provide a generic method to validate a SAML assertion and get the claims from the assertion?

**Comment by AndersAbel** [comment]
If you have a SAML assertion and want to get claims you can use the `Microsoft.IdentityModel.Tokens.Saml2` library directly, that is what Sustainsys.Saml2 uses to validate the assertion.
