### ISSUE TITLE
XML is invalid - Using XML Validation tool

### ISSUE THREAD

**Issue by mcampbell66** [Sustainsys/Saml2#1420]
version 2.9.1 when the XML is checked by IDP they are getting an XML is invalid and users are then not able to login.

When we drop the XML into a validation tool this is the message we get:
Line: 34 | Column: 0  --> Element '{urn:oasis:names:tc:SAML:2.0:metadata}RequestedAttribute': This element is not expected. Expected is ( {urn:oasis:names:tc:SAML:2.0:metadata}ServiceName ).

This is what is on line 34:
`<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://oursitenameandisvalid/IdSrv/Saml2/Acs" isDefault="true" index="0"/>`

Please note that there is no guarantee that your question will be answered. For commercial support with guaranteed response times, please mail support@sustainsys.com.

**Comment by AndersAbel** [comment]
This is when the Idp reads the metadata, right?

The error message doesn't match what you've pasted. Please share the entire Metadata file. You can redact sensitive values as long as the Xml structure is intact.

**Comment by mcampbell66** [comment]
Hi Support,

I’ve included the XML attached. I had to zip in order to send. It has been redacted but using this XML Tool it does still get the same error.


https://www.samltool.com/validate_xml.php<https://www.samltool.com/validate_xml.php%22%20%5Co%20%22https:/www.samltool.com/validate_xml.php>


Thank you
Matt

From: matt m2xi.com ***@***.***>
Date: Friday, December 1, 2023 at 6:08 AM
To: Sustainsys/Saml2 ***@***.***>, Sustainsys/Saml2 ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [Sustainsys/Saml2] XML is invalid - Using XML Validation tool (Issue #1420)
Hi Support,

Will this screenshot work or do you need a working XML file?
Thanks
Matt
***@***.***

From: Anders Abel ***@***.***>
Date: Friday, December 1, 2023 at 12:01 AM
To: Sustainsys/Saml2 ***@***.***>
Cc: matt m2xi.com ***@***.***>, Author ***@***.***>
Subject: Re: [Sustainsys/Saml2] XML is invalid - Using XML Validation tool (Issue #1420)

This is when the Idp reads the metadata, right?

The error message doesn't match what you've pasted. Please share the entire Metadata file. You can redact sensitive values as long as the Xml structure is intact.

**Comment by AndersAbel** [comment]
Attachments and images are lost when using e-mails to interact with GitHub. Please use the GitHub site to respond/update the thread.

The GitHub issue tracker works best for simple questions. If you need support analyzing/troubleshooting specific data, commercial support might be a better fit. Please reach out to support@sustainsys.com for more information.

**Comment by AndersAbel** [comment]
When using `AttributeConsumingService` there must be at least one entry in the `ServiceNames` collection. Unfortunately the library does not warn if that is not configured, but instead produces incorrect metadata.
