### ISSUE TITLE
Changing Default Login Endpoint

### ISSUE THREAD

**Issue by innotech-banha** [Sustainsys/Saml2#1422]
I'm using the package Sustainsys.Saml2.AspNetCore2 (version 2.9.2) for .NET 6.

I have a successfully gotten the package to work, authenticating and authorizing a user to access my web API. But now I'm facing a situation that I cannot find a solution for in the existing documentation, which is how to modify the default login address that a user is redirected to when trying to access an endpoint that requires authorization, while they have not yet logged themselves in.
I'm being reidrected to the endpoint "/Account/Login". Is it possible to modify this?

On that same note, is it also possible to customize the endpoint for when a user is denied access?

**Comment by AndersAbel** [comment]
Those options are handled by the cookie scheme and [can be configured.](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions?view=aspnetcore-7.0)

**Comment by innotech-banha** [comment]
Oh, I see! Thank you very much! That seems to definitely be what I needed, much appreciated! =) And happy holidays!
