### ISSUE TITLE
Getting Saml2Response must have status success to extract claims issue

### ISSUE THREAD

**Issue by Bhubalan** [Sustainsys/Saml2#1433]
Please be informed we are using Sustainsys 2.9.2 for SAML authentication. We have 2 Identity provide and for one we are able to successfully authenticate however for another IDP we are facing the  Saml2Response must have status success to extract claims issue. 

Please refer the attached screen shot as well. 

for additional Tech info 
    
      Technology - ASP.NET 
      Programming language - vb.net
      .NET Framework - 4.5
Sustainsys Configured in the web.config file

**Comment by AndersAbel** [comment]
Looks like something is incorrect with your configuration. I can help troubleshooting specific configuration issues as a commercial support/consulting service. Please reach out to support@sustainsys.com for more information.
