### ISSUE TITLE
How to override/change ACS URL?

### ISSUE THREAD

**Issue by JasonRucco** [Sustainsys/Saml2#1434]
I'm currently integrating with an IDP who only supports idp initiated sso and will only initiate through an endpoint /saml/sso/post

Is there a way to change the default ACS URL from "/saml2/acs" so that i can respect the idp's request that my endpoint follow the format ".../saml/sso/post"

**Comment by JasonRucco** [comment]
Thanks so much for the response

**Comment by AndersAbel** [comment]
@wan766405890 The `/Saml2/Acs` endpoint/path is handled internally by the Authentication handler. You don't need to write your own controller/endpoint for that path.
