### ISSUE TITLE
.net core getting "InvalidSignatureException The Signature verified correctly with the key contained in teh signature, but that key is not trusted."

### ISSUE THREAD

**Issue by hans9025** [Sustainsys/Saml2#1435]
we already have the V1 implementation of Sustainsys in .net framework 4.5 which is working fine, when i am trying to implement the same using V2 version on .net core getting below error after authentication , I tried samle code from here https://github.com/Sustainsys/Saml2.Samples/tree/main/v2

![image](https://github.com/Sustainsys/Saml2/assets/76694666/a20aa1f9-fc5c-4672-a02a-aba3a1895c1b)

we have this assertion <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost:44369/Saml2/Acs" index="1"/>, do we have to change anything here

**Comment by AndersAbel** [comment]
It looks like there's a configuration issue in the new setup. I would be happy to help you sorting out the configuration under my commercial support services. Please mail support@sustainsys.com for information.
