### ISSUE TITLE
Missing assertion consumer service url configuration on Idp https://localhost:44369/

### ISSUE THREAD

**Issue by hans9025** [Sustainsys/Saml2#1436]
I am getting this error Missing assertion consumer service url configuration on Idp https://localhost:44369/.
Don't know where i need to set AssertionConsumerServiceUrl, I tried setting in metadata like below in screen shot, is their any valid metdata file where i can compare my metadata.

<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" validUntil="2021-10-02T06:48:21Z" cacheDuration="PT604800S" entityID="https://localhost:44369/" >

	<md:IDPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol" >
    <md:KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate></ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:KeyDescriptor use="encryption">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate></ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:44369/Saml2/Acs" index="1"/>
    <md:AssertionConsumerServiceURL Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://epitest.mazdausa.com/Saml2/Acs" index="1"/>
  </md:IDPSSODescriptor>

  <md:Organization>
    <md:OrganizationName xml:lang="en-US">Mazda North American Operations</md:OrganizationName>
    <md:OrganizationDisplayName xml:lang="en-US">Mazda North American Operations</md:OrganizationDisplayName>
    <md:OrganizationURL xml:lang="en-US">https://www.mazdausa.com</md:OrganizationURL>
  </md:Organization>
  <md:ContactPerson contactType="technical">
    <md:GivenName>Wilfred Gonsalves</md:GivenName>
    <md:EmailAddress>wgonsalv@mazdausa.com</md:EmailAddress>
  </md:ContactPerson>
  <md:ContactPerson contactType="support">
    <md:GivenName>Ben Rounsefell</md:GivenName>
    <md:EmailAddress>brounsef@mazdausa.com</md:EmailAddress>
  </md:ContactPerson>
</md:EntityDescriptor>

![image](https://github.com/Sustainsys/Saml2/assets/76694666/a3b5f0fb-6e8e-441a-820d-4f35885db120)

**Comment by AndersAbel** [comment]
Are you running the stubidp on localhost:44369?

Exactly where do you get the error message?
