### ISSUE TITLE
SignInAsync getting me in loop, any reason  why 

### ISSUE THREAD

**Issue by hans9025** [Sustainsys/Saml2#1439]
following is my code

![image](https://github.com/Sustainsys/Saml2/assets/76694666/a3e038cd-dee3-4b23-a8d6-04008275011b)

**Comment by AndersAbel** [comment]
The OnSignedIn event is called by the cookie handler as part of SignInAsync processing. This code will create an endless loop and whatever you are trying to achieve this is not the right way.

**Comment by AndersAbel** [comment]
Closing as this is not at all related to the Saml2 library but to general Asp.Net Core Authentication.
