### ISSUE TITLE
SAML authentication with different Active Directory

### ISSUE THREAD

**Issue by 22Rushikesh** [Sustainsys/Saml2#1445]
Hi I am trying to navigate to a different cloud login page but some how it says "The SAML protocol message cannot be read because it contains data that is not valid" 

Error details: MSIS0018: The SAML protocol message cannot be read because it contains data that is not valid.
Node name: b9d08201-609f-41c5-9075-ea3617bfb205
Error time: Fri, 08 Mar 2024 10:00:27 GMT
Proxy server name: AP***01
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by 22Rushikesh** [comment]
my url looks like this :- https://adfs.edgegroup.ae/adfs/ls/?SAMLRequest=fJDBaoQwFEV%2FRbLXxEQHfagg7UaYbsa225KJmVHQxOYlpZ9fxzIw3XR5H%2BdyD69CucwrtMGP5qQ%2Fg0Yfdc81%2BThkYhBnlsaZlOc4ywoZl6pI45SXg1LikilxIFGHGHRn0Evja8IZz2ImYla8phx4AWmeiJyLUuQketcOJ2s2KmEkahG181t%2BsgbDol2v3dek9NvpWJPR%2BxWB0tkqOY8WPeSMpbTfVDltFZLoe5kNwu5ek%2BAMWIkTgpGLRvAK%2BvblCNsQrM56q%2BxMmupGwy7sHvr%2F1%2BVdkzR3KTlcMNHDVV%2BdDWsi9X6hG3fzR%2BpdQF%2FRh7XmN%2F39cvMDAAD%2F%2FwMA

**Comment by AndersAbel** [comment]
Looks like your Idp reports an error on the request you have created. Can you get any more detailed information from the Idp on what is wrong?
