### ISSUE TITLE
Support dynamically updating the ServiceCertificates during rollover (ASP.NET Core)

### ISSUE THREAD

**Issue by chwallen** [Sustainsys/Saml2#1447]
We are using rolling certificates with quite short validity periods (60 - 90 days). In order for the rollover to take effect in the metadata, we need to restart our service as the certificates are loaded once from disk during `AddSaml2`. If the `Certificate` property of `ServiceCertificate` was virtual, or the `ServiceCertificateCollection` would use `IServiceCertificate`s instead, we could easily implement this in a subclass.

Environment:
- .NET Core 8
- Sustainsys.Saml2.AspNetCore2 v2.9.2

**Comment by AndersAbel** [comment]
Reopening and adding as a possible future feature to consider for v3.
