### ISSUE TITLE
Thank you 💖

### ISSUE THREAD

**Issue by mderriey** [Sustainsys/Saml2#1455]
Hi there,

We've had to integrate with a SAML provider and found this project.

The integration was a breeze, so we wanted to thank you!
We don't know a lot about SAML, and the library handles all the nitty bits for us, which is much appreciated.

Our setup is not super common, but we found workarounds for everything:

- We don't know the entity ID of our IdP, so we register a single one with a name we picked, and leveraged `Notifications.GetIdentityProvider` to always select the one we registered.
- Similarly, we don't know the entity ID of our service provider in the IdP, so we had to disable audience validation, which we did with `Notifications.Unsafe.TokenValidationParametersCreated`.
- Loading the signature verification and assertion decryption certificates was super easy.
- Allowing IdP-initiated flows was a property assignment away.

I know some of this sounds strange, but we had to configure the provider with limited information from an external system that we don't have control over. The point is that the library made it super easy for us to integrate with a SAML provider and work around the oddities of our setup.

Thanks again!

**Comment by AndersAbel** [comment]
Thank you for your kind words.

You are right in that some of this sounds a bit strange. After a decade working on this library I've learned that there are so many special cases that I would never have thought about from the start. I'm happy to hear that the extension points available made it possible for you to customize the library to work for you.
