### ISSUE TITLE
Could not load type 'Sustainsys.Saml2.WebSso.Saml2Module' from assembly 'Sustainsys.Saml2'

### ISSUE THREAD

**Issue by AdarshSynfinity** [Sustainsys/Saml2#1462]
# Security issues

"I'm implementing SSO login using SAML authentication with Okta as the Identity Provider (IDP) in a **.NET Framework 4.8.1** web API application. After setting up the Assertion Consumer Service (ACS) URL, we successfully triggered the ACS method and placed a debug point. To access the user details from the SAML assertion, I need an external library/package, so I'm using 'Sustainsys.Saml2'. According to the official documentation and reference sites, the first step is to add some configuration settings to the web.config file, as shown below."

Refer to the system.webserver tag from web.config attached in the below screenshots.

As soon as this line add name = Saml2Module is added when the application is started the above error occurs.
Please refer to the below error message

![ErrorPage](https://github.com/user-attachments/assets/1a7ee72a-2a96-4e42-84b6-532ad8de9369)
![SAML pkg](https://github.com/user-attachments/assets/fb4e972f-d27c-4540-8edd-9fd04c2b4a8e)
![WebconfigPage](https://github.com/user-attachments/assets/d2d3ec79-159c-433b-9e28-534b3b283825)
![WebCOnfigPage2](https://github.com/user-attachments/assets/119aceab-dd33-4c87-b77e-47d303fa6eeb)

Please let me know if Sustainsys.Saml2 supports .NET framework 4.8.1 application to fetch the user details from SAML assertion (IDP).

Please drop example code/ resource if any for .NET framework web api application.

**Comment by AndersAbel** [comment]
The HttpModule is in the `Sustainsys.Saml2.HttpModule` package.

**Comment by AdarshSynfinity** [comment]
Thanks @AndersAbel,
I tried installing Sustainsys.Saml2.HttpModule package installed successfully.
But i'm still getting the same issue.

![VisualStudio2022](https://github.com/user-attachments/assets/e3fe8131-0f27-456f-bf78-8408166badb2)
![same issue](https://github.com/user-attachments/assets/312b0a54-d53f-4112-a596-c58a2bac890f)

**Comment by AndersAbel** [comment]
It looks like your configuration is incorrect. See https://github.com/Sustainsys/Saml2/blob/v2/Samples/SampleHttpModuleApplication/Web.config for a working example.
