### ISSUE TITLE
Consider making all cookies Secure

### ISSUE THREAD

**Issue by iconics-milan** [Sustainsys/Saml2#1465]
Currently, the Saml2 library is smart and sets the Secure flag only on cookies on HTTPS requests.

But cookies which are not marked as Secure are automatically refused by Chrome, because they have SameSite=None (which is required for SAML to work). 
This post discusses Chrome refusing SameSite=None without Secure: https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure

Chrome also refuses these cookies on http://localhost, which is unfortunate during development.

If the cookies were set as Secure in all cases, they actually would work on http://localhost according to this excerpt from MDN:
"_A cookie with the Secure attribute is only sent to the server with an encrypted request over the HTTPS protocol. It's never sent with unsecured HTTP (except on localhost)_" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)

Please consider dropping the current logic and simply mark all cookies as Secure if they are using the option SameSite=None.

**Comment by AndersAbel** [comment]
My recommendation is to always use https, even on localhost for development. I do not think that updating this is relevant for the v1/v2 branches. On the v3 branch it makes sense to ensure there is a way to intercept and update the cookie flags.

**Comment by iconics-milan** [comment]
We were able to use a custom ICookieManager to intercept and update the cookie flags, so we are all set, thanks!

I just thought that you would appreciate a simplification of the Sustainsys.Saml2 code, as the current logic that makes the cookies sometimes Secure and sometimes not, does make little sense nowadays, given that modern browsers simply require this flag for SameSite=None cookies.

**Comment by AndersAbel** [comment]
Happy to hear that you got this solved.

And yes, I do appreciate cleaning up the code - that's why I'm trying to get time to work on v3 to move to a better architecture.
