### ISSUE TITLE
How to generate https link of ACS in metadata 

### ISSUE THREAD

**Issue by wjfang90** [Sustainsys/Saml2#1467]
hi guys,

I hope you can help me,thank you.

I used Sustainsys.Saml2.Mvc 2.10.0

I configurate domain like test.project.com on the website with http and https protocol, and I download the metadata with https://test.project.com/saml2. it's ok. But the ACS url is http 

the metadata file like this
![1724903963821](https://github.com/user-attachments/assets/194a762e-ae05-4904-b332-633260852c89)

the web.config is this 
[
![1724904156005](https://github.com/user-attachments/assets/a6326dd4-2d33-499a-887c-a13d331e8d83)
](url)

**Comment by AndersAbel** [comment]
If the generated URLs are http even if your are using https, you need to set the PublicOrigin option (Note: This advice is for the Mvc package, not for Asp.Net Core)

**Comment by wjfang90** [comment]
Thank you for answer,it works.
