### ISSUE TITLE
I updated from version 2.9.0 to 2.9.1 and 2.9.2 and my SSO link is changing

### ISSUE THREAD

**Issue by Revon-Rayen** [Sustainsys/Saml2#1469]
I have an application that was running sustain.sys at version 2.9.0 and my login button was working without any problems. However when I upgraded to version 2.9.1 the single sign on url is changing from what I've declared. The url is supposed to be https://sp.examplecompany.com/gg/public/saml2sso but after the update the url is changing to https://sp.examplecompany.com/gg/secure/securedirect  . I didn't do any changes to my appsettings or configuration all I did was update the nuget package in my application and this problem appeared. I also updated to version 2.9.2 and the same problem occurs. Downgrading back to 2.9.0 fixed it but I need to upgrade.

**Comment by AndersAbel** [comment]
This looks really weird. The URL is not the default one created by this library. How have you set it up to use /public/saml2sso as the URL?
