### ISSUE TITLE
Release new version on nuget

### ISSUE THREAD

**Issue by rgroenewoudt** [Sustainsys/Saml2#1479]
The latest version on [NuGet](https://www.nuget.org/packages/Sustainsys.Saml2#dependencies-body-tab) still references many obsolete packages and this results in many security warnings in .NET 9.

In september 2023 this was fixed in the commit https://github.com/Sustainsys/Saml2/commit/61815296db61a62a1b84303401337071ab08af82 but the nuget package doesn't target net6.0.

Could you release a new version of the v2 branch to nuget?

**Comment by AndersAbel** [comment]
The v2.11.0 release has improved targets - do they look good?

**Comment by rgroenewoudt** [comment]
Oh yes, that's already better. The version of dependencies are still very old but that's not a big problem.

**Comment by AndersAbel** [comment]
I try to keep the package dependencies to the lowest version without known vulnerabilities. Someone referencing the Saml2 libraries in their application can always force an upgrade to newer version of the dependencies, but they cannot reference anything older. If the Saml2 packages would enforce the latest version, that would potentially break a lot of applications that for some reason cannot update all dependencies.
