### ISSUE TITLE
Correct handling of cacheDuration and validUntil

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#170]
The handling of `cacheDuration` and `validUntil` is not correct according to the specification. They are treated as they have the same meaning, which they don't.

Correct it, which means that:
- `cacheDuration` is the refresh interval.
- `validUntil` is the end time by which the idps should be deactivated.

Even if a metadata refresh fails, the data should still be considered valid until the `validUntil` time has passed.

If `cacheDuration` is missing, the present algorithm using half-times up to `validUntil` should be used. If `validUntil` is missing, the metadata should be considered valid for ever.

If both are missing, the metadata should be considered valid for ever and `cacheDuration` should get a default of 1 hour.

**Comment by TimV81** [comment]
@AndersAbel why are you giving the _optional_ properties a default value? My IdP specifically requires to omit cacheDuration since it isn't used on their end. How do I do this?

**Comment by AndersAbel** [comment]
@TimV81 That's a separate subject as it concerns the values generated by AuthServices. This issue is about handling of Idp metadata read by AuthServices.

Please open a new issue.
