### ISSUE TITLE
Service Provider signing certificate in SP metadata.

### ISSUE THREAD

**Issue by emilienmartinez** [Sustainsys/Saml2#176]
Hello,

Thanks for sharing this great project! it saves me lot of time!
I've got a question: is there a way to pass public signing key in SP metadata in order to allow Idp to encrypt SAML Response with my public key?

Regards,

Emilien

**Comment by Raschmann** [comment]
Hello,

please look here https://github.com/Raschmann/authservices/tree/Release for  branch implementing SP AuthnRequest signing and encrypted assertion implementation. It will take some time to become part of the maste branch.

**Comment by emilienmartinez** [comment]
Thank you, I've found it and it works well.
