### ISSUE TITLE
Redirect URL from RelayState

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#250]
When using Idp-initiated login, there is a convention that the Idp can specify the URL to redirect after successful authentication, by including that in the RelayState parameter. We should add support for that.

See http://saml.xml.org/wiki/idp-initiated-single-sign-on-post-binding

**Comment by CryptonZylog** [comment]
Seconded!

How would you handle this in ASP.NET execution pipeline? Setting a parameter within BeginRequest (overridable) or just grabbing the ReturnUrl from Forms Authentication?

**Comment by AndersAbel** [comment]
@CryptonZylog I don't understand your question. Using a Redirect URL from relay state would only be useful with IDP initiated login. Using SP initiated login, the IDP is required to relay back whatever the SP put in the relaystate, so in that case the IDP can't (ab)use the RelayState parameter for a target URL.

**Comment by CryptonZylog** [comment]
In our case, suppose a user follows a link to a specific protected page, but they are unauthenticated. They get redirected to IdP, authenticate, then IdP redirects them back to the static URL configured for AuthServices. I haven't had a chance to verify this yet, but it does not seem like AuthServices supports redirecting them back to the original URL they were requesting. Please correct me if I'm wrong.

**Comment by albinsunnanbo** [comment]
If you have SP initiated login, AuthServices should respect the returnUrl parameter on the SignIn command.
/AuthServices/SignIn?returnUrl=https://myApp.com/aProtectedPage/ should fix the redirect. With no returnUrl parameter AuthServices uses the configured returnUrl from the config file.

**Comment by AndersAbel** [comment]
@CryptonZylog AuthServices already supports redirecting back to the URL that triggered the signin. The MVC and Owin sample applications in the repo demonstrates that. This issue is about IDP-initiated login with a direct link to a specific resource.

**Comment by CryptonZylog** [comment]
Excellent, thanks for the clarification.

**Comment by nahidf** [comment]
Any update on this?

**Comment by AndersAbel** [comment]
@nahidf It's unfortunately not prioritized for us at Kentor the moment and as far as I know there's noone else working on it. If you need it you are welcome to submit a Pull Request (please check contribution guidelines first). Kentor also offers sponsored development where you pay for a specific feature (like this) to be completed. Please mail me at anders.abel@kentor.se if that's interesting.

**Comment by chrisnott** [comment]
I really need this functionality and am loathe to fork the repository and use my own custom version to achieve this. I realise that it is not a priority but there is an open PR - any chance that this will be looked at soon?

**Comment by AndersAbel** [comment]
@chrisnott It's in the backlog and I can't give you any date on when I have time to work through it.

Current status is that I'm more or less keeping up with new issues coming in, but I've still not had time to work with the backlog.

I took a quick look on the PR and I'm a bit concerned about the approach taken there, especially that it looks like tests are only done on the MVC module. I think this should be fixed in the AcsCommand.

If you want to get priority to a specific PR, that's part of what I offer in my commercial support agreement. Please mail me at anders@sustainsys.com for more info.

**Comment by chrisrrowland** [comment]
> If you have SP initiated login, AuthServices should respect the returnUrl parameter on the SignIn command.
> /AuthServices/SignIn?returnUrl=https://myApp.com/aProtectedPage/ should fix the redirect. With no returnUrl parameter AuthServices uses the configured returnUrl from the config file.

This is an old issue but in case anyone else comes across this comment, it took me a while to realize that it needs to be 'ReturnUrl' rather than 'returnUrl'
