### ISSUE TITLE
Q: NameClaimType & RoleClaimType

### ISSUE THREAD

**Issue by Peperud** [Sustainsys/Saml2#300]
Is there a way in Kentor middleware to specify/configure NameClaimType (and RoleClaimType)?

**Comment by AndersAbel** [comment]
Yes, implement a `ClaimsAuthenticationManager` and set it there. There is info in the [documentation](https://github.com/KentorIT/authservices/blob/master/doc/ClaimsAuthenticationManager.md) on how to do it.

**Comment by Peperud** [comment]
@

**Comment by Peperud** [comment]
@AndersAbel 
Does this still apply to OWIN? It doesn't appear to take my class...
Besides...at the time it gets called to process the incoming claims, unless there's some state info passed to it, how would it go about to make the proper decision when dealing with potentially multiple IdPs? 

What I seem to be going at is - doesn't it make sense to have these as settings on say the IdP configuration for Kentor and have the Kentor middleware use them instead of the defaults?

**Comment by albinsunnanbo** [comment]
We have it running on OWIN.

You can check the [Claim.Issuer](https://msdn.microsoft.com/en-us/library/microsoft.identitymodel.claims.claim.issuer.aspx) property on any of the claims to find out the IDP.

Since the ClaimsAuthenticationManager is the canonical place in Identity to "here is what you got, transform it as you like" place I don't see any obvious reason to duplicate that functionality in Authservices.
Besides if you have multiple IDP:s with different claims I would suggest that you use the ClaimsAuthenticationManager to map the incoming claims to a common set of claims that you use in the application.

**Comment by AndersAbel** [comment]
@Peperud Yes, it still applies to Owin, but if you're using code-based configuration (with `new KentorAuthServicesOptions(false)`) you should set the `ClaimsAuthenticationManager` in the code too, not in the config file. The docs are a bit outdated on that.

**Comment by AndersAbel** [comment]
@Peperud I just updated the documentation with how to do it in code with OWIN.

**Comment by Peperud** [comment]
@AndersAbel Thanks, that did it.

@

**Comment by ckouroupis** [comment]
Hi @AndersAbel,
Firstly, thank you very much for bringing Kentor.AuthServices into the .Net community!!

I agree with @Peperud in that it would be nice to make NameClaimType and RoleClaimType configurable on the IdentityProvider level.  It is the party hosting the IdP who will govern which attribute contains the "Name" claim and it makes sense to configure it in the IdentityProvider.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.

**Comment by npnm** [comment]
> Yes, implement a `ClaimsAuthenticationManager` and set it there. There is info in the [documentation](https://github.com/KentorIT/authservices/blob/master/doc/ClaimsAuthenticationManager.md) on how to do it.

I am trying to upgrade  one .Net framework library to .Net core which is using Saml2 auth v1.  In that library 'spOptions.SystemIdentityModelIdentityConfiguration.ClaimsAuthenticationManager' was using to perform some transformation logic in claim. Like adding/modifying the claim.
As 'SystemIdentityModelIdentityConfiguration' is  now not available in 'SPOptions' in v2 version of Saml2, where I can place that claim transformation logic? In v2, is there any way to do it?  Any thoughts?
