### ISSUE TITLE
Include debug symbols in NuGet packages

### ISSUE THREAD

**Issue by albinsunnanbo** [Sustainsys/Saml2#320]
To make better stack traces we should include debug symbols in our NuGet packages.
Either in the main package, or in a separate .symbols.nuget package.

Alternative solutions could also be publishing symbols to SymbolSource: https://docs.nuget.org/create/creating-and-publishing-a-symbol-package
or using GitLink: https://github.com/GitTools/GitLink

**Comment by AndersAbel** [comment]
Replaced by #1345
