### ISSUE TITLE
Enable parallell test run

### ISSUE THREAD

**Issue by dariusdamalakas** [Sustainsys/Saml2#329]
Tests fail when using NCrunch. Seems there is an issue with [MetadataServer.Start](https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices.Tests/Metadata/MetadataServer.cs#L311) method, which starts a local metadata server.  

Exceptions are being [swallowed](https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/IdentityProvider.cs#L270),  so it's difficult to track where it initially fails.

Total 120 out of 367 tests fail.

**Comment by AndersAbel** [comment]
Are you running the tests in parallel or sequentially?

**Comment by dariusdamalakas** [comment]
Yes, that's first thing i've tried - running sequentially gives same results.

**Comment by AndersAbel** [comment]
Good. The tests for metadata won't work in parallel. They all depend on the single Metadata server instance and during the run various flags are set on the Metadata server to alter its behaviour.

The reason for this is to save time when running sequentially opening up an http server every single time would be too time consuming.

Can you see if NCrunch tries to start the MetadataServer several times? That would cause issues with the port being occupied by the first instance.

The best way to handle this is probably to isolate the actual http downloading into a component that can be stubbed out during tests.

**Comment by dariusdamalakas** [comment]
Thansk, well this was my first question - why a real server was used in tests, perhaps this could not be mocked or stubbed easily? Any potential blockers here?

**Comment by AndersAbel** [comment]
It should be quite simple to Mock. Maybe something like this:

    internal static Func<MetadataBase, Uri> Load { get; set; } = metadataUrl =>
    {
      // Current implementation
    }

In the test setup, a stub implementation can be injected. Internal hides the injection point for real clients. The tests can access internal stuff thanks to InternalsVisibleTo.
