### ISSUE TITLE
Use http headers with proxy info for URL generation

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#363]
When AuthServicesUrls generates URLs from an http request it should look at common http proxy info headers to get the client-facing URL.

Headers that appears to be used are:
- [HTTP_FRONT_END_HTTPS](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields)
- [X-Forwarded-Proto](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields)
- [X-Forwarded-Host](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields)
- [Forwarded](http://tools.ietf.org/html/rfc7239)

**Comment by explunit** [comment]
Note that #609 provides a notification hook to set this value per-request based on your own logic for whatever headers are used in your environment.

**Comment by AndersAbel** [comment]
This is already correctly handled in Asp.Net Core - the request URL is fixed to contain the public facing url. And I'm not spending time on fixing things for the older platforms any more.
