### ISSUE TITLE
SP Metadata

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#4]
Expose metadata from the SP.

**Comment by dazinator** [comment]
Is this metadata automatically exposed on some URL for an IDP to obtain? (i.m using the asp.net core saml2 authentication nuget package)

**Comment by explunit** [comment]
@dazinator Yes, by default the metadata is exposed at the root url where you configured the Saml2 handler, so for example if you configured at `http://myapp/saml2` then `http://myapp/saml2` would be the metadata, `http://myapp/saml2/acs` would be the assertion consumer service, etc.

**Comment by dazinator** [comment]
@explunit - thanks! I had almost started to write my own endpoint :-)
