### ISSUE TITLE
Authentication workflow successfull, but User not authenticated

### ISSUE THREAD

**Issue by HeikoLux** [Sustainsys/Saml2#453]
I downloaded code and ran the owin example. Everything worked, SAML respones status code is success, but secured Action in Controller was not passed.
`User.Identity.IsAuthenticated` is false.
Can you help me?

/Heiko

**Comment by AndersAbel** [comment]
Please use https://coding.abel.nu/2014/06/understanding-the-owin-external-authentication-pipeline/ as a starting point and try to find out how far in the authentication it works.

**Comment by AndersAbel** [comment]
Old, no further comments, closing.
