### ISSUE TITLE
Saml2Artifactbinding.Unbind always sets `TrustLevel.None`

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#511]
Saml2ArtifactBinding.Unbind always sets the `TrustLevel` to `None` which is incorrect. It should set it to `HttpGet` if the artifact resolution endpoint is http, `TlsTransport` if the artifact resolution endpoint is https and `Signature` if the artifact response message is signed.

**Comment by btopalka** [comment]
is there a work around for this?

**Comment by AndersAbel** [comment]
No, this is something that needs to be added to support a wider range of how Idps handle Artifact resolution.

What issues are you actually running into? This bug is a corner case so unless you have a quite special setup, you shouldn't be affected by this. Chances are that it's something else that is the actual problem.
