### ISSUE TITLE
Version conflict with Asp Net Core 1.0.0 release

### ISSUE THREAD

**Issue by Thaoden** [Sustainsys/Saml2#529]
Due to some breaking changes in the Asp.net Core libraries (see https://github.com/aspnet/Announcements/issues/187), Kentor.AuthServices.AspNetCore (which uses 1.0.0-rc2-final packages) currently can't be used with an Asp.Net Core 1.0.0 application (which use 1.0.0 packages).

**Comment by AndersAbel** [comment]
New asp.net core library is planned, will target later versions and resolve this.
