### ISSUE TITLE
Raw SAML assertion

### ISSUE THREAD

**Issue by minarikjan** [Sustainsys/Saml2#553]
I try get raw SAML assetion (XML) in SampleOwinApplication. 

I tried these solutions:

**Solution 1:**

In Startup ConfigureAuth added:

`FederatedAuthentication.FederationConfiguration.IdentityConfiguration.SaveBootstrapContext = true;`

Access to the token:

```
    var icp = System.Security.Claims.ClaimsPrincipal.Current;

    var claimsIdentity = icp.Identity as System.Security.Claims.ClaimsIdentity;

    var ctx = claimsIdentity.BootstrapContext as System.IdentityModel.Tokens.BootstrapContext;

    var token = ctx.SecurityToken;
```

But BootstrapContext is null.

**Solution 2**

I set on SpOptions:

`spOptions.SystemIdentityModelIdentityConfiguration.SaveBootstrapContext = true;`

When I debug in class Saml2PSecurityTokenHandler in method CreateClaims is set identity.BootstrapContext. This is OK.

But when I try access to token for example from HomeController BootstrapContext is null.

```
    var claimsIdentity = icp.Identity as System.Security.Claims.ClaimsIdentity;

    var ctx = claimsIdentity.BootstrapContext as System.IdentityModel.Tokens.BootstrapContext;

    var token = ctx.SecurityToken;
```

Thank

**Comment by explunit** [comment]
If you're just looking for the raw XML you can use the Notifications system, e.g. 

```
myoptions.Notifications.MessageUnbound = unbindResult =>
{
	var xml = unbindResult.Data.OuterXml;
};
```

**Comment by AndersAbel** [comment]
The bootstrap token is not preserved by the session cookie module. Use SaveBootstrapContext and then use the AcsCommandResultCreated to grab the result.

**Comment by blaur** [comment]
@AndersAbel Sorry to tagging you here. Just have one question in regards to your above comment. I can easily grab the bootstrap context from AcsCommandResultCreated but is there no way of accessing that context outside? Could I tell it to preserve it in the session cookie somehow? Not having the bootstrap context in the identity could be problematic if you wanted to validate that identity at a later stage.

Any ideas?

**Comment by AndersAbel** [comment]
@blaur I think this behaviour has been improved in Asp.Net Core, and that's where any new efforts will be focused. Closing this as won't fix.
