### ISSUE TITLE
Error: ID4262

### ISSUE THREAD

**Issue by tforde1974** [Sustainsys/Saml2#558]
> Hi, I am getting the following error message and for the life of me I cannot figure out why.  The saml response is correct and I am using the latest build.

ID4262: The SAML NameIdentifier 'BMS' is of format 'urn:oasis:names:tc:SAML:2.0:nameid-format:entity' and its value is not a valid URI.

**Comment by explunit** [comment]
I don't know the exact answer to this but I would guess it's coming from deeper inside Windows Identity Foundation (WIF) and not the AuthServices code. WIF is more strict than some other software about validating that certain types parse as URI and not just strings.

You might try to get the Idp to give you a different nameidentifier format such as "persistent" by specifying it in the NameIdPolicy: https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md#format-attribute

See also: http://stackoverflow.com/questions/11693297/what-are-the-different-nameid-format-used-for

Again, sorry I don't know the exact answer but perhaps this will set you in the right direction.

**Comment by AndersAbel** [comment]
Somewhere in the SAML message you have an identifier "BMS" that is specified to be of format `urn:oasis:names:tc:SAML:2.0:nameid-format:entity`. It's probably in the issuer field, which implicitly has that format. It could also be a Subject NameIdentifier with an explicit format. Either way, "BMS" violates the rules of the `...entity` format. It has to bee an absolut URI per the SAML specification. AuthServices/WIF is one of the few libraries that enforces this so there are many misconfigured Idps out there with invalid entity ids.

**Comment by rgs2007** [comment]
I have this Idp where the entity is not a URI and I just finished developing my application using kentor. Is there any solution in this case besides changing the Idp Entity?

**Comment by AndersAbel** [comment]
@rgs2007  No, System.IdentityModel that AuthServices uses internally enforces the rule in the standard that the entity id need to be an absolute URI.

**Comment by rgs2007** [comment]
Is it possible to change my version of the AuthServices in order to make the name to look like a URI before setting the System. Model? Do you think it would work? Can you tell where to find this piece of the code?

**Comment by AndersAbel** [comment]
@rgs2007 You would have to do it in Saml2Response. After the signature validation, but before `handler.CreateClaims`.

It's doable, but I would really, really recommend you to get the Idp to change to a URI EntityId as that's the standard.

**Comment by mrfatgoat** [comment]
@AndersAbel I'm having this exact problem right now and the IdP isn't willing to fix their end.  Can you elaborate a bit on how to do the workaround you're talking about.  It may be my only option, unfortunately.

**Comment by AndersAbel** [comment]
@mrfatgoat This pops up repeatedly, reopening issue. I'm currently doing work on moving away from System.IdentityModel to use the new Microsoft.IdentityModel nuget package that is planned. This is part of the effort to make the library compatible with ASP.NET Core. I'm opening an issue in their repo to see if they would be willing to add a compatibility setting/option.

**Comment by mrfatgoat** [comment]
@AndersAbel Thanks for the update.  I'll be attempting a roll to the aspnetcore branch of AuthServices soon.  Eager to see how it goes and to contribute if I can.

**Comment by AndersAbel** [comment]
@mrfatgoat Microsoft accepted my suggestion, so when the .NET Core version of the library is made public (it's still under private development) this will be fixed.

**Comment by mrfatgoat** [comment]
@AndersAbel Great news!  Thanks for the update and for bringing this to their attention.  I'll keep an eye out for changes.

**Comment by aaronlcope** [comment]
Until MSFT responds, is there anything we can do or you can do to allow and issuer's nameid-format of "entity" to ignore non-URI values. I know this is against the SAML spec, but a significant # of large US industry corporations have not caught up yet to the spec, where this was previously allowed before. MSFT is adapting, likely b/c of Oracle. Oracle has some web-based software that sets up SAML SSOs, and it produces non-URI data but decorates it in an issuer's nameid-format of "entity", still. These large industry corporations are not able to or are unwilling to change their configuration, as it will cause major breakage for them.

**Comment by AndersAbel** [comment]
@aaronlcope There's nothing to be done on the current version. The netstandard branch in this repo contains a preview that works with the new packages, that doesn't enforce the entity id to be an absolute URI.
