### ISSUE TITLE
How to programically configure sso settings  using kentor

### ISSUE THREAD

**Issue by sajithtgs** [Sustainsys/Saml2#579]
Hi,
I need to do  sso in generic way. Currently we have configured every thing inside the web.config.
how can we programmatically configure it using Kentor.AuthServices.HttpModule.

I am using the below code inside Saml2AuthenticationModule.cs in  HttpModule.

  if (application.Request != null)
            {
     

                System.IdentityModel.Metadata.EntityId eid = new System.IdentityModel.Metadata.EntityId();
                eid.Id = "http://localhost:17009/SamplePath/AuthServices";
                Uri url = new Uri("http://localhost:51204/WebForm1.aspx");

                SPOptions sp = new SPOptions();
                sp.AuthenticateRequestSigningBehavior = SigningBehavior.Always;
                sp.EntityId = eid;
                sp.ReturnUrl = url;

                Kentor.AuthServices.Configuration.Options op = new Options(sp);

                Kentor.AuthServices.ServiceCertificate se = new Kentor.AuthServices.ServiceCertificate();

                se.Certificate = new X509Certificate2("/StubIdp.pfx");
                se.Use = Kentor.AuthServices.CertificateUse.Signing;
                sp.ServiceCertificates.Add(se);

            

                Kentor.AuthServices.IdentityProvider idp = new Kentor.AuthServices.IdentityProvider(new System.IdentityModel.Metadata.EntityId("http://stubidp.kentor.se/Metadata"), sp);
                idp.Binding = Saml2BindingType.HttpRedirect;
                idp.AllowUnsolicitedAuthnResponse = true;
                idp.SingleSignOnServiceUrl = new Uri("http://stubidp.kentor.se/");
                idp.LoadMetadata = true;

                op.IdentityProviders.Add(idp);
                Options = op;

            }

**Comment by msekkappan** [comment]
This works, how do you add provider certificate to this?

**Comment by AndersAbel** [comment]
@msekkappan idp.SigningKeys.AddConfiguredKey(...)

**Comment by msekkappan** [comment]
The behavior is different with Sustainsys.Saml2.AspNetCore2, there is no SigningKeys.
