### ISSUE TITLE
RequestAbstractType.Extensions element

### ISSUE THREAD

**Issue by alexw66-github** [Sustainsys/Saml2#598]
Just a question/feature request:

The spec allows for an "Extensions" element to be sent as part of the request message (defined under the complex type "RequestAbstractType", section 3.2.1). Is there currently a way to add these? 

(My IdP has some additional contextual information that needs to be included.)

**Comment by AndersAbel** [comment]
No, it's currently not supported. Adding it can be done by adding an Extensions XElement property on the Saml2RequestBase class. Then the ToXNodes method should be extended to include the extensions, if the node is non-empty.

The user would have to use the AuthenticateRequestCreated callback to add content to the extensions.

Don't forget tests.

**Comment by Wilsonmg** [comment]
Hi,
I also need this feature to send some data per request (Third-Party Requests). How is it going? :) have you planned when to merge it? :)

**Comment by alexw66-github** [comment]
I did submit pull request #600, but don't think it's been reviewed/merged yet.

**Comment by wilsonmontalvo** [comment]
@alexw66-github , @AndersAbel I'm wondering when is this feature be available?
Regards.

**Comment by AndersAbel** [comment]
When I have time... can't promise anything right now. There's a lot of pull requests in the queue and I have to prioritise paid work.

**Comment by wilsonmontalvo** [comment]
Sure, ok.

**Comment by bgirts** [comment]
I am wondering what happened to this nice feature?  Is there any practical reason not to include it?

**Comment by AndersAbel** [comment]
@bgirts The only reason that it's not reviewed/merged is lack of time. If you want a particular feature prioritzed, please consider sponsoring the work to merge it. Mail me at anders@sustainsys.com if you want to discuss that.
