### ISSUE TITLE
Single sign out saml returns Partial Logout

### ISSUE THREAD

**Issue by rajsekharr83** [Sustainsys/Saml2#610]
Hi,
  I was trying to implement Single sign out using kentor and the IDP is ADFS.
I have  two asp.net apps, when i signed in to app 1 it will sign in to both app1 and app2, means app2 wont ask for credentials, but when i click signout from app1 it will signs out only from that app. and in app2 user remains signed in, what is issue? how to sign out form both the apps when signed out from any one app?

SAML logout Resonse we got from Kentor:
```
<samlp:LogoutResponse ID="_5f1f1af9-5dae-4349-8b14-a0c58c3e95e2" Version="2.0"
 IssueInstant="2016-12-10T20:39:20.098Z" Destination="https://appdev.com/AuthServices/Logout" 
Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="id1571de3a32fd4eabafc5f352b4434a7d" 
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://ITDEV01.app.com/adfs/services/trust</Issuer>
<samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:PartialLogout" />
</samlp:StatusCode></samlp:Status></samlp:LogoutResponse>

```

**Comment by albinsunnanbo** [comment]
The logout response is not signed.
It has to be according to specification and AuthServices will throw an exception.
You should have got an exception somewhere.

If you still have trouble it would be helpful if you posted the full chain of `<LogutRequest>` and `<LogoutResponse>` from both applications and the IDP to make it easier to follow where the logout chain broke.

**Comment by rajsekharr83** [comment]
Thank you very much albinsunnanbo.
i didn't get any exception in my code. But return the above response.
I have service certificate configured for single sign out in application side and configured the public key certificate in ADFS. How can i check the exception please?

**Comment by albinsunnanbo** [comment]
What flavor of AuthServices do you use? Http module, MVC or OWIN?
Exception handling is different. But typically your application will crash with the famous yellow screen of death if you get an exception. Otherwise you'll already handle the exception somewhere.

But, please read the Troubleshooting section on https://github.com/KentorIT/authservices and try to log all SAML2 messages to see if the logout chain breaks somewhere unexcpectedly.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
