### ISSUE TITLE
Generate certifcate for Single Logout

### ISSUE THREAD

**Issue by jaideepvr** [Sustainsys/Saml2#618]
Hi,

We have implemented Single SignOn with Okta and Kentor AuthServices adapter for our application. Now we are in the process of implementing Single Logout. I am aware that we need to sign our Single Logout requests for SP initiated requests and also upload a certificate in Okta for enabling SLO.

I am not knowledgeable in certificates and I would like to what certificates are these and how do I generate them?

Any help or direction is really appreciated.

Thanks
Jaideep

**Comment by albinsunnanbo** [comment]
Just about any certificate with a private key should work fine.
You could create a self signed certificate: http://windowsitpro.com/blog/creating-self-signed-certificates-powershell

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
