### ISSUE TITLE
Silverlight Application

### ISSUE THREAD

**Issue by sugapirapagaran** [Sustainsys/Saml2#655]
Hi,
Can we use Kentor Authservices with Silverlight application?? (using RIA Service??)

Thanks

**Comment by AndersAbel** [comment]
It's probably possible, but would require some design thought as AuthServices would have to run on the server side, creating a session that is then used by the SilverLight application in it's calls to the RIA service.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
