### ISSUE TITLE
Possible lock contention issue in IdentityProvider.DoLoadMetadata()

### ISSUE THREAD

**Issue by mrquantize** [Sustainsys/Saml2#658]
We are running an Azure App Service website, using the stub IDP (http://stubidp.kentor.se/) to simulate mock logins.

Very frequently, the site becomes unresponsive or extremely slow (>2 mins request time). Through the Kudu profiler, I have traced the issue to the `IdentityProvider.DoLoadMetadata()` method (screenshot attached; I can send through the original .diagsession files, but this would need to be via a more secure means due to the sensitivity of the data)

<img width="1127" alt="profiler" src="https://cloud.githubusercontent.com/assets/11027486/23700788/f52da53c-03eb-11e7-97b9-64f2b446c3ff.png">

![image](https://cloud.githubusercontent.com/assets/11027486/23700839/26b00c12-03ec-11e7-8150-3f9d011bfbd3.png)

It seems there is a lock around the whole body of `DoLoadMetadata()`. The majority of threads seem to be stuck outside this lock, since the main work happens in clr.dll according to the trace.

I am not sure what is causing the slowness within the lock, as we are using a local metadata file (stored in the `/App_Data` directory). Possibly, while loading metadata, it is calling out to one of the http://stubidp.kentor.se/ URLs, and this is causing slowness. Or maybe it is some other kind of deadlocking issue.

We do not have this problem when running the web application with the real IDP, nor when running locally.

Please let me know if you require any further information (especially the .diagsession files).

**Comment by AndersAbel** [comment]
I've haven't heard about this before, but it looks like something bad is happening.

Can you provide a bit more details about how your configuration is done? Specifically, do you instantiate multiple IdentityProvider objects or just a single one? What's the cacheDuration and validUntil values in the metadata file?

**Comment by mrquantize** [comment]
Hi Anders, thanks for the prompt reply.

Your mention of `validUntil` was a great clue - we were actually storing the stub IDP metadata file in our `App_Data` directory, as mentioned in the original post, but crucially this meant that the validUntil value never changed. Our real IDP provider's metadata does _not_ have a `validUntil` value, hence we are able to store that statically within the application quite safely.

Presumably, the stale `validUntil` value meant that the website was continually refreshing the metadata, which is not normal behaviour.

Now that I have pointed the metadata to the URL (i.e. http://stubidp.kentor.se/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Metadata) rather than the local file, the issue should be solved. I will update in due course if it is not!

Again, thanks for your response, and if you need any more info from me, please do not hesitate to ask.

**Comment by AndersAbel** [comment]
Yes, that would explain it. If validUntil has already passed, the metadata reloader would try to refresh before doing any kind of operation on the Idp. Closing the issue as I consider it solved. Feel free to reopen if it isn't solved after you've tried the updated version.

**Comment by albinsunnanbo** [comment]
A quick look at the code says that it is still a slight problem.
If you have high load on Authservices and metadata loading is somewhat slow all calls to `ReloadMetadataIfRequired` between the point in time when the metadata expires until one of the `DoLoadMetadata` calls has completed will queue up their own loading of the metadata.

To prevent this you could either move `lock (metadataLoadLock)` in `ReloadMetadataIfRequired` outside the `if` statement or create some fancy signalling/locking inside `DoLoadMetadata` to make sure concurrent calls to `DoLoadMetadata` only results in one actual load request.

**Comment by AndersAbel** [comment]
Thanks @albinsunnanbo for being such a pain and finding the race condition. Reopening issue.

**Comment by ghanashyaml** [comment]
I use locking/signalling using a combo of Monitor and ManualResetEvent (or
Slim version) as I have come across multiple of such cases where lock is
not optimal way of doing it. This is in general and not specific to
KentonIT/authservices.
