### ISSUE TITLE
when i login to web sites directly without okta it redirected to okta login after login i am getting below error

### ISSUE THREAD

**Issue by abilash1205** [Sustainsys/Saml2#728]
Received message contains unexpected InResponseTo "id3b8c812826d14aee81ad0c567c6219b3". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost

**Comment by abilash1205** [comment]
When login undefined User.Identity.IsAuthenticated

**Comment by AndersAbel** [comment]
What API package are you using? MVC, Owin or HttpModule?

**Comment by TIN-123** [comment]
I have the same issue. I am using HttpModule

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
