### ISSUE TITLE
Remote certificate considered invalid

### ISSUE THREAD

**Issue by LoicLopes** [Sustainsys/Saml2#732]
As I had an issue with the parameter returnURL, I tried to upgrade from 0.19.0 to the last version (0.21.2), but I now have an issue when I try to authenticate. I'm using KentorIT.AuthServices.MVC. I got the following error:

![image](https://cloud.githubusercontent.com/assets/450826/26243391/fc276246-3c8b-11e7-8d44-cd3fb9b76938.png)

I tried to use different certificates, but I always have the same problem.

I have the line Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures(); in Global.asax.cs as it was previously necessary.

I had no problem with the 0.19.0 version.

**Comment by AndersAbel** [comment]
The server doesn't trust the https certificate of the idp when loading metadata. To diagnose, log in interactively on the server (if you have access) and open the IDPs metadata in a browser. You'll probably get a certificate warning that can show what's wrong.

**Comment by LoicLopes** [comment]
Thanks for the answer.
I installed the certificate in the Trusted Root Certification Authorities store of the server but I still get the same error (but I do not have a warning anymore when I open the IPD metadata in a browser).
Is it a new check which was added in 0.20.0? Because I have the problem only with version >= 0.20.0.

**Comment by AndersAbel** [comment]
No, this is not a new check. There are no recent changes in that part of the code. If you revert to < 0.20.0 does the problem go away?

When you added the certificate to the Trusted Root store, did you do that for the store for "current user account" or for "local machine"? The IIS process only reads the latter. If you add it to current user store you make the problem go away when logged in as your user, but not for the web process.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
