### ISSUE TITLE
Kentor and Mono

### ISSUE THREAD

**Issue by SbGibson** [Sustainsys/Saml2#739]
Someone used Kentor AuthServices in Mono?
With the same basic configuration used in Windows I obtain a generic:
`System.TypeInitializationException: The type initializer for 'Kentor.AuthServices.HttpModule.Saml2AuthenticationModule' threw an exception. ---> System.TypeLoadException: Could not load type 'Kentor.AuthServices.Configuration.KentorAuthServicesSection' from assembly 'Kentor.AuthServices, Version=0.19.0.0, Culture=neutral, PublicKeyToken=null'.`

Can't understand why. Everything seems ok, I checked version, assembly loading, naming etc.

**Comment by AndersAbel** [comment]
I haven't heard of anyone running AuthServices on Mono, but people are doing a lot of (to me) unexpected things with AuthServices.

I have no idea why the type fails to load. If you figure out what's wrong, please comment back here to help if anyone else runs into the same issue.

**Comment by justinSelf** [comment]
Looks like Kentor is dependent upon classes that haven't been implemented in Mono yet.

**Comment by AndersAbel** [comment]
@justinSelf What is your scenario for wanting this to run in Mono? If you want to run it on Linux, would .NET Core be an option?

**Comment by justinSelf** [comment]
Core isn't an option for our scenario, yet. We aren't running production mono, but many of our devs use Rider+MacOS+Mono. For now, I've just disabled SAML auth if the platform isn't windows.

**Comment by AndersAbel** [comment]
I'm working on a version for .NET Core, which will eventually be targeted to .Net Standard. Then Mono should work.
