### ISSUE TITLE
Logout problem when having two idps

### ISSUE THREAD

**Issue by LukeeK** [Sustainsys/Saml2#749]
Hello,
in my scenario I have two idps, in test environment I am using our test adfs and http://stubidp.kentor.se as second idp. I am adding saml authentication to web form app with using owin package. To login I am using links =>"./Internal/SignIn?idp=..." and "./Externall/SignIn?idp=...". To logout I am calling context.Authentication.SignOut(). Each idp has its own AuthService (Internal and External)

I am having problem with logging out. Only for the first decalred idp remote logout request is performed, for the second only local. When switch the order of declaration result is also reversed. I can put my config if needed. Any ideas on that ? 

I had a feeling it may be related with this (also wrote there) [#515](https://github.com/KentorIT/authservices/issues/515)

**Comment by AndersAbel** [comment]
I would need some more logs/info to be able to understand what's happening here. Can you please enable the logging and post the log?

**Comment by LukeeK** [comment]
Hi, thanks for response :) , I will try to put some code and more info next days

**Comment by LukeeK** [comment]
Hi, my code from Startup.vb file is below, it is in vb. As I said for the second auth service added(internal in this case) logout is not performed correctly. When try to log again I am automatically redirected back to application without need of putting credentials again.

   Dim returnUrl As String = "https://localhost:44300/"
   Dim publicOrigin As String = "https://localhost:44300"
   Dim externalSamlAuthData = New SamlAuthenticationData With
                 {
                 .IdentityProviderId = "http://stubidp.kentor.se/Metadata",
                 .IdentityProviderCertificateName = "Kentor.AuthServices.StubIdp.cer",
                 .IdentityProviderLoginUrl = "http://stubidp.kentor.se",
                 .IdentityProviderLogoutUrl = "http://stubidp.kentor.se/logout",
                 .IdentityProviderRPIdentifier = "https://localhost:44300/AuthServices",
                 .Name = "External",
                 .SigningPrivateKeyName = "Kentor.AuthServices.Tests.pfx"
                 }
            Dim internalSamlAuthData = New SamlAuthenticationData With
                 {
                 .IdentityProviderId = "http://our.test.adfs/adfs/services/trust",
                 .IdentityProviderCertificateName = "adfs_test.cer",
                 .IdentityProviderLoginUrl = "https://our.test.adfs.adfs/ls/idpinitiatedSignon.aspx",
                 .IdentityProviderLogoutUrl = "https://our.test.adfs/adfs/ls/",
                 .IdentityProviderRPIdentifier = "http://samltest.com/adfs",
                 .Name = "Internal",
                 .SigningPrivateKeyName = "Kentor.AuthServices.Test3.pfx"
                 }
            app.UseCookieAuthentication(New CookieAuthenticationOptions() With
            {
                .AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                .LoginPath = New PathString("/Account/LoginProviderPicker.aspx")
            })
            app.SetDefaultSignInAsAuthenticationType(DefaultAuthenticationTypes.ApplicationCookie)
            app.UseKentorAuthServicesAuthentication(CreateAuthServicesOptions(externalSamlAuthData, returnUrl, publicOrigin))
            app.UseKentorAuthServicesAuthentication(CreateAuthServicesOptions(internalSamlAuthData, returnUrl, publicOrigin))


            app.Map("/Account/Logout.aspx",
                Sub(map)
                    map.Run(Function(ctx)
                                If ctx.Authentication.User.Identity.IsAuthenticated() Then
                                    ctx.Authentication.SignOut()
                                Else
                                    ctx.Response.Redirect("/Account/LoginPickerProvider.aspx")
                                End If
                                Return Task.FromResult(0)
                            End Function)
                End Sub)
  Private Shared Function CreateAuthServicesOptions(ByRef configData As SamlAuthenticationData, ByVal returnUrl As String, ByVal publicOrigin As String) As KentorAuthServicesAuthenticationOptions
        Dim spOptions = CreateSPOptions(configData, returnUrl, publicOrigin)
        Dim entityId = New EntityId(configData.IdentityProviderId)
        Dim idp = New IdentityProvider(entityId, spOptions) With
                {
                    .Binding = Saml2BindingType.HttpPost,
                    .SingleSignOnServiceUrl = New Uri(configData.IdentityProviderLoginUrl),
                    .SingleLogoutServiceUrl = New Uri(configData.IdentityProviderLogoutUrl)
                    }
        Debug.WriteLine("idp " + configData.IdentityProviderLogoutUrl)


        idp.SigningKeys.AddConfiguredKey(
                New X509Certificate2(
                    HostingEnvironment.MapPath(
                        "~/App_Data/" + configData.IdentityProviderCertificateName)))
        Debug.WriteLine(configData.IdentityProviderCertificateName)

        Dim authServicesOptions = New KentorAuthServicesAuthenticationOptions(False) With
            {
                .AuthenticationType = configData.Name,
                .Caption = configData.Name,
                .SPOptions = spOptions
            }

        authServicesOptions.IdentityProviders.Add(idp)
        Return authServicesOptions
    End Function


    Private Shared Function CreateSPOptions(ByRef configData As SamlAuthenticationData, ByVal returnUrl As String, ByVal publicOrigin As String) As SPOptions

        Dim spOptions = New SPOptions With
            {
                .EntityId = New EntityId(configData.IdentityProviderRPIdentifier),
                .ReturnUrl = New Uri(returnUrl, UriKind.RelativeOrAbsolute),
                .PublicOrigin = New Uri(publicOrigin),
                .ModulePath = configData.Name
        }
        spOptions.ServiceCertificates.Add(New X509Certificate2(
                AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "/App_Data/" + configData.SigningPrivateKeyName))
        Debug.WriteLine(configData.SigningPrivateKeyName)
        Return spOptions
    End Function

Public Class SamlAuthenticationData
    Property IdentityProviderId As String
    Property IdentityProviderRPIdentifier As String
    Property IdentityProviderLoginUrl As String
    Property IdentityProviderLogoutUrl As String
    Property Name As String
    Property IdentityProviderCertificateName As String
    Property SigningPrivateKeyName As String
End Class

**Log in is started pressing cetain links :
../Internal/SignIn?idp= http://our.test.adfs/adfs/services/trust
../External/SignIn?idp= http://stubidp.kentor.se/Metadata

Output when doing log out from the second added auth service:**
Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware Verbose: 0 : Expanded AuthServicesUrl
  AssertionConsumerServiceUrl: https://localhost:44300/Internal/Acs
  SignInUrl: https://localhost:44300/Internal/SignIn
  LogoutUrl: https://localhost:44300/Internal/Logout
  ApplicationUrl: https://localhost:44300/
Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware Verbose: 0 : Initiating logout, checking requirements for federated logout
  Issuer of LogoutNameIdentifier claim (should be Idp entity id): http://our.test.adfs/adfs/services/trust
  Issuer is a known Idp: True
  Session index claim (should have a value): http://kentor.se/AuthServices/SessionIndex: _58e53124-5426-49b8-bebb-6a740dd979b6
  Idp has SingleLogoutServiceUrl: https://our.test.adfs//adfs/ls/
  There is a signingCertificate in SPOptions: True
  Idp configured to DisableOutboundLogoutRequests (should be false): False
Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware Information: 0 : Sending logout request to http://our.test.adfs//adfs/services/trust
Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware Verbose: 0 : Expanded AuthServicesUrl
  AssertionConsumerServiceUrl: https://localhost:44300/External/Acs
  SignInUrl: https://localhost:44300/External/SignIn
  LogoutUrl: https://localhost:44300/External/Logout
  ApplicationUrl: https://localhost:44300/
Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware Verbose: 0 : Initiating logout, checking requirements for federated logout
  Issuer of LogoutNameIdentifier claim (should be Idp entity id): http://our.test.adfs//adfs/services/trust
  Issuer is a known Idp: False
  Session index claim (should have a value): http://kentor.se/AuthServices/SessionIndex: _58e53124-5426-49b8-bebb-6a740dd979b6
  Idp has SingleLogoutServiceUrl: 
  There is a signingCertificate in SPOptions: True
  Idp configured to DisableOutboundLogoutRequests (should be false): 
Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware Information: 0 : Doing a local only logout.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.

**Comment by arthurmmedeiros** [comment]
I think this is the same problem I'm facing here. 

In the documentation it says "If you are using Single Logout, you need to make sure that the claims containing the Saml2 logout information are present in the returned identity. The types of the claims are available in Saml2ClaimTypes.SessionIndex and Saml2ClaimTypes.LogoutNameIdentifier."

After downloading the source code I was able to understand that this message "Federated logout not possible, redirecting to post-logout" happens exactly because it's missing thos claims. However, I don't understand how and where I should add them.

I'm using the asp net core version
