### ISSUE TITLE
No way to override or set AssertionConsumerService(ACS) URL

### ISSUE THREAD

**Issue by iamvips** [Sustainsys/Saml2#762]
I am unable to set/override the ACS Url while sending an Authentication request in our .net application. Could anyone please guide us through?

**Comment by avatart0ph** [comment]
did you figure this out? i dont need to change the acs url. but i need to change the index
anyway, i read you have to change PublicOrigin property but that didnt work for me.
for example if i set it to http://localhost:50975/public-origin/saml, the destination in the saml response is
Destination="http://localhost:50975/public-origin/saml/AuthServices/Acs"

...if you look at the code, Acs is hardcoded. so i dont think this is possible. i just changed my idp to use AuthServices/Acs instead.

**Comment by iamvips** [comment]
@avatart0ph Thank you for your help this has been resolved.
