### ISSUE TITLE
Kentor not finding return URL

### ISSUE THREAD

**Issue by FerdyHoefakker** [Sustainsys/Saml2#763]
Hi,

I'm trying to set-up an SSO using Kentor and am running into a strange issue. When trying to log in to the IDP, this is successful. However, upon being redirected to my application, Kentor throws an error because it claims the return url was not configured. I put a watch on `CommandFactory.GetCommand(CommandFactory.AcsCommandName)` to see its result and there's 2 properties filled:

1. SpInitiatedMissingReturnUrl
2. UnsolicitedMissingReturnUrlMessage

The text in these is 

> Successfully received and validated response from Idp, but don't know
where to redirect now. There was no return url specified when initiating
the request and there is no default return url configured.

>When initiating a request, pass a ReturnUrl query parameter (case matters) or 
use the RedirectUri AuthenticationProperty for owin. Or add a default ReturnUrl
in the configuration.

and 

> Unsolicited SAML response received, but no ReturnUrl is configured.

>When receiving unsolicited SAML responses (i.e. IDP initiated login),
AuthServices will redirect the client to the configured ReturnUrl after
successful authentication, but it is not configured.

>In code-based config, add a ReturnUrl by setting the
options.SpOptions.ReturnUrl property. In the config file, set the returnUrl
attribute of the <kentor.authServices> element.

When checking the Options.SPOptions however, I can clearly see that the ReturnUrl property has a (correct) value. I've set up an SSO for other sites using the same settings (but with different URLs obviously) and it always worked without a hitch. What am I missing here?

Kind regards,

Ferdy

**Comment by explunit** [comment]
I can't think of anything obvious that would be causing this. Are you able to reproduce the problem by using a similar configuration in any of the sample projects? Also, which mode are you using (OWIN, MVC, or HttpModule)?

**Comment by FerdyHoefakker** [comment]
Hi, 

I have not been able to reproduce the problem on any of the other projects, but the problem seems to be fixed now. I threw out all the (related) DLLs, recompiled the project and cleared all the (related) temp files. 

-Ferdy

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
