### ISSUE TITLE
Return Url is Ignored when Configuring via Code

### ISSUE THREAD

**Issue by christopherbauer** [Sustainsys/Saml2#773]
I have a multi-tenant environment that requires we keep our IDP configuration in a database and load it at App_Start for use throughout the day. To facilitate SSO, we've created an MVC controller "SingleSignOn" with actions:

- SSO() - Uses the Url host to determine which single sign on method to use, which includes a "SingleSignOnId" which is passed forward. When determined, redirects to the appropriate Action Method (currently we only support SAML20)
- Saml20(int singleSignOnId) - Requests IDP info (per the SingleSignOnID), constructs the kentor options with the ConsumeSaml20Response as the return uri, and sends the request using SignInCommand
- ConsumeSaml20Response() - Consumes the Saml2 message and performs credential mapping to the login stored in the platform, then redirects to our login pages

Despite configuring SPOptions.ReturnUrl to be my custom ConsumeSaml2Response URI, it keeps getting ignored and instead uses /{ModulePath}/Acs. I tracked it down to to the SignInCommand.cs.

It seems that the SPOptions return Url is not used, ever, in the SignInCommand when sending the request to the IDP, instead it constructs the url based on finding the returnUrl in the request data which I assumed is loaded normally if you use Web.config configuration.

~~I think that a line inserted between line 41 and 42 of SignInCommand.cs essentially performing:~~

~~`if(string.IsNullOrEmpty(str) && options != null && !string.IsNullOrEmpty(option.SPOptions.ReturnUrl)) { str = option.SPOptions.ReturnUrl; }`~~

~~Would fix this issue, but I suspect I might also be misunderstanding some core functionality here.~~

**Comment by christopherbauer** [comment]
Actually, I see now that it's a problem at line 61: AuthservicesUrls, which ignores the configuration and always inits the AssertionConsumerServiceUrl to be ModulePath/Acs. Is there a way around this?

**Comment by AndersAbel** [comment]
The idea with AuthServices is that it will extract the recevied SAML response and validate it for you. That's why it always sets the response to /{ModulePath}/Acs. After the SAML response is processed, the Acs command will redirect to the return url.

You shouldn't make your own ConsumeSaml20Response method, use one of the existing API modules (Kentor.AuthServices.HttpModule, Kentor.AuthServices.Mvc or Kentor.AuthServices.Owin).

And the AuthServicesUrl initialization works perfectly fine in a multi tenant environment. It will create the URLs based on the request URL so with different domains it will create different URLs.

**Comment by christopherbauer** [comment]
Sorry, my ConsumeSAML20Response method is just what I named it in the back end so that my coworkers (who know very little about SSO) would be able to understand what the "Acs" action was for. I will use a Route attribute to complete the redirect to "/Acs" as outlined here.

I had difficulty finding additional information on how to extract the information from the response after a redirect occurs, which is why I am trying to perform my credential mapping in the /Acs method. I'll try a deeper dive into the examples because I must have missed something.

**Comment by leotohill** [comment]
@christopherbauer , did you figure out how to extract information at the end? My situation is similar to yours.  Afaict, no contextual information is available to the final response, at returnurl.  

@AndersAbel you say that multi-tenant should be fine but you seem to be assuming that the tenant id would be part of the url path.  In my case it is a url parameter.

**Comment by christopherbauer** [comment]
@leotohill I have a working implementation but per above it's not ideal. I can send you the code if you want but I wouldn't want to make it public as I don't seem to be understanding the nuances of kentor.

**Comment by leotohill** [comment]
I don't see a way to contact you privately. Would you write to me at my name at gmail.com ? Thanks

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
