### ISSUE TITLE
Different SignatureMethod and DigestMethod

### ISSUE THREAD

**Issue by janobrestad** [Sustainsys/Saml2#777]
I have a saml response that have sha-256 as the signature method and sha-1 as the digest method. 

`<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />`
`<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />`

Authservices gets the mininumDigestAlgorithm based on the signing algorithm in `GetCorrespondingDigestAlgorithm`. 

Is this a valid combination of algortihms according to the standard? 

Is there a way I can make my meta-data explicitly ask for sha-256 as the digest method?

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
