### ISSUE TITLE
How to turn existing ASP.NET MVC project (using ASP.NET Identity) into SAML identity provider?

### ISSUE THREAD

**Issue by asilverstein** [Sustainsys/Saml2#778]
I've read the configuration document, reviewed some of the source code, test-ran all the projects in the solution in VS, and I still have no idea how I would use this code to turn my existing ASP.NET MVC application into a SAML identity provider (the SAML service provider that we want to communicate with already exists). Any help would be great. I have the certificates generated and ready to use.

**Comment by explunit** [comment]
AuthServices is designed primarily for the service provider/relying party side of the SAML protocol. While there is a "Stub" IDP and some underlying protocol classes, quite a bit of work would be needed to turn it into a production-ready IDP.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
