### ISSUE TITLE
AuthServices IdP Initiated Request

### ISSUE THREAD

**Issue by carl6885** [Sustainsys/Saml2#779]
Hi 

Apologies if this is the wrong forum for this but I am trying to implement iDp initiated login using IdentityServer and AuthService stub iDp - SP works fine.

Every time I do it I just see the login screen. Reviewing the logs has helped, I can see that it is parsing the SAML response and claims to authenticate the user however when it redirects to my site to the redirect to IdSrv it suggests the user isn't authenticated and then loads the logon screen - not sure if its a bug or my configuration issue....

------ section of log -----

2017-08-17 21:31:10,297 [18] INFO  Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware - Successfully processed SAML response id891d5ac12bd84d9c8d7271ecaac74812 and authenticated carl.law@nysgroup.com
2017-08-17 21:31:13,814 [18] DEBUG HTTP Logging - HTTP Request
{
  "Method": "GET",
  "Url": "https://localhost:44384/connect/authorize?client_id=imrm_web&response_type=id_token+token&scope=openid+profile+roles+api&redirect_uri=http%3A%2F%2Flocalhost%3A4694&state=649b11dfc59a4ca29d0268d20314862f&nonce=149e96f976104ae08f0e0086a740ae7b&acr_values=idpokta&response_mode=form_post",
  "Headers": {
    "Cache-Control": [
      "no-cache"
    ],
    "Connection": [
      "close"
    ],
    "Accept": [
      "text/html, application/xhtml+xml, image/jxr, */*"
    ],
    "Accept-Encoding": [
      "gzip, deflate"
    ],
    "Accept-Language": [
      "en-GB"
    ],
    "Cookie": [
      "_ga=GA1.1.894368044.1500476143; stubIdp.username=carl.law@nysgroup.com; idsrv.external=62MEmOtD0oxuTDgNwoJkEuHszuouWREErAXA40o_Bi_a0AIH6iFFn0_j8gh19_iKFXseinMr22ym_WYGxG38CBFiQvq5OTnrXncj5Ew3DsCOAoYitdECXu9cUGjSeAFGrwVnvxcJBf63Aeol9BYgdjSui29LdFftBn7vcYJ_9htRTVxDKJ26xKVD5gt9gDHfsg8FRl0hnSpZdoIRHXSXhS8HKcvyWhrffl63dzW2PMLeRFNBaPYfzm0WddhmCMROSZMUEXlA1I9m6TdCQnrpEM0ZChc8oZbLgElEvWDgn4PlbX0XVlTxqMgKos8ZYSLHSsPt-C45MXJFZJX6p4icYgtXMqt99lKZhpdg6dTWw-O84Ps-Cn49yQ_0f0Feuw8gu3AVCL-mnV09U41P1TXzOktw9dKkDrXLrGv1DU3b42W40c7njSdn1kEobGiEMI9Gnjs9YhcPXFmvYeOp_rCjbf1RU6oTrZjbwvkqQ6D2ANvrlpoeFuMScBBHA1Ln64SXgLwVeL4Gnc8sDQCfeALEluJduxHSP-3Cjhb0xvza9IcjASC1RKVrpQ68WBEdEbmzEqBv_lgL6FHJjUMLId3aBsKrUd7qzbDe9Zjy63IPlAZIqhfxhKSFhIHBAZ4uGkT2mcQtchLHCOFFvPHP2r3O-DtKzK8SxCD5ii3WZEXxKNM; SignInMessage.6245bf64e9d1550661ba1c4358b22cd4=Btz0MSdbNuO29jbJDMGt0nD5rh77eTPOdP48MwCiaoKvVryH6ztL9VjxHjuncBjFfUwjann35HSc0ikj8FnOByVOERDJgyhSA_cbQSXIj1t6I8qAP8635tlnJoYCh6zWRaVO1O_u4zq77tdUEg4-hXPYJ1q9NSEV4DdbkaABllnID5gqEIPey6UlhrwcvuBM6lZlDNbu8sZKjsQq39-7BZkhrjg_lTrm297sdfSaEP1g_xeNEdnqq3R4rFuDuRTciJqMLam4dHmgwFmZkYprZzvFAVSxKNj_6bA-bz5NIyZnPrwxO-qGKFQP6pi2ujFVrYZNzTmo3ehpbk6mBKa_8p6kMYw3yp0o60H4Tz3AUsdh6OsoZRkSaU3gpY4TTORca93qyfQXn0QfBcCD9uMHgc1uWygieFc7KN8mAOMN9yghVp4B0u5xjEWVzQ7fBZGE0Co3AGctvjcpV_-zAUM8TzI9niq1Jbvfwp_X_wTtqt9z-piENKl9OTx1aBvA0jQl0G9KvjDJxo7YQ-D__D9MlYjZ7foraZQsiZO_GW5MC8l_L6J70WSt-vwH6M0-UkNf; idsrv.xsrf=zzDEXCvF8vOMSzGIC1XsODgfTsei3LevSRT6xmN1dz954P2Os_I-juwPR9wFsTtUE3xXT9s2r_Ba4PpoovJHpRfB0Ped63VoCBQFsZjX5TY"
    ],
    "Host": [
      "localhost:44384"
    ],
    "Referer": [
      "http://localhost:52071/"
    ],
    "User-Agent": [
      "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"
    ]
  },
  "Body": ""
}
2017-08-17 21:31:13,817 [18] INFO  IdentityServer3.Core.Endpoints.AuthorizeEndpointController - Start authorize request
2017-08-17 21:31:13,817 [18] INFO  IdentityServer3.Core.Validation.AuthorizeRequestValidator - Start authorize request protocol validation
2017-08-17 21:31:14,216 [23] INFO  IdentityServer3.Core.Validation.AuthorizeRequestValidator - Authorize request validation success
 {
  "ClientId": "imrm_web",
  "ClientName": "IMRM Web App",
  "RedirectUri": "http://localhost:4694",
  "AllowedRedirectUris": [
    "http://localhost:4694",
    "http://localhost:52071"
  ],
  "SubjectId": "unknown",
  "ResponseType": "id_token token",
  "ResponseMode": "form_post",
  "Flow": "Implicit",
  "RequestedScopes": "openid profile roles api",
  "State": "649b11dfc59a4ca29d0268d20314862f",
  "Nonce": "149e96f976104ae08f0e0086a740ae7b",
  "AuthenticationContextReferenceClasses": [
    "idpokta"
  ],
  "Raw": {
    "client_id": "imrm_web",
    "response_type": "id_token token",
    "scope": "openid profile roles api",
    "redirect_uri": "http://localhost:4694",
    "state": "649b11dfc59a4ca29d0268d20314862f",
    "nonce": "149e96f976104ae08f0e0086a740ae7b",
    "acr_values": "idpokta",
    "response_mode": "form_post"
  }
}
2017-08-17 21:31:14,216 [23] INFO  IdentityServer3.Core.ResponseHandling.AuthorizeInteractionResponseGenerator - User is not authenticated. Redirecting to login.
2017-08-17 21:31:14,216 [23] INFO  IdentityServer3.Core.Endpoints.AuthorizeEndpointController - End authorize request
2017-08-17 21:31:14,216 [23] INFO  IdentityServer3.Core.Results.LoginResult - Redirecting to login page

---- end section of log -----

Does anyone have any ideas?

Thanks
Carl

**Comment by AndersAbel** [comment]
Closing as this is an old question that was never answered. Please comment if it is still a problem.
