### ISSUE TITLE
Compatibility setting for authentication context parsing

### ISSUE THREAD

**Issue by explunit** [Sustainsys/Saml2#780]
An issue I've seen frequently is a parsing error when the IDP sends something like this:

```
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>phonefactorPREAUTH/contract</saml:AuthnContextClassRef>
        <saml:AuthnContextDeclRef>phonefactorPREAUTH/contract</saml:AuthnContextDeclRef>
      </saml:AuthnContext>
```
We get error like this:
```
Kentor.AuthServices.Exceptions.BadFormatSamlResponseException: The SAML response contains incorrect XML ---> System.Xml.XmlException: ID0013: The value must be an absolute URI.
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadSimpleUriElement(XmlReader reader, UriKind kind, Boolean allowLaxReading)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadAuthenticationContext(XmlReader reader)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadAuthenticationStatement(XmlReader reader)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadAssertion(XmlReader reader)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadToken(XmlReader reader)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
```

IDP side is often reluctant to fix this, as they consider their response to be conforming with the spec, e.g. see here: https://www.novell.com/support/kb/doc.php?id=7015106

Would it make sense to add a `Compatibility.IgnoreAuthenticationContextInResponse` setting to simply skip parsing of this section?

I believe it would be as simple as overriding `ReadAuthenticationContext` in `Saml2PSecurityTokenHandler` and returning an empty `Saml2AuthenticationContext` based on this new setting.

As far as I can tell, AuthServices does not currently process/verify anything in that section today, but by doing it as a compatibility setting we would ease the transition if/when AuthServices does process that section.

**Comment by AndersAbel** [comment]
Novell is wrong. While the section they reference in the spec doesn't mention anything about absolute vs relative URIs there's a general clause in the spec at section 1.3.2:

>>>Unless otherwise indicated in this specification, all URI reference values used within SAML-defined elements or attributes MUST consist of at least one non-whitespace character, and are REQUIRED to be absolute [RFC 2396].

But being right/wrong doesn't matter. If an `AuthenticationContextClassRef` i present it will end up as a claim in the generated identity (see [Saml2SecurityTokenHandler source](http://referencesource.microsoft.com/#System.IdentityModel/System/IdentityModel/Tokens/Saml2SecurityTokenHandler.cs,1977)). I think that a compatibility setting as you suggest is a good idea. That way someone that doesn't care/want those values can filter them out.

Overriding `ReadAuthenticationContext` sounds like a good idea.
