### ISSUE TITLE
Any updates on using this with .Net Core fully? I am implementing SAML into my .net core application

### ISSUE THREAD

**Issue by cherokeestewarthart** [Sustainsys/Saml2#782]

**Comment by pulverize** [comment]
I'm interested in this as well.

Even though I'm targeting the .NET framework, which I gathered from the discussion in this project should be supported, I have not been able to integrate this with my Core 2.0 solution. It seems like some of the documentation provided is outdated, which I can get around: KentorAuthServicesAuthenticationOptions has become Kentor.Auth.Configuration.Options, for instance - but crucially there appears to be no app.UseKentorAuthServicesAuthentication and none of the .NET Use*Authentication methods accept a Kentor.Auth.Configuraiton.Options instance.

Integrating with a core project targeting .net core 2.0 is probably a long way off.

**Comment by cherokeestewarthart** [comment]
@pulverize 

Yes I am running into issues trying to authenticate to Salesforce without seeing a user interface. I originally authenticated it using OAuth, but it needs to be without the user interface. I want all of the signing into Salesforce to be done behind the scene with the end user having to do anything. I have been looking into SAML to do this, but it isn't looking too promising right now. 

What technology are you trying to integrate with using SAML ?

**Comment by pulverize** [comment]
I have the same sort of demand for UI-free authintegration (like that @cherokeestewarthart ?). Our in-house web application uses our in-house SAML2 IdP for authentication and the application needs to accept external SSO of the same sort. I'm rewriting the in-house web application which was written in WebForms and trying to make a case for doing so with .NET Core 2.0. I agree, promising would not be the correct term for the immediate future.

Componentspace.SAML2 is looking a little more polished than Kentor and ITFoxtec but it's a tad pricey and I can't quite get the evaluation version's middleware to function. Core unfortunately I think is just a bit immature for my needs. I can't wait until everyone gets on board with it and fleshes out the ecosystem a bit more.

**Comment by AndersAbel** [comment]
Work is under way with a .Net Core version, I'm aiming at a public release before the end of the year.
