### ISSUE TITLE
Transfer and Rename of the project

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#787]
After 8 years at Kentor the time has come for me to [move on](https://coding.abel.nu/2017/09/going-independent/). TLDR; I will bring Kentor.AuthServices over to my new company [Sustainsys](https://sustainsys.com). I will continue to support existing support contracts signed with Kentor and I am open for new support contracts (mail me at anders.abel@sustainsys.com)

As part of the transfer I need to rename the project as I no longer have the right to use the name Kentor.

Naming is one the hardest things in computer science and this case is no different so I want help from the community. If you have a suggestion, please add it as a comment on this issue. Use reactions (thumbs up/down etc) on each suggestion to give an informal vote.

**Comment by AndersAbel** [comment]
My own suggestion is `Sustainsys.Saml2`.

It is simple and explains what it does as well as connecting it with a brand name. When I first created the library I had an idea that it would contain various authentication and authorization helpers - hence the name AuthServices. As it turned out it has become a Saml2-only library, so I think using that as a name is a better fit.

**Comment by dahlsailrunner** [comment]
Congrats on arriving at your decision!  Name sounds fine to me -- I just wanted to reiterate that I would be totally willing to help get docs for the new library set up if you still would like the help.  I've been spending some time with ReadTheDocs lately and really like the platform.  If you're interested in the help / support on this, just let me know.  And you have my +1 vote for your name suggestion above.  Simple and self-explanatory!

**Comment by woric** [comment]
Naming is always hard, it's a bitch, and often dependant on luck, and changing a name is always problematic. 

If staying with the existing name is not an option, then choose something that people will associate with the project. 

I suggest Abel.Saml2 or Anders.Saml2

**Comment by MartijnKooij** [comment]
Congrats on the new phase in your life.

Not sure if branding should be part of the product name (even when it is a very sustainable brand name ;) ). Since we are posting suggestions I would say something more general such as SAML2.net.

**Comment by ghanashyaml** [comment]
Congratulations for your new job!

I would think its best to not associate the project with your employer name
since you are sharing it with the community. If you are working on it as
part of your employer's payroll time, then it would make sense. Otherwise,
I would recommend to rename it to something generic Saml2.Net.

**Comment by AndersAbel** [comment]
Thanks for your comments and encouragement.
@woric Thanks for putting that level of confidence in my name, but I don't really like the idea to have my own name. Can't say why, but it feels a bit wrong.
@MartijnKooij Saml2.net is simple, but I think it's a bit too generic. There are other similar projects (e.g. https://github.com/i8beef/SAML2) so I prefer a more distinct name.
@ghanashyaml Sustainsys is actually my own company, with just me employed (so far). Working on this project will be a core part of my business, so I think it makes sense to use the Sustainsys name.

So, I've settled for *Sustainsys.Saml2*.

The repository is already transferred to the Sustainsys GitHub account. The roadmap ahead is:
* Release of an asp.net core 2 service. It will have the Sustainsys name from the start.
* Wrap-up of all loose ends (pull requests) under the current name. Don't want to have dangling PRs when doing a large code renaming.
* Final feature release under the `Kentor.AuthServices` name.
* Rename of the repository
* Renaming in the code.
* First release under the `Sustainsys.Saml2` name. Empty `Kentor.AuthServices` packages will also be published that just references the new `Sustainsys.Saml2` packages and shows a readme with info on the transition.

**Comment by AndersAbel** [comment]
@dahlsailrunner Can you please mail me at anders@sustainsys.com if you are still open for helping out on documentation?

**Comment by AndersAbel** [comment]
Reopening this, as the rename as not really taken place yet...

**Comment by AndersAbel** [comment]
Now the rename has actually been carried through in the source and new nuget packages are available. The 0.23.0 release has exactly the same functionality as the 0.22.0 release, only the names differ
