### ISSUE TITLE
Saml2SubjectConfirmationData does not contain a notBefore value

### ISSUE THREAD

**Issue by riccardogozzi** [Sustainsys/Saml2#788]
Hi there
I'm trying to use the Kentor.AuthServices with a SAML SP that requires the NotBefore attribute. Having looked at the ClaimsIdentityExtensions class I can see that a value isn't passed in. Could you please update to include the NotBefore value by default? Don't know if it will impact others?
Kind regards
riccardo

**Comment by AndersAbel** [comment]
This looks like a specific issue to your setup but nothing that is required by a lot of users of the library. If you want I can do it as commercial consulting, but it's nothing I can prioritize otherwise. Mail me at anders@sustainsys.com if you want to discuss options.
