### ISSUE TITLE
Change request: Make all `Kentor.AuthServices.WebSso.*Command` classes public

### ISSUE THREAD

**Issue by mattbrooks2010** [Sustainsys/Saml2#793]
The following `ICommand` implementations are public:

- `Kentor.AuthServices.WebSso.SignInCommand`
- `Kentor.AuthServices.WebSso.LogoutCommand`

The following are not:

- `Kentor.AuthServices.WebSso.AcsCommand`
- `Kentor.AuthServices.WebSso.MetadataCommand`
- `Kentor.AuthServices.WebSso.NotFoundCommand`

Making these implementations of `ICommand` public would be useful for consumers of the `Kentor.AuthServices` package that want to avoid the static `CommandFactory` class.

Would you be receptive to implementing this change request or accepting a PR?

**Comment by AndersAbel** [comment]
I might be positive if there's a good reason. Why isn't `CommandFactory` a viable option for you?

**Comment by mattbrooks2010** [comment]
`CommandFactory.GetCommand` is static and so doesn't lend itself to mocking. If the concrete `ICommand` implementations were public, application code could take a dependency on `ICommand` and concrete instances could be created directly and injected.

**Comment by AndersAbel** [comment]
Ok, so this is a case where you are coding directly against the main Kentor.AuthServices library, without using the HttpModule, Mvc, Owin or AspNetCore2 packages?

That is an advanced scenario, but one I want to support. So I'm positive to making the commands public. Please go ahead with a PR. I don't think tests even make sense in this case (how would you even test it?) so for once there's a code change were I won't be asking for tests.

And thanks for opening the issue to discuss this before submitting a PR, always better to have the discussion before the code is done (even though this is a small change).

**Comment by mattbrooks2010** [comment]
> Ok, so this is a case where you are coding directly against the main Kentor.AuthServices library, without using the HttpModule, Mvc, Owin or AspNetCore2 packages?

Yes, that is correct.

> Please go ahead with a PR.

Thanks, will do.

> I don't think tests even make sense in this case (how would you even test it?) so for once there's a code change were I won't be asking for tests.

Assuming you're referring to unit tests, I agree.

The value of any new tests would be to ensure the classes _remain_ public, as this would be an easy way to break consumers of the `Kentor.AuthServices` package in the future. In my opinion, tests like this are not really suitable in the form of unit tests. It would be much more effective to have an test project in your repo that references the `Kentor.AuthServices` package and creates an instance of each of the classes. Before releasing a new version of the package to NuGet, you would test it out on the test project to ensure you can still compile and also run any other scenarios implemented in the test project. These would be more like end-to-end tests.

I won't implement the test project for this issue. Perhaps it is worth opening another issue for this, if you think my suggestions are valid?

**Comment by AndersAbel** [comment]
Fixed by #831
