### ISSUE TITLE
Logout not called in passive mode/external cookie

### ISSUE THREAD

**Issue by mitsufu** [Sustainsys/Saml2#795]
Hi @AndersAbel,

I've realized I posted this in comment on a closed issue...
Not sure you can see it, so I put here also :)

I've made my first test from your SampleOwinApplication and my Adfs server.

I've configured the Relaying Party from the metadata issued from /AuthServices successfully.
The sample worked directly, Kentor owin extension is passive with ExternalCookie, "KentorAuthServices" appeared on the login page and jumps successfully to the adfs login page. When redirecting back to my service, I had no logininfo in AccountController/ExternalLoginCallback. I've added a custom ClaimsAuthenticationManager implementation and added a correct ClaimTypes.NameIdentifier to the identity based on the incoming claim (upn from adfs).
Then everything went fine in the ExternalLoginCallback and I'm in the end correctly signed on Asp.Net Identities (ApplicationCookie) which is my only identity. Am I right ?
My problem is I don't understand how to call "log off". I tought AuthenticationManager.SignOut("ApplicationCookie", "KentorAuthServices"); would have work.

I've read this up on this discussion but I can't find where to catch those claims during signin and then how to trigger signout:

"Check that you have the AuthServicesClaimTypes.LogoutNameIdentifier and AuthServicesClaimTypes.SessionId. They are generated by AuthServices, but if you have some kind of claims mapping/translation you will need to carry them over to the actual identity used in the session."

I would be very thankful if you could give me some guidance.

Thanks

**Comment by AndersAbel** [comment]
The issue is two month old and I never had time until now to look at it. Closing as inactive, please comment if you still need help.
