### ISSUE TITLE
Error with null StoredRequestState.ReturnUrl

### ISSUE THREAD

**Issue by edleno** [Sustainsys/Saml2#804]
Just pulled down the latest, did the build, but when I test with any of the samples when I select "Sign in - default IDP" it takes me to the discovery service page for the local stubidp.  Is it supposed to do that?  If I run the externally provided stubidp.kentor.se it goes straight to the login page and then everything works.

When I get the discovery service page everything looks to be filled out, so I press "Redirect back to SP" but that fails with a null in the ReturnUrl in StoredRequestState.  

Error output returned on page:
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 84:             if (request.StoredRequestState != null)
Line 85:             {
Line 86:                 returnUrl = request.StoredRequestState.ReturnUrl.OriginalString;
Line 87:             }
Line 88: 
  

 Source File:  C:\Work\authservices2\Kentor.AuthServices\WebSso\SignInCommand.cs    Line:  86 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Kentor.AuthServices.WebSso.SignInCommand.GetReturnUrl(HttpRequestData request, IOptions options) in C:\Work\authservices2\Kentor.AuthServices\WebSso\SignInCommand.cs:86
   Kentor.AuthServices.WebSso.SignInCommand.Run(HttpRequestData request, IOptions options) in C:\Work\authservices2\Kentor.AuthServices\WebSso\SignInCommand.cs:41
   Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e) in C:\Work\authservices2\Kentor.AuthServices.HttpModule\Saml2AuthenticationModule.cs:67
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

  I added a logger but up until the error everything looks complete.  This is "out of the box" with no modifications, but I'm probably not doing one step that is needed.

**Comment by edleno** [comment]
Sorry, didn't mean to put IdentityServer3 in the title.  This problem has nothing to do with that.

**Comment by explunit** [comment]
I am also seeing this error with the MVC Sample and the local Stub IDP in the master branch, but not in the v0.21.2 tag that corresponds to the released nuget version. I will tag as bug but in the meantime you might need to use the published nuget or checkout and older revision such as v0.21.2.

Regarding the use of discovery service in the sample, this is done to exercise supported features but is not a typical use case as I understand it.

**Comment by AndersAbel** [comment]
Fix looks good, but I don't understand what changed to cause the bug.
