### ISSUE TITLE
The Saml2Response must have status success to extract claims.

### ISSUE THREAD

**Issue by redapplewithleaves** [Sustainsys/Saml2#807]
Saml2 Second Level Status: urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy
![image](https://user-images.githubusercontent.com/9419314/30865497-a472f69e-a28b-11e7-90db-e7429020ff55.png)

Currently my nameIdPolicy is set to:
`    <nameIdPolicy allowCreate="true" format="Persistent" />`

I've been asked to add the following lines to the resulting in the Service Provider Metadata after `</KeyDescriptor> `
```
<NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat> 

```
But I couldn't find a way to set multiple nameIDFormats. Also, the nameIdPolicy doesn't result in any of those lines appearing in the Service Provider Metadata.

**Comment by explunit** [comment]
Would it work to use the `MetadataCreated` or `MetadataCommandResultCreated` notifications to customize the generated metadata? E.g. see here https://github.com/Sustainsys/Saml2/issues/473#issuecomment-220157016

**Comment by redapplewithleaves** [comment]
Where would you recommend to put the `metadataCreated`?

**Comment by redapplewithleaves** [comment]
I added it to the XML, but it seems to make no difference since the sign-in function does not even enter the generate xml code.

**Comment by AndersAbel** [comment]
The metadata publishes information on what `NameIDFormats` your application accepts. You can alter those in the `MetadataCreated` notification.

The `NameIDPolicy` of the `AuhtnRequest` should match one of those in the metadata. `Persistent` is not a valid standard value, you should use `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.

**Comment by redapplewithleaves** [comment]
Can you give an example of altering the `MetadataCreated ` notification?

I see this in the code:

```
        /// <summary>
        /// Notification called when metadata has been created, but before
        /// signing. At this point the contents of the metadata can be
        /// altered before presented.
        /// </summary>
        public Action<ExtendedEntityDescriptor, AuthServicesUrls>
            MetadataCreated { get; set; }
```

Where would you recommend to put the metadataCreated?

**Comment by AndersAbel** [comment]
@redapplewithleaves I'm sorry, but this is as far as I can help for free (which the issue tracker is). If you are interested in my commercial support options, please mail me at anders@sustainsys.com and I'll be able to help.

**Comment by redapplewithleaves** [comment]
Alright. Thanks for the offer and thanks for making this product.

I'll have to move on to different options then.
