### ISSUE TITLE
Relaystate cookie lost in ASP.NET Core handler

### ISSUE THREAD

**Issue by andreujuanc** [Sustainsys/Saml2#809]
Hello,
Using Sustainsys.Saml2.AspNetCore2.

When /Saml2 gets posted from Okta HandleRequestAsync responds to browser with a file.

It's my first time dealing with this protocol., i always used OpenId. 

How should I debug this?

commandName = context.Request.Path.Value.Substring(
                    options.SPOptions.ModulePath.Length).TrimStart('/');

returns "", which means give me the file., but why? is Okta giving the wrong command? (blank) or this file should be handled somehow?

My code is very simple and does not have anything fancy. Tried specifying ReturnUrl but does nothing.

Cheers

**Comment by AndersAbel** [comment]
The endpoint for the Assertion Consumer Service that Okta should post to is `/Saml2/Acs`. The `/Saml2` path will return the metadata of the SP.

**Comment by andreujuanc** [comment]
Thanks for reply, I did exactly that few hours ago, i didn't update the issue because I had a conference call.

Changed the path to /Saml2/Acs but it's throwing this:

> Received message contains unexpected InResponseTo "id31a5bc1dcb91419e8f3b85ab63c33054". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.

Is there any config prior to setting this up?  I have "exactly" the same as in the sample.

**Comment by andreujuanc** [comment]
I can see that expectedInResponseTo is null, but parsedInResponseTo is not. 
I will dig out where does expected comes from .

**Comment by AndersAbel** [comment]
Looks like something that needs to be investigated. I'll try to reproduce it.

**Comment by andreujuanc** [comment]
I don't know much about the project and Saml, but I think there must be a cookie before redirecting to the IP. Cos that cookie is somehow set when it comes back, but it firsts checks it and then sets it. So when i press F5 its already there and sends it on the request.

**Comment by AndersAbel** [comment]
The correlation cookie is set when issuing the 303 to redirect to the Okta Idp. Then it is checked when the response from Okta is received. The name of the cookie is carried in the RelayState parameter of the Saml2 request/response. It's both a matter of carrying state and protecting against login CSRF.

**Comment by andreujuanc** [comment]
Good tip. Will check that. My project is using all projects sources directly, so I can easily debug this.

**Comment by andreujuanc** [comment]
While debugging I found that when creating a HttpRequestData for the post from okla, request.Cookies has zero items.

I will have to install fiddler or similar to sniff the actual communication to see where is the problem, if in aspnet/dotnet or in okla.

**Comment by andreujuanc** [comment]
Can it be that Okla is making the post, but the actual request does not pass through the browser, or does not takes the cookies with it? Maybe some setting, like the fetch option` credentials: "same-origin"` , you get the idea.

At this point, I feel like it can be on Okta side, since I CAN CONFIRM that Kentor is sending the cookie right on the redirect response.

I will open an issue with them. Will close this :)

Anyways, let me know if you can get any info.

Thanks!!!

**Comment by andreujuanc** [comment]
I just tried it in Firefox and Edge and it works. Can it be a Blink issue, since it also failed in Opera?

**Comment by AndersAbel** [comment]
Looks like this is still an open issue. Reopening since this is the original.

**Comment by explunit** [comment]
This is a SameSite cookies issue due to the new defaults in ASP.NET Core 2. See linked PR #822. It only happens in Chrome because the others lack support for this standard. It worked for retried request because then the request *was* coming from same site.

**Comment by andreujuanc** [comment]
Issue can be closed as soon as the PR gets merged. 
Thanks to all.

**Comment by jonmeyerson** [comment]
I sadly ran into this issue somehow with UseCookiePolicy in 2.1, commenting it out resolved it.

**Comment by Subodhan** [comment]
I am getting the same error. I am using Firefox and Artifact binding. I am not using Okta. I am using the standard StubIdp provided with the code.

**Comment by AndersAbel** [comment]
@Subodhan This issue is already marked as solved. Please open a new bug report if you experience the same issue again.
