### ISSUE TITLE
It will throw a exception System.Web.HttpException if IDP only support HTTP-POST binding logout

### ISSUE THREAD

**Issue by Newbe36524** [Sustainsys/Saml2#810]
It will throw a exception System.Web.HttpException if IDP only support HTTP-POST binding logout

## Summary 

If only support HTTP-POST binding logout, "SampleIdentityServer3" will not work with a System.Web.HttpException throwed from IdentityServer3.

## How to show the problem

1. remove the HttpRedirect logout support from IDP Metadata

~~~csharp
//code class Kentor.AuthServices.StubIdp.Models.MetadataModel in Kentor.AuthServices.StubIdp project
public static class MetadataModel
    {
      ///..... nothing changed
      		idpSsoDescriptor.ArtifactResolutionServices.Add(0, new IndexedProtocolEndpoint()
            {
                Index = 0,
                IsDefault = true,
                Binding = Saml2Binding.SoapUri,
                Location = UrlResolver.ArtifactServiceUrl
            });

            //comment this to remove HttpRedirect logout support
            //idpSsoDescriptor.SingleLogoutServices.Add(new ProtocolEndpoint()
            //{
            //    Binding = Saml2Binding.HttpRedirectUri,
            //    Location = UrlResolver.LogoutServiceUrl
            //});

            idpSsoDescriptor.SingleLogoutServices.Add(new ProtocolEndpoint()
            {
                Binding = Saml2Binding.HttpPostUri,
                Location = UrlResolver.LogoutServiceUrl
            });

            idpSsoDescriptor.Keys.Add(CertificateHelper.SigningKey);

            return metadata;
        
        ///....nothing changed
    }
~~~

2. run the Kentor.AuthServices.StubIdp and SampleIdentityServer3, then login with client side

3. logout with client side 

4. I get a http crash as log in chrome 

(i cant post img in china) it`s status is failed as show in chrome dev tools.

## I traced the code 

1. the class Kentor.AuthServices.Owin.CommandResultExtensions in Kentor.AuthServices.Owin project

HttpContext.Current.Response.HeadersWritten will be changed from false to true,if executing `context.Response.Write(commandResult.Content)` showed below.

~~~csharp
// Write the content last, it causes the headers to be flushed
// on some hosts.
if (commandResult.Content != null)
{
    // Remove value set by other middleware and let the host calculate
    // a new value. See issue #295 for discussion on this.
    context.Response.ContentLength = null;
    context.Response.Write(commandResult.Content);
}
~~~

2. in this case, the IdentityServer3 will unable to clear cookies or send other headers. because HttpContext.Current.Response.HeadersWritten is true.

## My Question

1. is this an identityServer3 issue or Kentor.AuthServices.Owin issue?

**Comment by AndersAbel** [comment]
This is an issue with how the Owin pipeline works. When an authentication middleware such as Kentor.AuthServices is run, it is not guaranteed that the headers can still be changed and content written.

To work around the specific case with IdSrv3 + Saml2 Post binding would require looking at the source of both to see where it's easiest to adjust it.

But the easiest of all would of course be that you continue to use the Redirect binding. Is that possible?

**Comment by Newbe36524** [comment]
Yes,this is ok to use  the Redirect binding for me .
I will keep this issue opened for tracing the problem.

**Comment by AndersAbel** [comment]
Closing this as won't fix as there is an acceptable workaround using the Redirect Binding. Also, IdSrv3 is slowly phased out in favour of IdSrv4 which is based on Asp.Net Core.
