### ISSUE TITLE
Kentor AuthService give the error=access_denied in mvc

### ISSUE THREAD

**Issue by bhupendrasaini12** [Sustainsys/Saml2#825]
the auth request:

<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                     ID="id325ab97009864cadaa9fe323232c97e4"
                     Version="2.0"
                     IssueInstant="2017-10-25T02:01:32Z"
                     Destination="https://somedomin.com/nidp/saml2/sso"
                     AssertionConsumerServiceURL="http://somedomin.com/AuthServices/Acs"
                     AttributeConsumingServiceIndex="0"
                     >
    <saml2:Issuer>http://somedomin.com/AuthServices</saml2:Issuer>
</saml2p:AuthnRequest>

and my response

<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                Consent="urn:oasis:names:tc:SAML:2.0:consent:obtained"
                Destination="http://somedomin.com/AuthServices/Acs"
                ID="id-kws6Q7iCpBw7xrh_vTMY4x3ULQ"
                InResponseTo="id325ab97009864cadaa9fe323232c97e4"
                IssueInstant="2017-10-25T02:01:37Z"
                Version="2.0"
                >
    <saml:Issuer>https://somedomin.com/nidp/saml2/metadata</saml:Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <saml:Assertion ID="idQZ5crDC_gNUAWo6odhGsCPRA1JI"
                    IssueInstant="2017-10-25T02:01:37Z"
                    Version="2.0"
                    >
        <saml:Issuer>https://somedomin.com/nidp/saml2/metadata</saml:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <CanonicalizationMethod xmlns="http://www.w3.org/2000/09/xmldsig#"
                                        Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"
                                        />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <ds:Reference URI="#idQZ5crDC_gNUAWo6odhGsCPRA1JI">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <DigestValue xmlns="http://www.w3.org/2000/09/xmldsig#">PYogmzWEMjvpEiBA01y74AfEPaGvJqMNDN+P395ltqI=</DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <SignatureValue xmlns="http://www.w3.org/2000/09/xmldsig#">
coqXXPbVU/BunXhaHk7AhiVXM1/cD/o3IZ6i7OL7AuQ/mVetcIzzJLs6gaY221ZOiaLHfKWdU3ww
Bp5DCo0amw5Tn5tPLCxITp/27+JdJBMmS6/mzYMqcuhfhGC+hvBLETuQzvI3qhZhhZMNYuSlb2Az
6/danJc52ziDaKfULR9LLUovP7xJSqM764ZHPgX9Y0flqchXrLC/Og57f8TmgYBTw2h3VmUmToXC
iAydcWtMjQhOPOXA/v4cw+4MFzW1Ng9weMPWX6FCE0FLwCLuFzqqYN5i1DShLCl0nCcnjVMDyZAF
lZ56rCEOdxuMncpE1sMwu1iur0GLLYMJMuPaUg==
</SignatureValue>
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>
MIIFlDCCBHygAwIBAgIQU8uTHtHUCIkbiOAevpMOPTANBgkqhkiG9w0BAQsFADBBMQswCQYDVQQG
EwJVUzEdMBsGA1UEChMUQ29ybmluZyBJbmNvcnBvcmF0ZWQxEzARBgNVBAMTCkNvcm5pbmcgQ0Ew
HhcNMTcwMzAyMDAwMDAwWhcNMTkwMzAyMjM1OTU5WjCBgjEnMCUGA1UEAwwec3NvdGVzdC5mZWRl
cmF0aW9uLmNvcm5pbmcuY29tMRMwEQYDVQQLDApTSU1QTEUtU1NMMRYwFAYDVQQLDA1NVUxUSS1B
TExPV0VEMQswCQYDVQQGEwJVUzEdMBsGA1UECgwUQ29ybmluZyBJbmNvcnBvcmF0ZWQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3HZi6XJbBc06vLBoddVwJ9HGQyOUiXNwV7iONwiyR
cVSZ6YWne/O0sp969PyIo2CBhNijI2b2QOg05ctHQfz43WLa7BoCAN2PeZfrmlfyKPZOfWtGfvBs
wtcUh7q145HeLWKe16mUq+fmHQ3afPgPateTlIK9wOnQ4dUrk0V0wQxp3tx0NEc+mvgO844U4ULG
vMlZTXD6pST+bzV8pAH7ambNLRBlxoHSVRdsUA2BzeYM/P0f5qoNthvKhXO/gdTSdccy2SUjXrUW
hTGjy0482tkMHGflaWSPQu/kKPkmBN4w8QhwXKX+jJVpLXH8H5oQoi5gBVRdibNyw6K1FNQFAgMB
AAGjggJEMIICQDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIFoDAgBgNVHSUBAf8EFjAUBggr
BgEFBQcDAgYIKwYBBQUHAwEwHQYDVR0OBBYEFOxY0J8qdL2SzhXjkSsRuhaKxyVbMCkGA1UdEQQi
MCCCHnNzb3Rlc3QuZmVkZXJhdGlvbi5jb3JuaW5nLmNvbTBdBgNVHR8EVjBUMFKgUKBOhkxodHRw
Oi8vcGtpLWNybC5zeW1hdXRoLmNvbS9jYV8wOTUxMmZiYzQzODgxMjlhMWJmZjM4MjM0M2E4OGJm
MC9MYXRlc3RDUkwuY3JsMIHKBggrBgEFBQcBAQSBvTCBujAnBggrBgEFBQcwAYYbaHR0cDovL3Br
aS1vY3NwLnN5bWF1dGguY29tMIGOBggrBgEFBQcwAoaBgWxkYXA6Ly9kaXJlY3Rvcnkuc3ltYXV0
aC5jb20vQ04lMjAlM0QlMjBDb3JuaW5nJTIwQ0ElMkMlMjBPJTIwJTNEJTIwQ29ybmluZyUyMElu
Y29ycG9yYXRlZCUyQyUyMEMlMjAlM0QlMjBVUz9jQUNlcnRpZmljYXRlO2JpbmFyeTAfBgNVHSME
GDAWgBQRM/3WrWsO1AU82fo8ugplhT5gcDAsBgpghkgBhvhFARADBB4wHAYSYIZIAYb4RQEQAQUC
AQGLxolQFgYzMjcwOTAwOQYKYIZIAYb4RQEQBQQrMCkCAQAWJGFIUjBjSE02THk5d2Eya3RjbUV1
YzNsdFlYVjBhQzVqYjIwPTANBgkqhkiG9w0BAQsFAAOCAQEAnPezgLQlYH0CeyKwMGnhlxS0njNz
7ri9CvFydbCvrkHzDRvR7TiDj/FO6JTi7fyClFPDa2puVrUnqLfGoLxGX3uoo5+FmWiDhsCWP9IS
Be+D6RRLLyVaJlINa3PA13ZriG+apeafWNFe+12Hu+JFAu+/6uhLseme3XL9KIUtoB2uBmF8hUyG
mGVv0q0uMbCiP68i4A8YaD/rC6BhLgmk/vpIKlhLox/nntOGVSYA+jJHAmuNDNTpA97BF2ZXa75B
+06dEXb5fvw82xDGDfFt9Y29YBVDVJqTC07gOS49HLeIGynIExUV+WHHVAVyZvjDgxFcahGeH6de
P3959HQDDA==
</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
                         NameQualifier="https://somedomin.com/nidp/saml2/metadata"
                         SPNameQualifier="http://somedomin.com/AuthServices"
                         >KundurthA@dominname.com</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData InResponseTo="id325ab97009864cadaa9fe323232c97e4"
                                              NotOnOrAfter="2017-10-25T02:06:37Z"
                                              Recipient="http://somedomin.com/AuthServices/Acs"
                                              />
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2017-10-25T01:56:37Z"
                         NotOnOrAfter="2017-10-25T02:06:37Z"
                         >
            <saml:AudienceRestriction>
                <saml:Audience>http://somedomin.com/AuthServices</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2017-10-25T02:01:37Z"
                             SessionIndex="idQZ5crDC_gNUAWo6odhGsCPRA1JI"
                             >
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
                <saml:AuthnContextDeclRef>ETQ_contract/uri</saml:AuthnContextDeclRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute xmlns:xs="http://www.w3.org/2001/XMLSchema"
                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            Name="firstName"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                            >
                <saml:AttributeValue xsi:type="xs:string">chetan</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute xmlns:xs="http://www.w3.org/2001/XMLSchema"
                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            Name="lastName"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                            >
                <saml:AttributeValue xsi:type="xs:string">Chopra</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute xmlns:xs="http://www.w3.org/2001/XMLSchema"
                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            Name="email"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                            >
                <saml:AttributeValue xsi:type="xs:string">KundurthA@dominname.com</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>

I have saml logged
![error](https://user-images.githubusercontent.com/33077442/31977095-dd322be2-b958-11e7-87f5-9c59967ae4a2.jpg)

After the successfully login it goes to login page

**Comment by AndersAbel** [comment]
Turn on logging, it should show what's wrong.
