### ISSUE TITLE
Idp login page every time

### ISSUE THREAD

**Issue by cauxmika** [Sustainsys/Saml2#827]
Hello,

    I'm using Kentor as an IDP and my application is the SP.

On the first access to my application url : 
1. My application send an AuthnRequest to IDP.
2. IDP send his login page and is displayed to the end user.
3. On login button pushed, my application receive a valid saml response and redirect to my application with a valid sso connection.

So, this part is ok 👍 

But, I don't understand why, when I call again my application url, **IDP send me again his login page instead of a valid saml response**. Knowing I can that see the IDP cookie is present as John Doe. Do you know why ? Is it the normal behavior ? Did I miss something ?

Thanks in advance for help.

Mickaël

**Comment by explunit** [comment]
This is just the behavior of the "stub" test IDP. Most production IDP's I've seen will do as you describe and simply redirect back with SAML unless you specify the force authentication in the authentication request.

**Comment by cauxmika** [comment]
Many thanks for this quick response :-)

So, we can't test this behavior with Kentor "stub" test IDP. Thanks.
