### ISSUE TITLE
Question - What are the signing and service certificates

### ISSUE THREAD

**Issue by sanattiwari** [Sustainsys/Saml2#828]
Hi, We are using kentor auth services for implementing SAML in ASP.net application.
This is not an issue but a question, want to understand what is a signing certificate and who will provide this certificate?

Is it like identity provider has to provide one certificate which has to be used by service provider to verify signatures after receiving the saml response?

Please clarify? we may be using NAM (NetIQ) as identity provider, will this certificate be provided by NAM and we have to use in our IIS where application is hosted?

Thanks!
Sanat

**Comment by AndersAbel** [comment]
The signing certificate of the Idp is the public key you get from the Idp
The servicecertificate configured as part of the SP config is only needed if you do single logout or signed AuthnRequests. In that case it is a (probably self-signed) cert that you create for your app.

**Comment by sanattiwari** [comment]
Thanks Ander. So it means signing certificate has to be provided by the Idp so that we can use it to verify if messages are coming from right Idp or not? is this also used to decrypt the SAML response coming from Idp?
Regarding service certificate, I am using Asp.Net HttpModule and in its sample, below configuration is provided. This means the requests going out of application (SP) is signed using below certificate?
Configuration in sample App:
`<serviceCertificates>
      <add fileName="~/App_Data/Kentor.AuthServices.Tests.pfx" />
    </serviceCertificates>`

**Comment by AndersAbel** [comment]
Yes, you are right.

The Stub Idp is *not* doing the validations required by a real Idp. Yes, in a real setup you would have to send the public key of the SP certificate to the Idp - or better give them your metadata Url so that they can download all relevant info themselves.

**Comment by sanattiwari** [comment]
Thanks a lot Anders
