### ISSUE TITLE
Question - How can we use kentor authservices to authenticate webservice

### ISSUE THREAD

**Issue by sanattiwari** [Sustainsys/Saml2#829]
Currently we have web forms application, which has some web services inside it.
We are changing authentication part of web form app to use SAML with identity provider as NAM.
There are some webservices in it which should be called by passing credentials like username or password in soap header.

How these web services should be changed now? since there wont be user name password inside the app now? How external webservices should call these web services?

Thanks!
Sanat

**Comment by sanattiwari** [comment]
Any feedback on this?

**Comment by AndersAbel** [comment]
This is a major design issue for your application and not something that can simply be answered. So it's not a good fit for the issue tracker. If you want commercial consulting services on the design of your solution, please mail me at anders@sustainsys.com.
