### ISSUE TITLE
Which SAML profiles are supported by this library

### ISSUE THREAD

**Issue by sanattiwari** [Sustainsys/Saml2#830]
Which of the below profiles are supported by this AuthServices?

1. Web browser single sign-on (identity provider and service provider initiated)
2. Single logout
3. Artifact resolution
4. Identity provider discovery
5. Authentication, attribute and assertion query
6. Name identifier management and mapping

**Comment by AndersAbel** [comment]
1. Web SSO is supported, but SP and Idp initiated)
2 Single Logout is supported.
3. Artifact resolution is supported when sending AuthnRequests and Logout messages to the Idp. It is not supported for receiving Logout messages from the Idp.
4. If by "Identity Provider Discovery" you mean a discovery service it is supported.
5. AuthnRequests are supported. Not attribute or assertion query.
6. No name identifier management and mapping is supported.
