### ISSUE TITLE
Dotnetcore 2 and Notifications

### ISSUE THREAD

**Issue by andreujuanc** [Sustainsys/Saml2#833]
Hello,

I subscribed to the notifications but they were not firing. It was weird. I tried to set any to null, and didn't work. I had to change the Notifications property and add a set method, then I created my own Instance, but not in the constructor like it is now. AND IT WORKED. I'm confused. Can it be a dotnetcore 2 issue?

Best regards.

**Comment by mrfatgoat** [comment]
I had the same issue and I'm working on a PR to fix this.  Should be up in the next day or two.

**Comment by AndersAbel** [comment]
Thanks for noticing this. I've commented on the PR.

**Comment by andreujuanc** [comment]
I see now the code, every time Notifications was access it returned a new instance. Right? 
I thought I was crazy.

**Comment by AndersAbel** [comment]
@andreujuanc Yes it does. I actually wrote a blog post about the syntax, but still got it wrong :( https://coding.abel.nu/2017/10/expression-bodied-vs-auto-read-only-properties/

**Comment by dgvinay** [comment]
Looks like this bug is back in version 2.0.0 Preview.

None of the notifications are hitting.
