### ISSUE TITLE
Question: Separate MVC and Web Api Applications

### ISSUE THREAD

**Issue by payneBrandon** [Sustainsys/Saml2#835]
I've been searching through the documentation, and through forums for the last couple days and cannot find an answer to this question, so figured I'd post it here.

I currently have a software solution comprised of an MVC application, and two Web Api services (separate projects).  The system currently uses Asp.Net Identity, and we are trying to move this over to accommodate SSO using SAML.  I have used the demo app with the OWIN pipeline, and am able to get a user to log into our system through using the stubidp, however I'm running into an issue with passing that authenticated user on to the service.

Previously we have accomplished this by using OAuth bearer tokens (acquired via the '/token' endpoint on the web api services).  Is there a token associated with the Systainsys Saml2 system that I can overwrite the token decryption on the web api end to get the current user with?  Or should I use some cookie to send to the web api for authentication?  

I've installed the proper nuget packages on the web api side as well, but am at a loss as to the next steps.  Thanks for looking!

**Comment by AndersAbel** [comment]
SAML2 was created long before REST APIs existed, so they don't play well together. Keep OAuth2 for authenticating to the API.

A common approach is to add an IdentityServer3 instance that handles the SAML2 authentication (Sustainsys.Saml2/Kentor.AuthServices can be used as external auth for IdSrv3) and then let both your MVC app and the API use OIDC against the IdSrv3. See the SampleIdentityServer3 project in the repo for some guidelines.

**Comment by payneBrandon** [comment]
I was wondering if proper solution would involve setting up an IdentityServer instance to handle this.  Thanks for the help!
