### ISSUE TITLE
Problems With Implementing SLO with Kentor.Authservices

### ISSUE THREAD

**Issue by ErikMolnarSoftronic** [Sustainsys/Saml2#836]
Hi there.

I am working on a project where Single Logout is required and the service uses the Kentor/Sustainsys as the SAML engine. I have read many similar posts regarding the same issue, among others the closed issue "Single Log out - what is required to be implemented in SSO Logout endpoint #459", since I believe I am facing a very similar problem and I have learned quite a bit. However, I am still not able to get a successful logout with the service I am working on.

I have redirected the user to the AuthServices/Logout Action with the following code:

<a href="@Url.Action("../AuthServices/Logout", new {ReturnUrl = "/?Status=LoggedOut"})">Log out</a>.

That did not do the trick as I was only logged out locally, not on the IDP side. Thus I found out that for the SLO to work on the IDP side, you have to make use of a certificate in the signout process, since it requires signing. I then added the following code to web.config and added the certificate to my solution:

        <serviceCertificates>
          <add fileName="~/App_Data/mycert.pfx" />
        </serviceCertificates>

I then debugged the code in the InitiateLogout method in the LogoutCommand.cs class again, and it could now find the certificate, which it could not do before and it proceeded to send the logout request to the IDP. However...

I was then met with an error message in the browser and with no particular exception that I could see was shown in the code:

![image](https://user-images.githubusercontent.com/33055417/32555962-684bef60-c49e-11e7-83f8-1d9f4faef8f5.png)

Saml/SignOut is not an action in any controller in the service and it looks like it's trying to send the request to some part of the service that is simply not implemented. Any suggestions of what might be causing this?

Any help is appreciated.

**Comment by explunit** [comment]
Maybe the IDP just needs to fix the return URL. Do you know where the IDP got this URL? Was it manually configured or was it pulled from your SP metadata? Unlike authentication requests, logout requests do not specify the return URL and the IDP just uses what it has on file for that SP.

**Comment by ErikMolnarSoftronic** [comment]
I do not know excactly how the IDP got that information, but now when I take a look at the metadata in our development enviroment (this particular IDP is only used in our dev-enviroment), I can clearly see that this is included:

<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://saml.vs.stc13034.dev/Saml/Logout" />

....however logout and signout are same things here....so I don't think it is pulling it from the metadata. I think we have full controll over this IDP. I will take a closer look and see if this is manually configured somewhere.

So, your theory is that perhaps the IDP needs to redirect back to another page and this one is just pointing to some wrongly configured logout url? (Logout functionality was never a part of the initial functionality of this service, but it has recently been added as a requirement)

**Comment by explunit** [comment]
Yes, that's my theory.

**Comment by ErikMolnarSoftronic** [comment]
You were absolutely correct. I found a 'SingleLogoutService' configuration at the development IDP that pointed to the page that did not exist, namely Saml/Signout. I changed it to point to the home page of the application and it now redirected correctly. However, the user (me) is not prompted to enter his credentials when logging in again.

In other words, I am seeing the same effect as when I just redirected the user to "../AuthServices/Logout", without providing a certificate. However, I did try to login again from another browser and I was then prompted to enter my credentials once again. I'm guessing the session has been terminated on the IDP side, but not on the SP side? Or should not the redirection to the AuthServices/Logout part of the engine perform both a local logout in the browser and a remote logout at the IDP?

**Comment by ErikMolnarSoftronic** [comment]
I was able to get a complete logout to work now by killing the session locally as well with the following code:

Session.Abandon();

In other words, the logout for the AuthServices/Logout method worked to logout the user from the IDP, but not locally.

Anyway, I have achieved what I set out to do. Thank you for pointing me in the right direction!

**Comment by explunit** [comment]
The correct logout url should be available in your SP metadata in the `<SingleLogoutService>` tag. This is what the IDP should be using to return the logout response or to inform your application that the user wants to log out (IDP-initiated logout, for lack of a better term).

The SP metadata is available by default at the root `/AuthServices` path. Ideally, the IDP consumes your metadata directly and you don't have to manually configure these paths.

**Comment by ErikMolnarSoftronic** [comment]
Indeed. The implementation of this functionality is mainly being done in order to supply our IDP with SLO addresses in the SingleLogout tag in our metadata.

Do you know how to edit this <SingleLogoutService> metadata tag? It is currently configured to something incorrect. I am experimenting around with the <metadata> tag in web.config, but have not found a way to edit this particular part of the metadata as of yet.

**Comment by explunit** [comment]
What value is showing up in your SP metadata and what did you think it should be instead?

Also, which mode of AuthServices are you using (HttpModule, OWIN, or MVC nuget)?

**Comment by AndersAbel** [comment]
The Logout endpoint in the metadata is not directly editable. You can change the base path by changing `ModulePath` (as I guess you've already set to `Saml`).

When things are correctly set up you should not need to do a `Session.Abandon()` to get logged out - the login session should be handled by the `SessionAuthenticationModule` and not by the session system. The Idp should redirect/post the logout response to ~/Saml/Logout.

If you are interested in consulting services in Stockholm (where I guess you are located), please mail me at anders@sustainsys.com.

**Comment by ErikMolnarSoftronic** [comment]
@explunit  I have managed to manipulate the the metadata generation so that it now displays the SLO address which I want it to point at. Previously, it displayed, https://saml.vs.stc13034.dev/Saml/Logout, but it now displays https://saml.vs.stc13034.dev/Account/Signout/Saml, which is our logout page at our service. I am using the Kentor.AuthServices, Kentor.AuthServicesHttpModule and the Kentor.AuthServices.Mvc projects in conjunction with the service. Sorry for not answering that the problem was solved earlier.

@AndersAbel  Ok, I see. It seems to be working now with the implementation I made, so in case we encounter any problems when publishing to test, or production, I will keep your advice in mind.
Regarding the consulting service, I do not think that will be necessary at this stage. Should the need arise in the future, I will first speak with my supervisor and then e-mail you.

Thank you both for your input. I will contact you either here, or via e-mail if I require any more assistance.

**Comment by cederlof** [comment]
> When things are correctly set up you should not need to do a Session.Abandon() to get logged out - the login session should be handled by the SessionAuthenticationModule and not by the session system. The Idp should redirect/post the logout response to ~/Saml/Logout.

From what I can see the `ASP.NET_SessionId`-cookie will never be deleted and keep the same value for subsequent sessions if you do not do Session.Abandon? However that should not pose a risk if you do not base any custom logic on that session-id.

**Comment by AndersAbel** [comment]
`ASP.NET_SessionId` is not the cookie for the login session. The login session is handled by the `SessionAuthenticationModule` has another cookie. If you are using Asp.NET Sessions to store data, you should call Session.Abandon if you have stored any user-related data in the session.
