### ISSUE TITLE
Can you have Idp return to a different retrunUrl

### ISSUE THREAD

**Issue by corsini2** [Sustainsys/Saml2#839]
I have SSO working with the HttpModule so that when a user comes to the start page of my application, they see a link to sign on.  clicking the link takes them to the idp and returns them to the returnUrl set in the web.config.  
the link is similar to this:
                LoginLink.InnerHtml = "<a href = ""AuthServices/SignIn?idp=" & HttpUtility.UrlEncode(EntityId) & """ > Sign In</a>"

Now I want to add the ability for a user to go to a protected page, and if they are not authenticated, send them to the IDP and return to the protected page.  Is it possible to either set the returnUrl dynamically, or pass some parameter so that when the user gets to the returnUrl we can check the parameter and redirect to the secure page?

**Comment by AndersAbel** [comment]
Yes, Just add a ReturnUrl=%2Fprotected%2Fpage query param in the call to SignIn.
