### ISSUE TITLE
IdP-flow - Authentication Property "LoginProvider" not set

### ISSUE THREAD

**Issue by andreujuanc** [Sustainsys/Saml2#840]
Hello,

I successfully implemented authentication with Okta and Saml2. But when trying IdP-flow it fails.

After debugging for a few minutes i found that LoginProvider is not in the RelayData.

Is it something I have to do manually? (I'm using AcsCommandResultCreated) or RelayData should be handled by the middleware somehow?

Cheers

**Comment by AndersAbel** [comment]
Is this with IdentityServer?

**Comment by andreujuanc** [comment]
Nope. Just a token after auth and that's it.

For now I set it on AcsCommandResultCreated. It works fine. 

Is this normal? Should I debug this and post more data/info?

**Comment by AndersAbel** [comment]
What is this LoginProvider value? What did you expect it to be?
