### ISSUE TITLE
Connecting to external IdP

### ISSUE THREAD

**Issue by RaulAlon** [Sustainsys/Saml2#845]
Hi!

I'm pretty new in SAML and I'm having some problems/questions with my project that I wanted to solve.
What I want to do is to configure my project to use an external cllient IdP. For that, I only have the url with the metadata of my IdP client and the url that I should use to connect with him. (To make this connection I'm using the sample "SampleMvcApplication").

I post my current Web.config below:

```
 <authentication mode="Forms">
      <forms loginUrl="~/AuthServices/SignIn" />
    </authentication>
```

```
  <system.webServer>
    <modules>
      <add name="SessionAuthenticationModule" 
type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" preCondition="managedHandler" />
    </modules>
  </system.webServer>
```

 ```
 <kentor.authServices entityId="http://localhost:2181/AuthServices" returnUrl="http://localhost:2181/">
    <identityProviders>
      <add entityId="urlOfClientMetadata"
           signOnUrl="urlOfIDP"
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/Clientcertificate.cer" />
      </add>
    </identityProviders>
    <serviceCertificates>
      <add fileName ="~/App_Data/ClientCertificate.pfx" />
    </serviceCertificates>
  </kentor.authServices>
  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="SampleMvcApplicationAuth" />
    </federationConfiguration>
  </system.identityModel.services>
```

**First question is:** I'm using <identityProviders> to specify the features of client IdP, is it correct?
I've seen that other people only use <federations>
   
    <federations>
      <add metadataLocation="urlClientMetadata" allowUnsolicitedAuthnResponse="true" />
    </federations>

**Second question:** : What do you need to setup a federation between a service provider and an Identity Provider? I mean, is it necessary to have the metadata of both?

**Basic problem:** The main problem is that my service provider is not connecting with the client IdP and I'm not sure if it's because of my configuration or for another reason.

Thank so much for your time! ;D

**Comment by explunit** [comment]
You probably don't want the federation config if you have just a single idp.

You should just need to tell it to load the metadata for your IDP, something like
```
    <identityProviders>
      <add entityId="entityIdOfIDP"
           metadataLocation="urlOfIDPMetadata"
           loadMetadata="true"
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
      </add>
    </identityProviders>
```

Then you don't need to configure the signing certificate or signonurl since it they come from the metadata.

If your IDP's entity id is the same as the metadata url then you can omit the metadataLocation tag

**Comment by RaulAlon** [comment]
@explunit Thank you so much for your response. I have tried it and it seems like this configuration is working, but now I have some issues with the client. I think that my client needs the metadata info from my service provider to register this one into his identity provider, but I don't know how to generate it. Do you know how to do it?

Thanks again!

**Comment by explunit** [comment]
By default the metadata from your SP should be available at the root of your AuthServices path in your web application

**Comment by RaulAlon** [comment]
Thanks @explunit !
