### ISSUE TITLE
The signing algorithm <...sha1> is weaker than the minimum accepted <...sha256>

### ISSUE THREAD

**Issue by chesteryhi** [Sustainsys/Saml2#848]
I know there is a very similar post about the issue ([https://github.com/Sustainsys/Saml2/issues/672](https://github.com/Sustainsys/Saml2/issues/672)), but what I get this time is "sha1" is weaker than the "sha256" instead.

I got this error once when I am using the .Net Framework 4.5, but it was "sha256" weaker than "sha1" just like the mentioned post, and it is gone when I changed it to 4.6.2.
And it still works fine with the testing idp: http://stubidp.kentor.se/
But when I signed on to the client's idp, I got this error.

The version I'm using is 0.21.2.

Server Error in '/' Application.

The signing algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 is weaker than the minimum accepted http://www.w3.org/2001/04/xmldsig-more#rsa-sha256. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: Kentor.AuthServices.Exceptions.InvalidSignatureException: The signing algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 is weaker than the minimum accepted http://www.w3.org/2001/04/xmldsig-more#rsa-sha256.

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[InvalidSignatureException: The signing algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 is weaker than the minimum accepted http://www.w3.org/2001/04/xmldsig-more#rsa-sha256.]
   Kentor.AuthServices.XmlHelpers.ValidateSignatureMethodStrength(String minIncomingSignatureAlgorithm, String signatureMethod) +362
   Kentor.AuthServices.XmlHelpers.ValidateSignedInfo(SignedXml signedXml, XmlElement xmlElement, String minIncomingSignatureAlgorithm) +36
   Kentor.AuthServices.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm) +148
   Kentor.AuthServices.Saml2P.<>c__DisplayClass52_0.<ValidateSignature>b__0(XmlElement a) +59
   System.Linq.Enumerable.Any(IEnumerable`1 source, Func`2 predicate) +179
   Kentor.AuthServices.Saml2P.Saml2Response.ValidateSignature(IOptions options) +293
   Kentor.AuthServices.Saml2P.<CreateClaims>d__57.MoveNext() +127
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +452
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +70
   Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options) +218
   Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) +52
   Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +869
   Kentor.AuthServices.Mvc.AuthServicesController.Acs() +81
   lambda_method(Closure , ControllerBase , Object[] ) +87
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +280
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41() +33
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +69
   System.Web.Mvc.Async.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33() +80
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +69
   System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +32
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +185
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +22
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +22
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +22
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1590.0

**Comment by AndersAbel** [comment]
In this case the error message is correct. The Idp has sent you a response signed with rsa-sha1. The default minimum accepted level is rsa-sha256. You should tell the Idp people to change to rsa-sha256 as rsa-sha1 is no longer considered secure. If they don't want to change, set the minIncomingSigningAlgorithm to "rsa-sha1" to supress the warning.
