### ISSUE TITLE
Cookie not set for multiple SAML IDP

### ISSUE THREAD

**Issue by netachar05** [Sustainsys/Saml2#849]
Our application is authenticated for multiple Shibboleth IDP using KentorAuthServices.  Challenge works fine but, HttpContext.Current.GetOwinContext().Authentication.AuthenticateAsync(DefaultAuthenticationTypes.ExternalCookie)  fails to return the principal if multiple identity providers are configured.  

I found that if it is a single provider, the request will have a cookie .AspNet.ExternalCookie and has a proper value and authenticates without any issue.

If multiple identity providers are added, the cookie name is Kentor.Gr-lOTMKSNFn4vQ0U-eNsfNVp8T1pbadbJiT5jXkUrgn8R7P8YYyl0_Z and the value ends with ... (3VTfiCKc2mfIcxU1On0Yljz_uh2VvDD5jHGX26E4UNJeKpw_THDZWgZQjN4bB9obSdl0z7FnPKj61pAQ-n5RVXrPBhY4V7-Ky1krJaZX7c-KF41F_TL0owvb-JPl3Gnc6T6puLFp9Wo1T0BnwtYjP_o5WBaKgWcd1SaAROoqk2vIn2Um6EZX22yMRHbzb2naMtJK4GUCuU6wZSBLcyJvhrO0v8o-d1t-jgoetZjqCmElcnj9clW3CfQ2WTZj8U80TjhzRw..)  which fails the authentication and return null.

How can we handle this?

**Comment by KevinMVTransit** [comment]
I banged my head on this one too, until i read this line.

See Selecting IDP
https://github.com/Sustainsys/Saml2/blob/599a12cf36c79c5def25c7f6d6862c7d0fda38b4/doc/OwinMiddleware.md

Another, more simple way to pass a value is to put it directly in the Owin environment dictionary under the key "KentorAuthServices.idp".

Here's an example of how to set the Owin environment value through ASP.NET MVC

var context = HttpContext.GetOwinContext();
**context.Environment.Add("KentorAuthServices.idp", new EntityId(YOUR_IDP_ENTITY_ID));**

Here is my code

        private void ExecuteOAUTH(string RedirectUri, string SAMLidentityProvider)
        {

            var properties = new AuthenticationProperties {
                RedirectUri = RedirectUri
            };
            properties.Dictionary.Add("idp", SAMLidentityProvider);
            Request.GetOwinContext().Authentication.Challenge(properties, LoginProvider);

        }

**Comment by netachar05** [comment]
Thanks Kevin.  The challenge is working fine, get authenticated and is routed back to our application.  We do back an authenticatesync after this challenge which is failing.  The only difference I see is the cookie name and value for same IDP, if muliple identity providers are configured.

I tried adding the element to environment before authenticating, which didn't help.

**Comment by KevinMVTransit** [comment]
Ahh, well I dont know if this helps, but After challenge, I could not extract the info and found out that the IDP was SHA1.  By default, this projects minimum is SHA256.

Had to add:
spOptions.MinIncomingSigningAlgorithm = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
After that, the claims were coming thru like a champ.

And, I have added multiple IDPs.

Hope this helps.

**Comment by netachar05** [comment]
@KevinMVTransit , That too didn't help.  I had pasted the piece of code I am trying with.  The cookie value set by kentor seems to be corrupted.

var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
			{
				SPOptions = new SPOptions
				{
					EntityId = new EntityId(org.Realm),
					ReturnUrl = new Uri(org.Realm),
					Organization = organization,
					ModulePath = "/AuthServices",
					PublicOrigin = new Uri(org.Realm.Remove(org.Realm.IndexOf("/Authentication"))),
					MinIncomingSigningAlgorithm = "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
				},
				AuthenticationType = org.Caption,
				Caption = org.Caption,
				SignInAsAuthenticationType = DefaultAuthenticationTypes.ExternalCookie,
			};

			authServicesOptions.IdentityProviders.Add(new IdentityProvider(
			new EntityId(org.IDPProvider), authServicesOptions.SPOptions)
			{
				MetadataLocation = org.MetadataUrl,
				LoadMetadata = true,
				SingleLogoutServiceUrl = new Uri(org.Realm),
			});
			app.UseKentorAuthServicesAuthentication(authServicesOptions);
			
//THIS CODE WORKS			
return new ChallengeResult(provider, Url.Action("ExternalLoginCallback", "Authentication", new
{
	ReturnUrl = returnUrl,
	provider = provider
}));

//THIS ONE FAILS
Microsoft.Owin.Security.AuthenticateResult result = await HttpContext.Current.GetOwinContext().Authentication.AuthenticateAsync(DefaultAuthenticationTypes.ExternalCookie);

**Comment by KevinMVTransit** [comment]
Im using the OWIN path and not MVC. So I have not had any experience with that one.
Good luck.

Thank you,
Kevin Cornelison
Application Developer
MV Transportation, Inc.

**Comment by AndersAbel** [comment]
@netachar05 Did you add multiple identityproviders to one middleware instance? Or did you register multiple middleware instances?

**Comment by KevinMVTransit** [comment]
Add multiple idps to one service

**Comment by AndersAbel** [comment]
@KevinMVTransit Yes, I see that you did that, but it's not clear if @netachar05 did that. Both ways are possible, but different stuff get complicated depending on what you choose. One middleware instance => need to pass idp selection (as you noted). Several => need to separate module paths.

**Comment by KevinMVTransit** [comment]
I recommend having one Service Provider and add multiple IDPs.
Just like what is in the sample app.

**Comment by netachar05** [comment]
@AndersAbel,  @KevinMVTransit,  Thanks for the suggestions.  I am adding multiple multiple middleware instance for each IDP, since the organization id and return url are different for multitenant environment of same application.  Module path is specified for each instance by specifying public origin.  Only for the first instance external cookie is set in correct format, while for the remaining instance the cookie seems to be corrupted.  Is there any way to add middleware instance at runtime other than in startup, I mean at controller level?

**Comment by AndersAbel** [comment]
@netachar05 You need to set separate module path's for each instance as well. Even though you have different public origins, the first middleware instances will always be triggered. If you enable logging, I'm sure you'll see a message that the idp is unknown.

**Comment by KevinMVTransit** [comment]
@netachar05 , I see.  3 weeks ago, I have never heard of SAML, so I have only used the One Service Provider with multiple IDPs.  I may be in the same situation as you some day, Please post if you find the solution.

**Comment by netachar05** [comment]
@AndersAbel , How can I assign different module path for each instance?  Any value other than "/AuthServices" assigned to this property fails at provider level mentioning misconfiguration in request.

**Comment by netachar05** [comment]
@AndersAbel , @KevinMVTransit ,  Since module path didn't help, I had followed @KevinMVTransit suggestion and changed the code for single instance and multiple IDP with IDP property added before challenge, which resolved the issue.  Thanks both of you for the help and suggestions.

**Comment by KevinMVTransit** [comment]
@netachar05 , Good luck!
