### ISSUE TITLE
Service provider metadata structure

### ISSUE THREAD

**Issue by RaulAlon** [Sustainsys/Saml2#851]
Hi!

I'm trying to generate a service provider metadata file to setup a federation with my client but I'm not sure if  the structure and the differents fields for this document are complete. 
Like @explunit told me in the issue  [#845](https://github.com/Sustainsys/Saml2/issues/845), I'm downloading my service provider metadata from the url /AuthServices. That file contains the following XML code:

`<EntityDescriptor ID="_c358978e-995e-4239-ac7f-ef00c4299695" entityID="http://localhost:2181/AuthServices" cacheDuration="PT1H" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns="urn:oasis:names:tc:SAML:2.0:metadata"><SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:2181/AuthServices/Acs" index="0" isDefault="true" /><AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="http://localhost:2181/AuthServices/Acs" index="1" isDefault="false" /></SPSSODescriptor></EntityDescriptor>`

In comparison with my client's metadata file, I can see that mine doesn't contain any type of certificate (in my client's xml appears several X509 certificates) and, in general, mine contains less information. Is my XML fine?

I've seen in other issues that, for single logout, it is necessary to configure other things, in my case I'm not going to use it.

If it was necessary I could post my client's XML.

Thank you in advance!

**Comment by AndersAbel** [comment]
The default metadata is trimmed down, but contains all the stuff needed for sign on.

A certificate is generally not needed for sign on only implementations. If you add a certificate (which is required for log out) it will automatically be published in the metadata and the logout endpoints will show up too.

**Comment by RaulAlon** [comment]
So, if I have understood correctly, if my client uses this metadata file, it could register my service provider in his idp without any other data?

**Comment by AndersAbel** [comment]
@RaulAlon Yes.

**Comment by RaulAlon** [comment]
Thanks @AndersAbel!
