### ISSUE TITLE
Having issues with Logout

### ISSUE THREAD

**Issue by kj1981** [Sustainsys/Saml2#852]
I have integrated kentor in my mvc application and using okta as the provider. I have setup okta and the login works all fine. It is the logout with which I am stuck and not able to proceed further.  Below is the code I use for logout:
`<a href="@Url.Action("../AuthServices/Logout", new { ReturnUrl = "/?Status=LoggedOut" })">Log out</a>.`

Below is my config file:

`  <kentor.authServices entityId="http://localhost:60041/AuthServices/" returnUrl="http://localhost:60041/">
    <identityProviders>
          <add entityId="http://www.okta.com/xxx" 
                  logoutUrl="http://localhost:60041/AuthServices/Logout?ReturnUrl=~/?Status=LoggedOut"   
                  signOnUrl="https://dev-xxx/app/xxx/xxx/sso/saml" allowUnsolicitedAuthnResponse="true" 
                  binding="HttpRedirect">
          <signingCertificate fileName="~/App_Data/okta.cert" />
        </add>
      </identityProviders>
    <serviceCertificates>
        <add fileName="~/App_Data/???.pfx" />
      </serviceCertificates>
    </kentor.authServices>`

My issue is as below:

At okta we are asked to provide the below details:
Single Logout URL:
SP Issuer:
Signature Certificate:

- How do we generated signature certificate?
- Is the signature certificate same as the web.config service certificate.

Now what happens is if we generated a self signed certificate using a private key it is generated as .pfx. If I try to upload the same certificate at okta it says "There was an error reading the certificate file" signed fields invalid". This certificate was generated using IIS then used openssl to give private key.

When I create a non private certificate it is generated as .cer which is uploaded fine by okta but when I click the logout button my application throws error: 
"Provided certificate is not valid because it does not contain a private key."

Not sure whats wrong we are doing here.
Would appreciate inputs.

**Comment by AndersAbel** [comment]
When creating a certificate you get both a pfx and a cer. The cer should be uploaded to Okta and the pfx is needed in the Saml2 config as the ServiceCertificate.
