### ISSUE TITLE
Incorrect serialization of the Assertion Consumer Service Url in the AuthnRequest

### ISSUE THREAD

**Issue by hoekj** [Sustainsys/Saml2#853]
When you use the Saml2AuthenticationRequest to create a AuthnRequest and call the ToXElement, the property AssertionConsumerServiceUrl is converted to a string using the ToString() method. This is incorrect, because the Uri.ToString() does a different type of encoding. Instead you should use the Uri.OriginalString to get a correct encoded string.

I'll submit a pullrequest to fix this.

**Comment by hoekj** [comment]
I get a 403 when i try to push a new branch. How can I submit the code change?

**Comment by AndersAbel** [comment]
@hoekj Make a fork to your own account, push to that fork and then create a PR.
