### ISSUE TITLE
SPOptions.RedirectUrl not working - Always using `/Account/ExternalLogin?handler=Callback`

### ISSUE THREAD

**Issue by Gillardo** [Sustainsys/Saml2#855]
Trying to use the returnPath property against spOptions as i do not want users to "register" but want to direct them to another piece of code which adds them to my database automatically. 

Upon trying to run the sample AspNetCore application i samples, and setting my own SAML values, upon successful login my site is always redirecting to `/Account/ExternalLogin?handler=Callback`.  I am setting it in my startup.cs file like so.

```
services.AddAuthentication()
	.AddSaml2(options => 
	{
		// organization
		var cultureInfo = System.Globalization.CultureInfo.GetCultureInfo("en-GB");
		var organization = new Organization();
		organization.Names.Add(new LocalizedName("my-company", cultureInfo));
		organization.DisplayNames.Add(new LocalizedName("my-company", cultureInfo));
		organization.Urls.Add(new LocalizedUri(new Uri("http://www.my-website.com"), cultureInfo));

		// certificates
		var spCertificate = new System.Security.Cryptography.X509Certificates.X509Certificate2("App_Data\\signcert.pfx", "my-password");

		// service provider
		options.SPOptions.Organization = organization;
		options.SPOptions.EntityId = new EntityId("https://www.my-domain.co.uk");
		options.SPOptions.ReturnUrl = new Uri("~/saml/success", UriKind.RelativeOrAbsolute);
		options.SPOptions.WantAssertionsSigned = true;
		options.SPOptions.ServiceCertificates.Add(spCertificate);

		var idp = new IdentityProvider(new EntityId("https://my.saml-ipd.co.uk"), options.SPOptions)
		{
			MetadataLocation = System.IO.Directory.GetCurrentDirectory() + "\\App_Data\\saml-metadata.xml",
			LoadMetadata = true
		};
	});
```
Upon looking it seems that line 142 in `Kentor.AuthServices\WebSso\SignInCommand.cs`, which reads
```
var returnUrl = string.IsNullOrEmpty(returnPath)
                ? null
                : new Uri(returnPath, UriKind.RelativeOrAbsolute);
```
Well `returnPath` is NEVER empty or NULL.  This value is passed all the way from the `ChallengeAsync` in file `Sustainsys.Saml2.AspNetCore2.Saml2Handler.cs`.  Here this method accepts `AuthenticationProperties` which always has `RedirectUri` set to `/Account/ExternalLogin?handler=Callback`.  I am guessing this is set by Microsoft?

To get round this, i have changed the above code in `Kentor.AuthServices\WebSso\SignInCommand.cs` at line 142 to read this instead.
```
var returnUrl = string.IsNullOrEmpty(returnPath)
	? null
	: new Uri(returnPath, UriKind.RelativeOrAbsolute);

// check if returnUrl setup against spd
if (options.SPOptions.ReturnUrl != null)
	returnUrl = options.SPOptions.ReturnUrl;
```
This way it is always set to `/Account/ExternalLogin?handler=Callback` but if the user is using `options.SPOptions.ReturnUrl` then it is overwritten.

Is this correct, or am i setting up something wrong?  If this is correct, is it ok to submit a PR with the change??

**Comment by AndersAbel** [comment]
Yes, you are setting up something wrong.

This is designed to prefer a dynamically registered return url from the challenge. The returnurl in the configuration should only be used if there either is no return url in the challenge or if this is an idp initiated sign on.

You should change your application so that it includes AuthenticationProperties with the right returnUrl set when issuing the challenge.

**Comment by Gillardo** [comment]
@AndersAbel so you have a property against spOptions that doesnt do anything? Can i have a basic example of what exactly you mean, because i dont see why this option exists if it doesnt do anything, or maybe i am supposed to set it somewhere else like you suggest.  Example would be helpful, as the AspNetCore2 sample doesnt show much at all

**Comment by AndersAbel** [comment]
@Gillardo It does things. But for ASP.NET Core2, it's only if you run idp initiated sign on. The spOptions is common to the all the api modules, including the HttpModule where things work a little differently.

In the ASP.NET Core2 model the return url is passed as part of the challenge that triggers the sign on. If you use ASP.NET Identity that is hidden in the SignInManager.

**Comment by Gillardo** [comment]
I do not have an "externalLogin" call on my controller and i do not use Identity....  Is this still possible??

**Comment by AndersAbel** [comment]
How do you trigger the login sequence?

**Comment by Gillardo** [comment]
@AndersAbel it seems i do use something that is like `ExternalLogin`.  I am trying to move over to your software, but by first getting it working in the example.  My real application uses an angular2 client ui, not an MVC asp.net one.  I will try this as you have said

**Comment by Gillardo** [comment]
Also, why you are here, when will you create a aspnetcore2 nugetspec file?  I need to create a nuget package for this and upload it to my own nuget server??

**Comment by Gillardo** [comment]
@AndersAbel any news on that nuget please?

**Comment by AndersAbel** [comment]
Nuget is published as https://www.nuget.org/packages/Sustainsys.Saml2.AspNetCore2/2.0.0-preview01
