### ISSUE TITLE
.NET Core 2 target support

### ISSUE THREAD

**Issue by dongigi92** [Sustainsys/Saml2#857]
Hi to all,

i have a question about the future of the project.
Are there plans for supporting the .NET Core 2 target?

I read the recent posts in #195, in particular: 
> [...] It only works on the full framework and not on .NET Core. [...]

I'd like to implements the SAML2 SSO into my project but, at the moment, not exist an open source library for .NET Core 2 target.

Do you think to working on it?

Thanks,
dongigi

**Comment by AndersAbel** [comment]
Yes, a .NET Core 2 target is on the way. It's currently in private beta for my paying customers.

**Comment by dongigi92** [comment]
There is a time target for the publication?

**Comment by dongigi92** [comment]
Is there a timeline for publishing?
