### ISSUE TITLE
Will SessionAuthenticationModule work in WebFarm scenario?

### ISSUE THREAD

**Issue by sanattiwari** [Sustainsys/Saml2#860]
SessionAuthenticationModule is used to establish the session after response comes from IdP.
This session data is stored in cookies, does it create any session object in server? will this work in WebFarm environment where-in request can go to any other server as well behind the Load Balancer?

Thanks!
Sanat

**Comment by AndersAbel** [comment]
The SessionAuthenticationModule uses a cookie on the client for all the data of the session. It works in a web farm environment as long as you have synchronized the machine keys.

**Comment by sanattiwari** [comment]
Hi Ander - SessionAuthenticationModule by default uses dataprotection APIs to protect the cookie which takes scope of current logged in user on that machine hence i think it will not work in web farm. For web farm we have to use machinekey data protection mechanism.
