### ISSUE TITLE
Dependent on IdentityModel 4.0.0??

### ISSUE THREAD

**Issue by Gillardo** [Sustainsys/Saml2#862]
Trying to add to my asp.net core site, which i do not reference Identity as well (using tokens using openIddict-core which separates from identity) and find myself not being able to use this because you MUST reference it?

This seems to be happening if i set my Organization and setting the EntityId, which are all classes defined in IdentityModel.

Would it not be better to create abstract classes to reference rather then depending on Identity??

**Comment by AndersAbel** [comment]
The current asp.net core release requires a reference to System.IdentityModel. The new version for .NET Core does not reference it, so I'm working on it. It is not ready for public release yet, but it's available in a private beta for paying customers with a valid support contract.

**Comment by Gillardo** [comment]
@AndersAbel do you have idea on when a "non identitymodel" would be released? i maybe interested in the private beta, depending on costs, if i can have access to non identityModel version.  Can you PM me details?

**Comment by AndersAbel** [comment]
@Gillardo I can't find a publicly listed e-mail for you. Mail me at anders@sustainsys.com
