### ISSUE TITLE
SLO with Okta

### ISSUE THREAD

**Issue by mattroot87** [Sustainsys/Saml2#866]
Hello,

 I am trying to configure SP-initiated SLO with Okta.  I have configured a signing certificate on my end and I have generated a logout request that is signed.  Lastly, I am configuring in Okta to send the Logout Response to mySite/AuthServices/Logout.  I am getting an error when it tries to post the saml responseto this location.  I have a feeling I am not sending Okta to the right endpoint for the response to be sent.  Any thoughts?  I can give more info if needed.

Thanks!

**Comment by AndersAbel** [comment]
What's the error message.

**Comment by mattroot87** [comment]
Received a LogoutResponse from http://www.okta.com/77777 that cannot be processed because it is not signed.

[UnsuccessfulSamlOperationException: Received a LogoutResponse from http://www.okta.com/77777 that cannot be processed because it is not signed.]
   Kentor.AuthServices.WebSso.LogoutCommand.VerifyMessageIsSigned(UnbindResult unbindResult, IOptions options) +953
   Kentor.AuthServices.WebSso.LogoutCommand.Run(HttpRequestData request, String returnPath, IOptions options) +375
   Kentor.AuthServices.WebSso.LogoutCommand.Run(HttpRequestData request, IOptions options) +249
   Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnPostAuthenticateRequest(Object sender, EventArgs e) +577
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +139
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91
--

I have Okta's cert on my server and they are telling me that the response does indeed come back signed.

Thanks!

**Comment by AndersAbel** [comment]
Can you include the query string/form data with the LogoutResponse?

**Comment by mattroot87** [comment]
My apologies for the delay.

POST https://mySite/APP/AuthServices/Logout HTTP/1.1
Host: myhost.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Length: 925
Content-Type: application/x-www-form-urlencoded
Upgrade-Insecure-Requests: 1
Cookie: ARRAffinity=7777; 
lang=en-US; SAML2IdentityHandlerReturnURL=https://mySite/APP/
Connection: keep-alive
 
HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000
Date: Wed, 06 Dec 2017 16:11:33 GMT
Content-Length: 5129
 
 
<saml2p:LogoutResponse xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                       Destination="http://mySite/APP/AuthServices/Logout"
                       ID="id7777"
                       InResponseTo="pfx7777"
                       IssueInstant="2017-12-06T16:11:32.197Z"
                       Version="2.0"
                       >
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                  Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                  >http://www.okta.com/7777</saml2:Issuer>
    <saml2p:Status>
        <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:AuthnFailed" />
    </saml2p:Status>
</saml2p:LogoutResponse>
 
POST
SAMLResponse: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOkxvZ291dFJlc3BvbnNlIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiBEZXN0aW5hdGlvbj0iaHR0cDovL2FwcHMuZWFzeXRlcnJpdG9yeS5jb20vZTA1OGIyMWYtZjkwYS00ZDQxLWI1MGItZDJjMDk4NzkwNjYxL0FQUC9BdXRoU2VydmljZXMvTG9nb3V0IiBJRD0iaWQxODIxNDA0MTA5MDE4NzYyNzE3MDg1NDE5NDkiIEluUmVzcG9uc2VUbz0icGZ4ZDRkMzY5ZTgtOWVhMS03ODBjLWFmZjgtYTFkMTFhOTg2MmExIiBJc3N1ZUluc3RhbnQ9IjIwMTctMTItMDZUMTY6MTE6MzIuMTk3WiIgVmVyc2lvbj0iMi4wIj48c2FtbDI6SXNzdWVyIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIiBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OmVudGl0eSI+aHR0cDovL3d3dy5va3RhLmNvbS9leGtkMW0yb2t5VnlQQXlNazBoNzwvc2FtbDI6SXNzdWVyPjxzYW1sMnA6U3RhdHVzPjxzYW1sMnA6U3RhdHVzQ29kZSBWYWx1ZT0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnN0YXR1czpBdXRobkZhaWxlZCIvPjwvc2FtbDJwOlN0YXR1cz48L3NhbWwycDpMb2dvdXRSZXNwb25zZT4=
RelayState:


I appreciate any insight you can bring.

-Matt

**Comment by mattroot87** [comment]
Hi Anders,

My main question is since I am doing a IdP-initiated login flow with Okta is it possible to do a SP-initiated Single Logout flow also?  Or must I have SP-initiated login in order to leverage SP-initiated logout.  
THanks!

**Comment by AndersAbel** [comment]
@mattroot87 Yes, you can choose SP or Idp-initiated for login and logout independently. So even if you do Idp-initiated login, you can do sp-initiated logout.

Looking at the Logout-response received, the error message is somewhat misleading. The logout response contains an error status code: AuthnFailed. My logout handler obviously does the signature check first, before checking the status (which might be the wrong order).

**Comment by mattroot87** [comment]
@AndersAbel  Thanks for the info.  What you are saying is that adjusting the logout handler check sequence might give us a better error message, correct?  

Where do you advise I go from here?  Continue to investigate if something is wrong with my certs or saml request.  Or is it an issue with the endpoint that I am trying to direct the logout response to- /AuthServices/Logout. 

Thank you very much.

**Comment by mattroot87** [comment]
This is the error message:
**User single sign out from app
failure: invalid Signature**

Just to confirm- what you are saying is that there isn't a problem on the Kentor side handling a SP-initiated logout in my case that I have described.  So, some issue with my signing certificate that I am generating from my server and uploading to Okta **_or_** the SAML request that I am appending to the logout URL- 
logoutUrl="https://oktaEndpoint/Guid/slo/saml/?SAMLRequest=guid here"

generate logout request steps:
1) Logout Request with embedded signature (HTTP-POST binding)
2) Deflate + Base64 Encode
3) URL Encode/Decode
4) Append to logoutURL

Is this the correct process?  
Thanks again

**Comment by AndersAbel** [comment]
You shouldn't generate the logout request yourself. Just hit mysite/AuthServices/Logout and the logout request, including the required signature will be generated for you.

**Comment by nareshbandameedi** [comment]
The below is the process to make SLO with HTTP Redirect binding
Encoding the query parameters should be done before generating the signature rather than after. For example, signature generation steps are as below:
1. queryStr = "SAMLRequest="+ UrlEncodeStr(logoutReqXML)+"&SigAlg="+UrlEncodeStr("http://www.w3.org/2000/09/xmldsig#rsa-sha1");
If you want to add you can add your relay state to above query parameters it should be like
queryStr = "SAMLRequest="+ UrlEncodeStr(logoutReqXML)+"&SigAlg="+UrlEncodeStr("http://www.w3.org/2000/09/xmldsig#rsa-sha1")+"&RelayState="+UrlEncodeStr(" some string you want to get back in logout response");
2. signatureStr = signQueryStr(queryStr);
3. b64Signature = encodeBase64(signatureStr);
4. finalReqURL = idpSLOUrl + "?" + queryStr + "&Signature=" + UrlEncodeStr(b64Signature);
redirect to finalReqURl

**Comment by AndersAbel** [comment]
Original issue is old. The latest comment by @nareshbandameedi is recent, but as far as I know the library already conforms to that. If you think not, please file a separate bug.

**Comment by nareshbandameedi** [comment]
@anitalad28  Hi, 
You can view the okta logs in the Reports section of Okta dashboard.
To Enable single log out you have to upload public certificate of the service provider to okta and You have to sign SAML logout request with the private key of the service provider.

**Comment by anitalad28** [comment]
Hi Naresh,

Thanks for your reply. 

I able to find okta logs and there I am getting 'signature failed' error.

Public vertificate of service provider -  I am attaching image which certificate I am uploading.
![certificate](https://user-images.githubusercontent.com/42993522/45199684-ac416d00-b28a-11e8-8d54-0c631a85f8e6.png) - Am I doing this wrong?

even at saml20-idp-hosted.php I have okta certificate which I have downloaded from okta sign on tab. 
// X.509 key and certificate. Relative to the cert directory.
	'privatekey' => '',
	'certificate' => 'okta.cert',

Kindly find attached logoutRequest andResponse
[logoutRequstResponse.txt](https://github.com/Sustainsys/Saml2/files/2359603/logoutRequstResponse.txt).

Kindly help.

**Comment by nareshbandameedi** [comment]
@anitalad28 Could you please check the SAML logout request here https://www.samltool.com/sign_logout_req.php
and validate SAML logout request here https://www.samltool.com/validate_logout_req.php. If something is wrong with your certificates generate your self signed certificates here https://developers.onelogin.com/saml/online-tools/x509-certs/obtain-self-signed-certs and verify it back.

**Comment by anitalad28** [comment]
Hi Naresh, 

Thanks a lot. 

Your links helped me to fix the issue.  First issue with the certificate, then sp issuer which I was adding in okta.

A big thanks,
Anita

**Comment by bubigen** [comment]
Hi @anitalad28 

I'm having the same issue as yours. Pretty much the same request and response XML. Can you please specify how did you fix this? Is there any part in certificate creation I have to look at?

Help is much appreciated!
Thanks!
