### ISSUE TITLE
How to handle the SAML assertions ?

### ISSUE THREAD

**Issue by shahrozkhan26** [Sustainsys/Saml2#867]
Hi Anders,

Previously i have implemented an IDP to sent SAML IDP initiated Post Binding Requests to a service provider. Now i need to implement a Service provider so our partners can send an idp request to our service provider. I went through the documentation for implementing the service provider in mvc application. The document is very well written. However i was not able to find "how to handle saml assertions from idp". Basically i need to authenticate the users from my client's web service. The idp will be sending username and password as SAML assertion parameters. I will appreciate if you can help me o n "how to receive saml assertions as a service provider". Hoping to get a response from you.

Thanks

**Comment by AndersAbel** [comment]
I don't understand what you are trying to do. And you should never be sending a password in a SAML assertion.

**Comment by shahrozkhan26** [comment]
Sorry if my question was not clear earlier. Actually i want to perform some operations on the SAML assertion parameters which IDP will send with "IDP inititated request" to the Service Provider. As a service provider, How will i get the saml assertion parameters in my service provider and perform some operations with it using (Kentor.AuthServices.MVC). In the sample MVC application you provided, i do not see any saml assertion. I am not able to figure out how i can do this.  Please advise.

**Comment by AndersAbel** [comment]
To allow idp initiated requests you need to set `AllowUnsolicitedResponses=true`.

The assertion is converted to claims by the library, so check the generated claims identity, it should contain the information you are looking for.

**Comment by shahrozkhan26** [comment]
Thank You for helping.
