### ISSUE TITLE
"ResponseLocation" missing from <SingleLogoutService>

### ISSUE THREAD

**Issue by saqibmushtaq** [Sustainsys/Saml2#869]
Hi there,

using kentor.AuthServices 0.21.2.0, I have configured the IdP property "idp.SingleLogoutServiceResponseUrl" via code and was hoping to see this in action but kentor package still forwards me to the default location of the page where I do Owin Sigout, instead of redirecting me to this page.

Moreover, "ResponseLocation" attribute is missing from the generated SP Metadata as well. Can you please advise? Thanks.

regards,
Saqib

**Comment by AndersAbel** [comment]
First you must create a signing certificate for your SP, without that, logout is not enabled (which it looks like you've done)

ResponseLocation isn't needed - AuthServices uses the same location for both requests and responses and the ResponseLocation is only needed if it is different to the request location.

To trigger single logout, you *should* do an ordinary owin signout which then triggers the saml2 single logout. Step through the the SampleOwinApplication in the repo to see this in action.

**Comment by saqibmushtaq** [comment]
Thanks for the reply.
yes, I can confirm that I have configured the certificate for logout action.

That's right, that's the default behaviour that AuthServices uses the same location for request and response but I deliberately wanted to redirect response to a different location. 

"ResponseLocation" attribute is missing from the generated SP Metadata as well. I recon this will be useful in auto-populating the IdP configurations and can be helpful while setting auto-monitoring of SP Metadata by IdP Server.????

Just to confirm, to trigger signout, I simply do the OwinContext.Authentication.SignOut().
