### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#872]
The build on master is broken, the test run fails with a message `vstest.console.exe : Could not find a test logger with URI or FriendlyName 'appveyor'.`. Looks like some appveyor error, I'm investigating.

**Comment by stevewhite** [comment]
thanks...

**Comment by AndersAbel** [comment]
The appveyor log issue is found, now the code coverage is not found however... investigating.

**Comment by AndersAbel** [comment]
Can't get both appveyor logger and code coverage to work on the same time. For now I settled with the code coverage to get build an PR validation running. This means however that the tests doesn't show up as listed in appveyor tests. Leaving the issue open until I (or someone else?) has time to fix it.

**Comment by AndersAbel** [comment]
Workaround is listed in the Appveyor ticket, next on todo is to try it.

**Comment by AndersAbel** [comment]
Build moved to GitHub Actions and works.
