### ISSUE TITLE
StubIdp form controls unreadable in macOS Safari

### ISSUE THREAD

**Issue by duncansmart** [Sustainsys/Saml2#874]
See attached screenshot.

<img width="1012" alt="screen shot 2017-12-20 at 2 41 17 pm" src="https://user-images.githubusercontent.com/576343/34212666-edce0134-e594-11e7-82c7-17269e5ac409.png">

The following CSS for `.form-control` style is more legible:

```
.form-control {
    font-size: 22px;
}
```

<img width="538" alt="screen shot 2017-12-20 at 2 49 56 pm" src="https://user-images.githubusercontent.com/576343/34212729-20007858-e595-11e7-9f31-a6b5f05a6676.png">

**Comment by AndersAbel** [comment]
Two things for the record:
1. Thanks for filing this, I didn't test this in Safari.
2. I hate CSS.

Initially I had the same issue in Internet Explorer and that was solved by using a `line-height: 0.8px`, I'll see if this can be solved for Safari using something similar (I have an ipad, that shows the same issue so I can test it)

**Comment by AndersAbel** [comment]
Looks like messing with line-height doesn't work all the way. Going with 22px as you suggested, but still need to keep the line-height for IE to be happy.
