### ISSUE TITLE
bindingUriMap doesn't have an entry for HttpRedirect binding

### ISSUE THREAD

**Issue by chirankavinda123** [Sustainsys/Saml2#876]
I tried to generate a saml request using the class  **SAML2AuthenticationRequest**. I tried with protocol binding type Http Post binding and it worked pretty well. But when i set the protocol binding to Http redirect binding it fails since **_bindingUriMap doesn't have an entry for HttpRedirect binding_**

which cause to throws out an exception at https://github.com/Sustainsys/Saml2/blob/master/Kentor.AuthServices/WebSSO/Saml2Binding.cs Line number 211.

**Comment by AndersAbel** [comment]
Please include the stack trace of the exception.

**Comment by chirankavinda123** [comment]
[ArgumentException: Unknown Saml2 Binding Type "HttpRedirect".]    Kentor.AuthServices.WebSso.Saml2Binding.Saml2BindingTypeToUri(Saml2BindingType type) +169    Kentor.AuthServices.Saml2P.Saml2AuthenticationRequest.ToXElement() +206    Kentor.AuthServices.Saml2P.Saml2AuthenticationRequest.ToXml() +8    sample.saml.SAML2SSOManager.buildRedirectRequest() in C:\Users\chira\source\repos\sample\sample\saml\SAML2SSOManager.cs:85    sample.FilteringHttpModule.onApplicationBeginRequest(Object sender, EventArgs e) in C:\Users\chira\source\repos\sample\sample\FilteringHttpModule.cs:37    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +71
--

**Comment by AndersAbel** [comment]
Is it the `Saml2AuthenticationRequest.Binding` that you are setting? It is used to indicate to the Idp what binding to use when sending the response. Using Redirect for a SAML2 response generally won't work as a response is too large for that binding. And AuthServices doesn't support receiving Responses over Redirect.

If you want to alter the binding used to send the outbound AuthnRequest you should just use a a different binding to create the `CommandResult`.

But all of this are details that you should normally not do yourself, use the HttpModule, Mvc or Owin packages instead that wraps all of this in convenient APIs instead.
