### ISSUE TITLE
Asp.Net Core2 handler without AuthProps

### ISSUE THREAD

**Issue by AndersAbel** [Sustainsys/Saml2#879]
If there is no ReturnUrl in AuthProps, or the AuthProps is entirely missing, use current Url as RedirectUri. This is how the [Authorize] attribute works. This is consistent with how the OIDC handler works.

**Comment by twenzel** [comment]
Any progress on this issue?

**Comment by lol768** [comment]
:+1: This is a blocker for my particular use-case

**Comment by osdev25** [comment]
Hi Anders, 
you mentioned you not using AuthenticationHandler base class , any reason why ? public Task<AuthenticateResult> AuthenticateAsync()
             throw new NotImplementedException();
         }

im more interested on authenticateAsync

**Comment by AndersAbel** [comment]
The reason to not use the AuthenticationHandler is that it duplicates a lot of the infrastructure already implemented in the base library, so I found it confusing.

Please open a new issue of the AuthenticationAsync method is needed.
