### ISSUE TITLE
Looping: Kentor not 'processing' SAML Response into User.Identity.IsAuthenticated

### ISSUE THREAD

**Issue by PittCaleb** [Sustainsys/Saml2#880]
I believe we have a working Kentor / Okta configuration.  

Through Chrome developer tools, I see it returning from Okta with avalid SAML assertion. it then redirects to my localhost/default.aspx which, based on sample code, performs a check of User.Identity.IsAuthenticated which is not set, thus it goes back to Okta for authentication and thus loops infinitely.

What am I missing that's getting Kentor to properly consume the SAML response and set my VB project up with the data correctly.  The structure System.Security.Claims.ClaimsPrincipal.Current.Claims conatins nothing but a 'local' claim.

From web.config:
    <authentication mode="Forms">
      <forms loginUrl="http://localhost:2018/Default.aspx" />
    </authentication>

  <kentor.authServices entityId="http://localhost:2018/AuthServices" returnUrl="http://localhost:2018/Default.aspx" authenticateRequestSigningBehavior="Never">

Chrome Tools tells me:
Request URL:http://localhost:2018/AuthServices/Acs has the SAML resposne (decodes to be correct)

in the Network log, after hitting Acs, it goes to my main site page, default.aspx.  There is no SAML passed through from a browser POV.  After hitting default.aspx, it redirects to Okta again for auth since it doesn't think it's logged in.

TIA - caleb

**Comment by nicswan** [comment]
When I had a similar issue, it was due to an error in a role manager I hadn't noticed was enabled. If you're using any role managers, I would disable those then see if you still have the same issue. Here's a link to info about my issue, in case it is of help: https://github.com/Sustainsys/Saml2/issues/684

**Comment by in10se** [comment]
I'm experiencing the same issue. The first time it works perfectly fine. Thereafter it keeps looping. It sure seems like a bug.

**Comment by AndersAbel** [comment]
@PittCaleb @in10se If this isn't the role manager issue @nicswan mentions but something else, can you please enable logging in AuthServices/Saml2 and post the results here? I need something more substantial to be able to find out what the issue is.

**Comment by in10se** [comment]
@AndersAbel 
I've managed to isolate the issue. In the function that gets called after returning from ADFS I was setting a session variable and then redirecting to another function in another controller. By not setting that session variable I was able to completely avoid any looping. 

I'd like to debug this further. How can I turn on logging?

**Comment by AndersAbel** [comment]
@in10se Sounds like a cookie monter issue (I assume you're using Owin?) https://coding.abel.nu/2014/11/catching-the-system-webowin-cookie-monster/

**Comment by in10se** [comment]
@AndersAbel I think you may be right. It does seem like that's what happens. I don't have time to test this right now but I'll try to revisit the issue at some point.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
