### ISSUE TITLE
Memory issues netstandard branch

### ISSUE THREAD

**Issue by Gillardo** [Sustainsys/Saml2#882]
I am not 100% sure, but i think there is either a memory leak or this code uses a lot of memory?

I have implement this code within our web application, and you can turn on/off the SAML functionality. There are about 10 copies of this application, 1 of which uses the SAML functionality. Our website usually takes up about 295-305mb on RAM to run. The one version with SAML running takes up 550-600mb of RAM.

Do you know why this would be? I am guessing it should not have such a big footprint??

**Comment by AndersAbel** [comment]
@Gillardo I updated the title, as I assume this relates to the .NET Core version?

**Comment by Gillardo** [comment]
Yes, sorry

**Comment by AndersAbel** [comment]
The net standard branch will be deprecated in favour of the PR in #939
