### ISSUE TITLE
is configured for signed AuthenticateRequests, but ServiceCertificates configuration contains no certificate with usage "Signing" or "Both". To resolve this issue you can a) add a service certificate with usage "Signing" or "Both"

### ISSUE THREAD

**Issue by msekkappan** [Sustainsys/Saml2#883]
I am getting this error...

is configured for signed AuthenticateRequests, but ServiceCertificates configuration contains no certificate with usage "Signing" or "Both". To resolve this issue you can a) add a service certificate with usage "Signing" or "Both" (default if not specified is "Both") or b) Set the AuthenticateRequestSigningBehavior configuration property to "Never".
  Source=Kentor.AuthServices

I have this code...
            ServiceCertificate se = new ServiceCertificate()
            {
                Certificate = new X509Certificate2("Kentor.AuthServices.Tests.pfx"),
                Use = CertificateUse.Signing
            };

            SPOptions sp = new SPOptions();
            sp.AuthenticateRequestSigningBehavior = SigningBehavior.Always;
            sp.EntityId = new EntityId("https://localhost/Test/AuthServices");
            sp.ReturnUrl = new Uri("https://localhost");

            IdentityProvider idp = new IdentityProvider(new EntityId("https://test"), sp);
            idp.Binding = Saml2BindingType.HttpPost;
            idp.WantAuthnRequestsSigned = true;
            idp.SingleSignOnServiceUrl = new Uri("https://test");
            //idp.LoadMetadata = true;
            idp.SigningKeys.AddConfiguredKey(new X509Certificate2("test.pem"));

            services.AddAuthentication()
                .AddSaml2(options =>
                {
                    options.SPOptions.ServiceCertificates.Add(se);
                    options.IdentityProviders.Add(idp);
                });

LIne 115 in signincommand.cs             IdentityProvider idp = options.Notifications.SelectIdentityProvider(idpEntityId, relayData); is not pulling in the passed idp.  It pulls the default IDP with no service certificate.  But, the options passed in the coomandResult has the service certificate.  What is it wrong with the configuration setup?

**Comment by explunit** [comment]
are you missing a line where you add `se` to your `sp.ServiceCertificates`?

**Comment by msekkappan** [comment]
Adding sp.ServiceCertificates.Add(se); before the idp initialization fixed the problem
