### ISSUE TITLE
IsAuthenticated is allways false

### ISSUE THREAD

**Issue by Strypenbever** [Sustainsys/Saml2#884]
Hi!
I'm trying out the kentor Idp to see if I can get it working with a new web forms project before I try it out in a real project.

I’m adding the nuget packages for Kentor.AuthServices and Kentor.AuthServices.HttpModule (do I need all four nuget packages?). And then all the configurations in web.config (I change to my localhost and the new website stubidp.sustainsys.com), downloaded and added the certificate. But when I return to the Default.aspx page from the Idp IsAuthenticated is always false. 

I have used SAML Chrome Panel and I get an SAML response back. 
Do I need to add some more code in the Default.aspx page besides an check for User.Identity.IsAuthenticated?

Thx for the help!

**Comment by AndersAbel** [comment]
1. You only need the Kentor.AuthServices and Kentor.AuthServices.HttpModule packages.
2. Turn on logging by setting a logger adapter on `Saml2AuthenticationModule.Options.SpOptions.Logge` to see what happens after the SAML response is received.
