### ISSUE TITLE
Sample Sustainsys.Saml2.AspNetCore2 without use of identity stores

### ISSUE THREAD

**Issue by msekkappan** [Sustainsys/Saml2#885]
Is there a sample without the use of identity stores, the old MVC samples do not require DB storage, but the Core2 requires the use of stores.  I am looking for a sample without the DB.  Is there a such a thing?

**Comment by AndersAbel** [comment]
No, there is no such sample, but it should be possible to use any external auth sample for Core2 to see how an external handler is registered. Note that #879 will prevent automatic login from `[Authorize]` attributes from working right now.
