### ISSUE TITLE
SAML2 Full .Net Core Version

### ISSUE THREAD

**Issue by bitbybitllc** [Sustainsys/Saml2#887]
Does a version of this toolkit exist that doesn't have the full .net dependency and is compatible with just 2.0? 

Last I saw earlier last week it was mentioned that this was in the works but not publically available.

**Comment by AndersAbel** [comment]
Yes, it's in the netstandard branch (despite the name it currently targets netcoreapp20). There's also a nuget https://www.nuget.org/packages/Sustainsys.Saml2.AspNetCore2/2.0.0-preview01

**Comment by tgreco** [comment]
Thank you very much.  

One last question, would you be able to point me to some documentation or at least a nudge in the right direction on how to integrate this with Okta/SAML without using my own identity server?
