### ISSUE TITLE
AspNetCore Preview Saml2ClaimTypes does not exist

### ISSUE THREAD

**Issue by bitbybitllc** [Sustainsys/Saml2#889]
In the externalLogin.cshtml.cs file there is a CreateAsync task and this line causes an error:

` var logoutInfo = _externalLoginInfo.Principal.FindFirst(Saml2ClaimTypes.LogoutNameIdentifier);`

Saml2ClaimTypes is not defined in the Saml2 library.

**Comment by AndersAbel** [comment]
@Bidou44 What sample application is this in? Is it in the netstandard branch?

**Comment by bitbybitllc** [comment]
Ah I mixed my branches up from where I was getting the samples.

Question though, the localhost:port/Saml2 page.  Where is that defined in the project?

**Comment by AndersAbel** [comment]
The entire /Saml2 virtual directory (or whatever ModulePath you've set) is handled by the Saml2 Handler. You won't see it as a page or controller/action.

**Comment by bitbybitllc** [comment]
Gotcha.  I'm trying to decompose the project a bit so that I can use it in an existing application.

What functions/classes in your (Fantastic) library should I look at in terms of decomposing this into two functions, a sendSAMLRequest() and receiveSAMLResponse()?  I've been stuck on this for a day or so.

**Comment by AndersAbel** [comment]
Normally you shouldn't do that yourself, but rely on the OWIN or ASP.NET Core handler API. But if you want to, check the `SignInCommand` and `AcsCommand`, those are the entry points.

**Comment by bitbybitllc** [comment]
I agree and I would much rather stick to the API you've setup.  However my application doesn't have a startup.cs file which is why I can't stick to the API.  It's a .Net 3.5 application.

**Comment by AndersAbel** [comment]
If it's a legacy ASP.NET application you can use the http module package.

**Comment by bitbybitllc** [comment]
I'm definitely going to try to get this working using the HTTP module now. 

I see all the configuration is done in the Web.config.  where in the HTTP Module sample does it demonstrate how to actually call the SAML login ?

**Comment by AndersAbel** [comment]
The login sequence is exposed at ~/Saml2/SignIn.

**Comment by bitbybitllc** [comment]
Ah I think I see. So you just setup the Url.context to point to the Saml2 virtual directory and that will handle moving the user to the IDP (say Okta for example).  

How do you handle the response in the HTTP module to verify if a User.Identity.IsAuthenticated is true? 

I have a different authentication model than using Identity so I'd like to be able to run an function after successfully returning back from Okta.

**Comment by bitbybitllc** [comment]
My legacy ASP.NET application is targeting .Net framework 2.0.  
Is it possible to use this HTTP module inside of it or is that going to be an issue since it uses .Net framework 4.6?

**Comment by AndersAbel** [comment]
This thread i starting to get a bit too long for me to be able to answer for free. Please mail me at anders@sustainsys.com if you are interested in commercial support offerings where I can spend more time to write more in depth answers.
