### ISSUE TITLE
How to use SAML2 without Identity store .Net Core

### ISSUE THREAD

**Issue by bitbybitllc** [Sustainsys/Saml2#890]
The .Net core sample app is heavily relying on the Identity store.  

I was curious how I can use this without the identity store and use cookies for example?

I read your blog post here: https://coding.abel.nu/2014/11/using-owin-external-login-without-asp-net-identity/

But how can I do it as UseCookieAuthentication is obsolete now so we have to use:

services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme);

But wouldn't this overwrite the AddAuthentication(AddSaml2) method?

I gave it a shot and whenever I return to ExternalLogin's OnGetCallbackAsync method I am still treated as logged out for some reason.

**Comment by msekkappan** [comment]
I have a similar case that we do not want to use the Identity DB tables

**Comment by AndersAbel** [comment]
It is possible to set this up, using the ASP.NET Core2 module as an external provider without identity. The #879 bug could affect such a setup though. I do currently not have a sample for that. If you want help to get going, mail me at anders@sustainsys.com for my commercial support offerings.

**Comment by osdev25** [comment]
Hi i tried to implement similar approach , thought i got it working but obviously not . 

i get this error when  i use this config :
No IAuthenticationSignInHandler is configured to handle sign in for the scheme: Saml2

 services.AddAuthentication().AddCookie()
                     .AddSaml2(options =>.....

but when i use 
       services.AddAuthentication(o=> { o.DefaultAuthenticateScheme = Saml2Defaults.Scheme; }).AddCookie()

i get this , 

NotImplementedException: The method or operation is not implemented.
Sustainsys.Saml2.AspNetCore2.Saml2Handler.AuthenticateAsync()
