### ISSUE TITLE
How to utilize ForceAuthn when using HttpModule version with non-MVC application

### ISSUE THREAD

**Issue by nicswan** [Sustainsys/Saml2#891]
Hi - I have this library working with a couple apps using ADFS as the identity provider. Now for one app (which is using the Http Module) I have need to include ForceAuthn in the SAML requests. The application is an older non-MVC application. I've read through the code and the pull request for the code that added ForceAuth capability, but it's unclear to me how I can utilize the notifications extension in my HttpModule, non-MVC, non-OWIN scenario. Can anyone point me in the right direction? Thanks!

**Comment by AndersAbel** [comment]
@nicswan You can set the notifications from code, i.e. in `Application_start` in global.asax.cs. The options are available at `Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.Options.Notifications`.

**Comment by nicswan** [comment]
I should have been more specific. Finding the notifications options was straight forward enough, using them less so (at least for me). Plus I then needed to translate it to VB for use in my app.

For any other poor souls who need to do this in VB, here's an example:

```
'Example Application_Start function for Global.asax.vb
Sub Application_Start(ByVal sender As Object, ByVal e As EventArgs)
 Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.Options.Notifications.AuthenticationRequestCreated = Function(request, identity, dictionary)
                                                                                                                          request.ForceAuthentication = True
                                                                                                            End Function
End Sub
```

**Comment by AndersAbel** [comment]
@nicswan Thanks for posting back sample code.
