### ISSUE TITLE
Metadata loading for For net-standard (ASP NET Core)

### ISSUE THREAD

**Issue by bitbybitllc** [Sustainsys/Saml2#892]
Is it possible to load meta data url to avoid having to pass in an IDP public key cert every time?

**Comment by AndersAbel** [comment]
I'm planning to add that functionality yes, but it will not be in the first non-preview release.

**Comment by AndersAbel** [comment]
There's no current issue for this functionality, so I'm reopening this one as the feature request.

**Comment by andreujuanc** [comment]
I'd love to have this. so I can migrate to dotnet core :)

**Comment by robertgins** [comment]
+1 on this issue for me as well

**Comment by AndersAbel** [comment]
This is part of #939 that will be merged.
