### ISSUE TITLE
redirects to the provider URL, returns HTTP 302 but not triggering the callback

### ISSUE THREAD

**Issue by msekkappan** [Sustainsys/Saml2#893]
Have this code in the controller...
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ExternalLogin(string provider, string returnUrl = null)
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            // Request a redirect to the external login provider.
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "", new { returnUrl });
            ViewData["ReturnUrl"] = returnUrl;
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            var rtnCode = Challenge(properties, provider);
            return rtnCode;
        }

Redirects to the provider URL, returns 302, but does not get in to the ACSCommand.cs run method.  Any ideas?  I am not using the Identity DB tables as we do not want register users or store in the DB.  Therefore, I do not have the migration tables under data folder and I do have this code in the startup.cd

            services.AddAuthorization();
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

**Comment by AndersAbel** [comment]
Does the browser display the Idp? What happens next, does the Idp redirect/POST back?

**Comment by msekkappan** [comment]
Yes, the browser displays the Idp?  Idp redirects, but it does not hit the run method in ACSCommand

**Comment by AndersAbel** [comment]
What adress does the Idp redirect to?

**Comment by msekkappan** [comment]
https://<dev>/Saml2/Acs, shows 302, hitting directly to this URL does not work which tells me that API is not available.

**Comment by AndersAbel** [comment]
Looks like something is wrong in your Idp then. Can you try to connect to the stubidp at https://stubidp.sustainsys.com first to make sure your setup works?

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
