### ISSUE TITLE
Password protected certificate file. Provite password attribute for serviceCertificates element

### ISSUE THREAD

**Issue by aleha84** [Sustainsys/Saml2#897]
My Config section looks like this:
```
<serviceCertificates>
      <add fileName="~/App_Data/keystore.pfx" use="Signing" status="Current" />
</serviceCertificates>
```

keystore.pfx is password protected file. 
Here: https://github.com/Sustainsys/Saml2/blob/940644de50fa981caa31f5e5d6e8c8a1dea401bc/Sustainsys.Saml2/Configuration/CertificateElement.cs#L113 
No password provided to constructor, just empty string. 

Please add attribute like "filePassword" and pass its value to X509Certificate2 constructor.

**Comment by AndersAbel** [comment]
Putting the password in the config file won't give any extra security. If anyone can grab the `keystore.pfx` file, they can also grab the `web.config` and get the password. Unless you are using encrypted sections, but nobody does in real life.

For a production environment you should put the certificate in the certificate store and give the app pool user appropriate access rights.

**Comment by kevinlow1926** [comment]
I still think having an attribute for password is a good idea. In our local testing we shouldn't have to install certificate in the certificate store.

**Comment by varadharajanmadhav** [comment]
> Putting the password in the config file won't give any extra security. If anyone can grab the `keystore.pfx` file, they can also grab the `web.config` and get the password. Unless you are using encrypted sections, but nobody does in real life.
> 
> For a production environment you should put the certificate in the certificate store and give the app pool user appropriate access rights.

How to use certificate store certificates in <serviceCertitificates> element?

**Comment by ymlai87416** [comment]
I am writing to ask you to reconsider reopening this issue and add back the password attribute to serviceCertificates element.

It is because it is not possible to export a certificate without a password in Windows 10 environment.

**Comment by Harvinator** [comment]
> > Putting the password in the config file won't give any extra security. If anyone can grab the `keystore.pfx` file, they can also grab the `web.config` and get the password. Unless you are using encrypted sections, but nobody does in real life.
> > For a production environment you should put the certificate in the certificate store and give the app pool user appropriate access rights.
> 
> How to use certificate store certificates in "serviceCertitificates" element?

This would be useful to add to the documentation because it's really not clear how to use this. The documentation doesn't refer to fileName attribute. I found that in the sample but I can't see a sample that uses the certificate store anywhere
