### ISSUE TITLE
Null "GetExternalLoginInfoAsync" using OwinApplication

### ISSUE THREAD

**Issue by himalpatel81** [Sustainsys/Saml2#899]
I am using SampleOwinApplication with OneLogin. The application gets redirected to OneLogin for the authentication and getting the post response on ExternalLoginCallback url. However, when AuthenticationManager is trying to getExternalLoginInfo, it gets null. 

I'm using "SampleOwinApplication.

Thanks,
Himal

**Comment by vidhyasagarreddy** [comment]
Even am facing same issue.

**Comment by himalpatel81** [comment]
I found that the cookie is coming null for whatever reason and thus the GetExternalLogin is returning null. but still have no idea on why Cookie is coming null.

**Comment by AndersAbel** [comment]
Check if the ExternalCookie is properly set. It might be an owin cookie monster issue https://coding.abel.nu/2014/11/catching-the-system-webowin-cookie-monster/

**Comment by vidhyasagarreddy** [comment]
Tried to go with workaround you provided with package, but seems like package is not targeted to **Fx4.5**.
Here's error message that i received:
**Could not install package 'Kentor.OwinCookieSaver 1.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

**Comment by AndersAbel** [comment]
@vidhyasagarreddy Upgrade your project's target to at least 4.5.2.

**Comment by vidhyasagarreddy** [comment]
mm.. That would be the last option. For now, am capturing ExternalLoginInfo in a different way.

**Comment by AndersAbel** [comment]
Looks like this issue is not related to the Saml2 component, closing.
