### ISSUE TITLE
Single Logout without SessionIndex

### ISSUE THREAD

**Issue by vidhyasagarreddy** [Sustainsys/Saml2#900]
When I use
**HttpContext.GetOwinContext().Authentication.SignOut()**
User is supposed to be Signed out from IdP as well. But this is not happening. Do we need **_http://Sustainsys.se/Saml2/LogoutNameIdentifier_** claim ? I found this inside IntiiateLogout method inside LogoutCommand.cs.

**Comment by AndersAbel** [comment]
Yes, the SessionIndex and LogoutNameIdentifier claims must be present to initiate a SLO. There must also be a service certificate configured. If you enable logging, you'll see a message with all the checks required for a federated SLO and which of them pass.

**Comment by vidhyasagarreddy** [comment]
Just checked & those claims are not auto-created as its missing SessionIndex at:
statement.SessionIndex
in ProcessAuthenticationStatement method in Saml2PSecurityTokenHandler.cs

**Comment by AndersAbel** [comment]
Looks like this might be a bug, I thought that SessionIndex is required in order to do a single logout, but apparently it's optional. Updating the title and marking this as a bug.

Can't promise any fix date though as the backlog is long. Mail me at anders@sustainsys.com if you want to discuss commercial options to get this fixed soon.

**Comment by vidhyasagarreddy** [comment]
Assuming, if I assign some dummy value to **SessionIndex**, will it effect anything ?

**Comment by AndersAbel** [comment]
@vidhyasagarreddy I don't think it's a good idea as that dummy value would be put into the LogoutRequest message sent to the Idp.

**Comment by vidhyasagarreddy** [comment]
Yeah, I understand that but just wanted to confirm if it breaks something in flow. I tried this against SalesForce and it worked.

**Comment by AndersAbel** [comment]
Hmm... checking up another part of the spec. And the current code is actually right, an Idp that supports Single Logout MUST supply a SessionIndex:

SAML2 Profile spec, section 4.1.4.2
> If the identity provider supports the Single Logout profile, defined in Section 4.4, any authentication statements MUST include a SessionIndex attribute to enable per-session logout requests by the service provider.

So the Idp is wrong in this case. If needed, it might be added as a compatibility setting though to allow for non-conforming Idps.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
