### ISSUE TITLE
statement.SessionIndex is null and hence SessionIndex and LogoutNameIdentifier Claims are not being created

### ISSUE THREAD

**Issue by vidhyasagarreddy** [Sustainsys/Saml2#901]
Seems like **_statement.SessionIndex_** is **_null_** and hence **SessionIndex** and **LogoutNameIdentifier** Claims are not being created

**Comment by AndersAbel** [comment]
This doesn't make sense on it's own, please don't create extra issues for things already being discussed. Keep this to #900.
