### ISSUE TITLE
Setting MetadataLocation for AspnetCoreApp

### ISSUE THREAD

**Issue by abdomohamed** [Sustainsys/Saml2#902]
I'm trying to setup Saml2 with IdentityServer4 which is a .netcore app. My question is how to set MetadataLocation because I couldn't figureout which proprty to use. Also I've seen in the code that LoadMeatdata property is only available for .net 4.5 build, which means if my app supports only .netcore it's going disappear.

Thanks for your help and support.

**Comment by kjbetz** [comment]
I believe Issue #892 is talking about this and it currently isn't in there. I would like this as well. In an early version I used the MetadataLocation as a file and then LoadMetadata... now I'm doing it manually.

**Comment by abdomohamed** [comment]
Thanks @kjbetz.  :)
