### ISSUE TITLE
Could not load file or assembly Kentor.AuthServices 

### ISSUE THREAD

**Issue by shahrozkhan26** [Sustainsys/Saml2#904]
Hi @AndersAbel, 

I integrated Kentor.AuthServices project in my solution. I did not use the nuget package for Kentor as the site i am working on does not use ASP Identity. Everything works fine in localhost. After deploying the site i found the following error.
"Could not load file or assembly 'Kentor.AuthServices' or one of its dependencies. An attempt was made to load a program with an incorrect format."

How can i resolve this issue? I tried adding the dependent assembly attribute in web.config but that does not help. Please guide.

**Comment by AndersAbel** [comment]
1. You can use the nuget even though you are not using ASP.Net Identity.
2. If you get a reference to Kentor.AuthServices you're not using the latest stable release (0.23.0, which you should use)
3. If you have built it yourself, I can't tell you what's wrong. Use the Nuget.
