### ISSUE TITLE
FedAuth cookies not get send back to returnUrl, cause a infinite url redirection

### ISSUE THREAD

**Issue by zhangming870** [Sustainsys/Saml2#905]
Hi experts,

In my case, the Saml2/Acs end point correctly process everything, send back the access token, keep it in cookie, makes a redirection to my landing page.    But landing page( the redirection url) is under a path, like http://site.com/path. and my cookie under the "path" is not sent back..,  which causes my application thinks user not authenticated yet, thus redirect to signin endpoint again and again.    My issue is very much similar to this guy https://github.com/Sustainsys/Saml2/issues/226 

In that post, you said you have fixed that issue, is there anything I need to configure for that?
Is this a browser setting thing or the sustainsys need a special tweak?

Thanks in advance!

**Comment by AndersAbel** [comment]
Looking at that post, it was a trailing slash mismatch issue between the configured redirect path and the cookie path. Check the set-cookie header in the 302 response from the Acs endpoint and the subsequent request to http://site.com/path. If it is the same as #226, the set-cookie header is restricted to `http://site.com/path/`

If you need further assistance to debug this, I'd be happy to do that as part of my commercial support offering. Please mail me at anders@sustainsys.com för information.
