### ISSUE TITLE
SessionNotOnOrAfter

### ISSUE THREAD

**Issue by raizarachi** [Sustainsys/Saml2#906]
Would it be possible, when there is no SessionNotOnOrAfter in the Saml2AuthenticationStatement objects, to use the saml2:Conditions NotOnOrAfter ?

Or at least to let this value be accessible even when the Saml response is encrypted ?

**Comment by AndersAbel** [comment]
@raizarachi No, you definitely don't want to use the Conditions NotOnOrAfter. As that is typically a much shorter time frame than the SessionNotOnOrAfter. See https://stackoverflow.com/questions/29508906/notonorafter-in-subjectconfirmationdata-and-conditions-and-sessionnotonorafter

Making it accessible should be possible. I'm thinking of a future redesign of the Saml2Response class which could incorporate that.

Can you please tell me more about your usage scenario.

**Comment by raizarachi** [comment]
With the OWIN middleware, my IT wanted to be able to get the Conditions.SessionNotOrOnAfter's value to force a reauthentication on timeout if the SessionNotOnOrAfter is null.

When the SAML Response's Assertion is not encrypted, I can add it to claims using the AcsCommandResultCreated notification and reading directly the xml data, but it doesn't work when it is encrypted.

By the way, will the middleware (in passive mode) redirect to the IdP in case of timeout (with SessionNotOnOrAfter) or will I need to challenge it ?

**Comment by AndersAbel** [comment]
If `SessionNotOnOrAfter` is set the authentication ticket created and stored in the cookie middleware will respect the session restrictions. If you are using the default model with an external cookie that is separate from the application cookie you need to carry that information over. This is as far as I can help you for free here on the issue tracker. If you want further help, please mail me at anders@sustainsys.com to discuss commercial support options.

**Comment by raizarachi** [comment]
Thank you sir.
