### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by anhhoangbui** [Sustainsys/Saml2#909]
Hi there,

I'm getting the following error after the ADFS sent back the SAML response to the ACS. I'm not sure how to interpret this as it seems to be generic and I'm not capable of reading the source code.

> [NullReferenceException: Object reference not set to an instance of an object.]
   Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) +225
   Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +441
   Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e) +261
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +71

Below is the SAML response that was sent back. I used the SAML plugin for Firefox to retrieve it. I've masked the domain name for privacy reasons and remove the signatures and X509 certificate part to make it easier to read: [saml response.txt](https://github.com/Sustainsys/Saml2/files/1719257/saml.response.txt)

[And this is the Kentor configuration in web.config](https://github.com/Sustainsys/Saml2/files/1719275/web.config.txt)

If anyone can point out what else do I need to configure, that'd be great.

Thank you,
Gavin

**Comment by AndersAbel** [comment]
I can't see anything obvious that's wrong. Looks like some debugging is needed. That's more than I can do for free here on the issue tracker. Please mail me at anders@sustainsys.com if you want further help on a commercial basis.
