### ISSUE TITLE
Stumped with OWIN issue 

### ISSUE THREAD

**Issue by keithd99** [Sustainsys/Saml2#912]
Hi there,

Using OWIN with Okta ... and have an issue that has me stuck ... In my callback method ...
` [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
        {
            
            // Getting the Authentication info from External Identity Provider
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();

            // if the Authentication info object is null, login is unsuccessfull from the External Identity Provider, return error message to user
            if (loginInfo == null)
            {
                ModelState.AddModelError("Error", Strings.SSOObjectNull);
                return View("SsoResponse");
            }`

My issue is logininfo is always returning null. 
Using Fiddler ... I can see the SAML response and all looks fine.  I have the same code running locally and all works fine! 
Oh and I have UseKentorOwinCookieSaver in my startup

Besides Fiddler ... any other troubleshooting tips as to why it's not working?

Thanks!
Keith.

**Comment by AndersAbel** [comment]
Check if a cookie is set in the redirect from ~/Saml2/Acs. Check if external cookie middleware is properly set up.

**Comment by keithd99** [comment]
Yep that's my issue it seems ... it's not for some reason - yet is setting fine locally

**Comment by AndersAbel** [comment]
Where in the owin pipeline did you register the cookie saver?

**Comment by keithd99** [comment]
In Startup.cs ... 
`
    public partial class Startup
    {
        // For more information on configuring authentication, please visit http://go.microsoft.com/fwlink/?LinkId=301864
        public void ConfigureAuth(IAppBuilder app)
        {
            // This is to prevent Cookies set through the Owin API disappear
            // For more information on this issue, visit https://github.com/Sustainsys/owin-cookie-saver
            app.UseKentorOwinCookieSaver();

            //initialize the SAML Provider instance
            var applicationSamlProvider =
                new ApplicationSamlProvider(ServiceLocator.Current.GetInstance<IAuthenticationModule>("SingleSignOn"),
                    ServiceLocator.Current.GetInstance<IUrlProvider>());

            //Geting the SAML and Identity Provider Configurations
            Saml2AuthenticationOptions saml2AuthenticationOptions = applicationSamlProvider.CreateSaml2Options();

            //If the SAML Configurations and Identity Provider are not empty, set external cookie and use SAML Middleware
            if (saml2AuthenticationOptions != null && !saml2AuthenticationOptions.IdentityProviders.IsEmpty)
            {
                // Enable the application to use a cookie to store information for the signed in user
                // and to use a cookie to temporarily store information about a user logging in with a third party login provider
                // Configure the sign in cookie
                app.UseCookieAuthentication(new CookieAuthenticationOptions
                {
                    AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie
                });
                app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

                app.UseSaml2Authentication(saml2AuthenticationOptions);
            }
        }
    }`

**Comment by AndersAbel** [comment]
Can't see anything that is wrong directly. Unfortunately I can't help you further than this for free here on the issue tracker. Mail me at anders@sutainsys.com if you want to discuss commercial support.

**Comment by yeti0506** [comment]
I am current also have as similar issue with an existing legacy application, was there a solution found? 

It was mentioned that commercial support was available however the email address provided are unreachable. 

Looking for any guidance on how to resolve this issue.

**Comment by AndersAbel** [comment]
@yeti0506 Thanks for pointing out the e-mail address. It was a typo in the domain name. One would think that writing one's own e-mail adress would be simple - but apparently not.
