### ISSUE TITLE
Verify SAML signature

### ISSUE THREAD

**Issue by YakkingYak** [Sustainsys/Saml2#914]
Hello,

We successfully implemented Kentor (now Sustainsys) with Okta and SalesForce in our MVC application.

For iOS app, we are planning on Authenticating with Okta / SalesForce independently, then call our WS for authorization (permissions level and others parameters are managed in a different system). If iOS send us the XML output <samlp:Response ...></samlp:Response>, can I use Saml2 to verify the signature?

**Comment by YakkingYak** [comment]
I tried this:
`var samlResponse = new Sustainsys.Saml2.Saml2P.Saml2Response(xmlDoc.DocumentElement, saml2Id);
                var claims = samlResponse.GetClaims(Options.FromConfiguration);`

It is throwing InvalidSignatureException, "Signature didn't verify. Have the contents been tampered with?" which is good, except, now every message is considered a tampered message, even when I didn't modify anything on the XML.

Maybe I am not understanding something more basics about what is considered tampering.

The XML I am using for testing is something I got from monitoring traffic to my app from my IdP using "SAML control Panel" Chrome extension.

**Comment by AndersAbel** [comment]
1. You should consider using a better architecture with the IOS app authenticating to an OpenID Connect server (e.g. IdentityServer4) which can then do the SAML2 authentication to an upstream SAML2 Idp.

2. Yes, it would be possible to send a SAML Response and use the API you've found to validate the response. The SAML Control Panel pretty prints the XML --> Introduces line breaks and white space --> tampered. If you extract the raw xml it should work. Or you could send the raw BASE64-encoded from the form field content to the server and convert it to XML server side (Check Saml2PostBinding class in source for how to do that).
