### ISSUE TITLE
HttpModule: Customise outgoing SAML2 metadata and setting User.Identity.IsAuthenticated

### ISSUE THREAD

**Issue by MikeAllenC** [Sustainsys/Saml2#915]
Hi there,

I'm just getting started with a single sign-on development (.Net web forms to ADFS). I've been playing around with the HttpModule, which looks great for my purposes (and I assume is the only option for a web forms project?).

I have a couple of questions:
1. Can I customise the outgoing SAML2 token/data that's being sent to ADFS? I need to send some extra info (different for each user), but the HttpModule is a bit of a black box, besides the details in web.config.
2. Just because a user authenticates at ADFS does not mean they are authorised to use my application. I've had a play with setting up my own ClaimsAuthenticationManager class as per the docs to check the various returned claims and do further processing on them that could determine whether a user is allowed in (and what rights they have). Can I/should I use the Authenticate method in my ClaimsAuthenticationManager class for this? incomingPrincipal.Identity.IsAuthenticated is read only, so I guess I'd need to create a new, blank ClaimsPrincipal and return that instead of incomingPrincipal if I didn't want a user to be authorised?

Any help much appreciated!

**Comment by AndersAbel** [comment]
1. Yes, you can hook options programmatically by altering `Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.Options`.
2. That's a possible way yes.
