### ISSUE TITLE
Which project to refer in site with .net 4.0

### ISSUE THREAD

**Issue by tutejaamit5** [Sustainsys/Saml2#917]
Hi Team,

I read in one of the thread that this library could be used to implement SAML authentication in .net applications with version 4.0 or lower. I tried importing these NuGet packages in .net 4.0 application but was unable to do that as all applications are targeted for framework 4.5. Can you please tell me the version targeted for .net version 4.0 or lower and what are the steps to consume the same

**Comment by AndersAbel** [comment]
The library requires framework 4.5 or later as the necessary components are not available in .NET 4.0.
