### ISSUE TITLE
Adding Authorize at the controller level for home on the SampleMvcApplication causes infinite loop.

### ISSUE THREAD

**Issue by klabranche** [Sustainsys/Saml2#925]
I realize this might be the worst place to enter this kind of an issue but I couldn't find anywhere else like a forum, etc...

I am working on implementing our teams first SAML based auth'd app.  I am using the sample Mvc Application to test getting things working with our internal server.  I have the sample working like a charm without changing anything.

However, I need to authorize a user for an entire application.  When I remove the Authorize attribute for the Secure Action and add it at the Home Controller level. I get authenticated by our internal servers but then end up in an infinite loop with our server and the app.

I read https://www.blinkingcaret.com/2016/01/20/authorization-redirect-loops-asp-net-mvc/
and created my own Custom Authorize as in the above post but it doesn't stop the infinite loop.

I would expect the Custom Authorize to redirect it to the not authorized but it doesn't.

**Comment by AndersAbel** [comment]
You're right that the issue tracker here is not ideal for this kind of issues. To help you, I'd need to spend some time understanding what you are trying to achieve and where it went wrong. That's unfortunately nothing I can do here for free on the issue tracker.

I do offer commercial support to help integrating the library into applications. Please mail me at anders@sustainsys.com if you're interested.
