### ISSUE TITLE
Decrypt the saml response with idp public key

### ISSUE THREAD

**Issue by Janidbest** [Sustainsys/Saml2#926]
the current Saml2Options are not having support to configure the decrypt certificate with public key.

when the saml response is encrypted, the public key shared by IDP needs to be used to decrypt. 
in case if the decryption certificate is not provided gives the following exception

`"The signature verified correctly with the key contained in the signature, but that key is not trusted."`

the config options are looks like 
````
.AddSaml2(options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    //EntityId as configured in SP
                    options.SPOptions.EntityId = new Saml2NameIdentifier("saml2.test.com.au");
                //X509certificate in the Auth request
                options.SPOptions.ServiceCertificates.Add(new ServiceCertificate
                {
                    Use=CertificateUse.Both,
                    Certificate= GetSigningCertificate("‎10 07 9f e5 d2 0d e6 78 21 64 f2 b8 ec 85 51 ae f9 d9 a0 a4", false)
                });
                    //options.SPOptions.ServiceCertificates.Add(new ServiceCertificate
                    //{
                    //    MetadataPublishOverride = MetadataPublishOverrideType.DoNotPublish,
                    //    Certificate = GetIdpCertificate(),
                    //    Use=CertificateUse.Both
                    //});
                    //Sign the auth request
                    options.SPOptions.AuthenticateRequestSigningBehavior = SigningBehavior.Always;  
                  
                    //NameId
                    options.SPOptions.NameIdPolicy = new Saml2NameIdPolicy(true, NameIdFormat.Unspecified);
                    
                    var identityProvider = new IdentityProvider(new EntityId("https://bvm01/idp/shibboleth"),
                        options.SPOptions)
                    {                        
                        SingleSignOnServiceUrl = new Uri("https://bvm01/idp/profile/SAML2/POST/SSO"),
                        Binding = Saml2BindingType.HttpPost,
                        WantAuthnRequestsSigned=true,
                        
                    };
                    options.IdentityProviders.Add(identityProvider);
                });
````

**Comment by explunit** [comment]
I think you are misunderstanding the role of encryption & signing in the SAML protocol. To verify the signature of the received assertion you need to configure the IDP's public key, either by using their metadata url or by configuring it in their IdentityProvider object. The ServiceCertificate is not involved in verifying the signature of the received assertion. You mention encryption but the error message you reported does not sound like encryption is involved in this scenario.

**Comment by Janidbest** [comment]
> To verify the signature of the received assertion you need to configure the IDP's public key

Exactly, I have the public key provided by IDP whose encrypting the response, as you said I will have to decrypt/verify the signature using the key.. that is missing in the configuration !! or maybe I have missed to identify that.

**Comment by explunit** [comment]
Decrypt and verify are not the same thing. For decryption, you need to configure ServiceCertificate. For verification of signature from IDP, you have to configure the properties of the IdentityProvider object with either a MetadataUrl or a SigningCertificate. In your code so far you are only specifying SingleSignOnServiceUrl, Binding, and WantAuthnRequestsSigned.
