### ISSUE TITLE
SAML2.MVC Usage

### ISSUE THREAD

**Issue by ychhajed** [Sustainsys/Saml2#927]
We have an asp.net website built in MVC framework. We want to make our website a SAML2 provider as mentioned in the Readme of this project. What all we need make changes in the controller to get this working ? (We have updated the web.config but could not get it working yet. ) Is there a step by step guide or something ?
Our end goal is to use Cognito Federated Identity and add our website as the SAML2 provider. This will help our mobile apps to use our existing users to login into the mobile apps.

**Comment by ychhajed** [comment]
Thanks for the response. We are not using ACtive directory in our application but normal form authentication with a Provider we created. We have the username and passwords stored in our SQL database. And this we want to use in Cognito , instead of creating new users in Cognito

**Comment by smcnaryM3** [comment]
Hey @ychhajed, I am in fact implementing an SSO into an MVC application.  I've been able to use your example above and it's helped me moved forward.  The part I'm still having trouble with is the certificate part.  I've been provided with a .cer file, which I've installed.  Is that the certificate I reference in the serviceCertificates portion of the web config? Or is it under the signing certificate?

**Comment by nicswan** [comment]
@ychhajed I could be misinterpreting, but it sounds like you're trying to roll your own _identity provider_. This library is for providing _service provider_ functionality for an app.

@smcnaryM3 Yes, the certificate referenced in the serviceCertificates section is the one that your app (the service provider) will use to sign SAML assertions.  Typically it needs to be in the Personal store of the Local Computer. The user or group your application runs under/as will need read access to the private key for the certificate (in the Certificates console, if you right click on the certificate, this is under All Tasks > Manage Private Keys). You may also need to update your application pool to set Load User Profile to true.

**Comment by AndersAbel** [comment]
Looks like this is solved, closing.
