### ISSUE TITLE
Receiving error Invalid URI: on the response

### ISSUE THREAD

**Issue by dunghill** [Sustainsys/Saml2#928]
Hello,
I am receiving an Invalid URI exception when process the response on /Salm2/Acs and I have gone through every configuration to understand what am I doing wrong but i am stuck on it.
 <sustainsys.saml2  entityId="tknb.ssc.vn" returnUrl="http://localhost:4092/Default.aspx"                     minIncomingSigningAlgorithm="sha1"  authenticateRequestSigningBehavior="Always">
    `<identityProviders>`

      <add entityId="http://sso.tinhvan.vnet:80/oam/fed" signOnUrl="http://sso.tinhvan.vnet/oamfed/idp/samlv20" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect" loadMetadata="true" metadataLocation="http://sso.tinhvan.vnet/oamfed/idp/metadata">
        <signingCertificate fileName="~/metadata/saml.cer"/>
      </add>
    </identityProviders>
    
    <federations>
      <add metadataLocation="http://sso.tinhvan.vnet/oamfed/idp/metadata" allowUnsolicitedAuthnResponse="false"/>
    </federations>
    
    <serviceCertificates>
      <add fileName="~/metadata/saml2.pfx"/>
    </serviceCertificates>
  </sustainsys.saml2>
  <system.identityModel.services>
    `<federationConfiguration>`
      `<cookieHandler requireSsl="false"/>`
    `</federationConfiguration>`
  </system.identityModel.services>
 

**--> Exception**
`[UriFormatException: Invalid URI: The format of the URI could not be determined.]
   System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) +6643964
   System.Uri..ctor(String uriString) +21
   Sustainsys.Saml2.Saml2P.Saml2PSecurityTokenHandler.GetAudienceRestriction(SPOptions spOptions) +167
   Sustainsys.Saml2.Saml2P.Saml2PSecurityTokenHandler..ctor(SPOptions spOptions) +87
   Sustainsys.Saml2.Saml2P.<CreateClaims>d__57.MoveNext() +297
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +387
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options) +90
   Sustainsys.Saml2.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) +38
   Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +183

[BadFormatSamlResponseException: The SAML Response did not contain valid BASE64 encoded data.]
   Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +292
   Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e) +261
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +71`

Can you help me?

Thanks!

**Comment by explunit** [comment]
It looks like your entity id `tknb.ssc.vn` does not parse as a URI/URN. Could you change it to an absolute one like `https://tknb.ssc.vn/myapp` even if that doesn't correspond to a real web site.
