### ISSUE TITLE
Implementation with Angular JS version 1.6

### ISSUE THREAD

**Issue by shahrozkhan26** [Sustainsys/Saml2#929]
Hi Anders,

I have a SPA application in Angular JS (1.6) which uses ASP.NET Web API for the back-end. Can you please guide me how we can implement a service provider, so an identity provider can send the single sign on request to the service provider? Is this do-able? Please advise.

Regards,
Shahroz Khan

**Comment by AndersAbel** [comment]
Yes this is doable, using IdentityServer3 or 4 as an OpenID Connect/SAML2P bridge. If you want guidance, I do offer that as commercial consultancy services. Please mail me at anders@sustainsys.com if you want more information.
