### ISSUE TITLE
Running in Debug mode locally when in a corporate AD

### ISSUE THREAD

**Issue by scriptmonkey69** [Sustainsys/Saml2#930]
First I would like to say that the library has made our transition to ADFS extremely easy due to the simplicity  of just a few lines of code and some configuration. Well done and Thank you.

I have one question with regards to running the software in debug mode in Visual Studio.
Currently the only way I can see you configure ADFS to let us run in Debug mode is to set each Development machine up as a separate trust relationship but this seems a bit overkill, do you have any suggestions or experience with this?

**Comment by explunit** [comment]
If the development machines have access to the same service certificate then the trust relationship can be set up with https://localhost:55555 (or whatever port number) you choose so that everyone can share a configuration. ADFS requires SSL but it's OK with SSL on localhost.
