### ISSUE TITLE
Redirect to original url requested after login

### ISSUE THREAD

**Issue by rosariomartone** [Sustainsys/Saml2#931]
Hi,
I am trying to redirect the user to the original url requested instead of base page.
For example, the user's url would be:

http://myapplication/controller/param1

so after login the user would be redirected automatically to:

http://myapplication/controller/param1

instead of 

http://myapplication/

Is there any chance having this properly working?

Thanks,
Rosario.

**Comment by explunit** [comment]
Which mode (HttpModule, OWIN, MVC, .Net Core) are you using to integrate this library? Yes, this should be possible but the answers might be slightly different based on which approach you use.

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
