### ISSUE TITLE
Missing await keyword in released NuGet package

### ISSUE THREAD

**Issue by lol768** [Sustainsys/Saml2#932]
When I decompiled `Sustainsys.Saml2.AspNetCore2.CommandResultExtensions` of version `2.0.0-preview01` of `Sustainsys.Saml2.AspNetCore2` there are no `await` keywords on the `httpContext.SignInAsync(SignInScheme, commandResult.Principal, properties)` call which causes issues - user is not logged in most of the time because the call doesn't complete.

This appears to be fixed in the `master` branch. Is there a `netstandard` release with this fix on NuGet, c.f.

* https://github.com/Sustainsys/Saml2/blob/netstandard/Sustainsys.Saml2.AspNetCore2/CommandResultExtensions.cs
* https://github.com/Sustainsys/Saml2/blob/master/Sustainsys.Saml2.AspNetCore2/CommandResultExtensions.cs

**Comment by lol768** [comment]
I'm so confused right now, it would appear `0.23.0` is _newer_ than `2.0.0-preview01` looking at the release dates (2018-01-17 vs 2018-01-09) and tags? Is this right?! Even NuGet itself thinks https://www.nuget.org/packages/Sustainsys.Saml2.AspNetCore2/0.23.0 is old and suggests there is a newer release.

**Comment by lol768** [comment]
If anyone else runs into this, I ended up applying just these changes from the default branch to a .NET Core compatible fork: https://www.nuget.org/packages/Lol768.Sustainsys.Saml2.AspNetCore2/2.0.1-preview01

**Comment by lol768** [comment]
ANy update on this? It'd be nice to not have to rely on a fork.

**Comment by AndersAbel** [comment]
The branch that 2.0.0-preview1 was built from will be abandoned in favour of #939, so this issue won't be relevant.

**Comment by lol768** [comment]
It's still relevant whilst you haven't merged the PR.
