### ISSUE TITLE
InvalidSignatureException

### ISSUE THREAD

**Issue by mattroot87** [Sustainsys/Saml2#933]
Attempting to set up IdP initiated Sign on and coming up against this error when logging into IdP server and then getting redirected to the Service Provider:

Message from http://sts.;alsdjfsad;lfj/adfs/services/trust failed signature verification at Kentor.AuthServices.WebSso.Saml2RedirectBinding.CheckSignature(HttpRequestData request, IdentityProvider idp) at Kentor.AuthServices.WebSso.Saml2RedirectBinding.GetTrustLevel(XmlElement documentElement, HttpRequestData request, IOptions options) at Kentor.AuthServices.WebSso.Saml2RedirectBinding.Unbind(HttpRequestData request, IOptions options) at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) at Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnPostAuthenticateRequest(Object sender, EventArgs e) at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) 

Any help on what is wrong with my singing certificate from the IdP?

Thanks!

**Comment by explunit** [comment]
Did you obtain the certificate manually or are you configured with their metadata url?

**Comment by mattroot87** [comment]
I obtained it manually from the IdP.  It seems as though the response is not being signed by the IdP.  Everything seems to be correct as far as the relaying party trust-> the signing cert located in the signature tab, etc...

**Comment by explunit** [comment]
Have you traced the responses using a browser addon like the one suggested in the troubleshooting steps? Most IDP include the public key along with the signed assertion so you can more easily troubleshoot if it's the same cert thumbprint as the one you loaded.

But if you're using ADFS I recommend pointing to the metadata URL instead so that you don't have to manually configure certificates and deal with rollover etc.

**Comment by mattroot87** [comment]
I appreciate your advice.  I actually yes have traced the response and the response does not include a public key nor a signature... Which is why I think for some reason the response nor the assertions are being signed by the IdP but I don't know why..

**Comment by explunit** [comment]
That is very odd. It sounds like only your IDP can answer this one so I'm going to close it here. Please reopen this issue if you find some information that indicates the library is at fault.

**Comment by mattroot87** [comment]
Ok.  I appreciate it.  Have a blessed day.
