### ISSUE TITLE
Migration to Sustainsys library

### ISSUE THREAD

**Issue by scriptmonkey69** [Sustainsys/Saml2#934]
I have migrated to the Sustainsys library today. My current setup is as follows
3 sections in the web.config
<section name="system.identityModel" type="System.IdentityModel.Configuration.SystemIdentityModelSection, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
        <section name="system.identityModel.services" type="System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
        <section name="sustainsys.saml2" type="Sustainsys.Saml2.Configuration.SustainsysSaml2Section, Sustainsys.Saml2" />

Module Path defined on the main sustainsys element
<sustainsys.saml2 entityId="***" returnUrl="***" modulePath="/AuthServices">

Route mapped for AuthServices to Saml2 controller
 routes.MapRoute("AuthServices", "AuthServices/{action}", new { Controller = "Saml2" });

But what ever I try I get a 404 error when I try authenticate to the site...

Is there anything I am missing?

**Comment by nicswan** [comment]
@scriptmonkey69 The path has changed to `/Saml2` or `Saml2/{action}`.

**Comment by scriptmonkey69** [comment]
But I can override that with the modulepath attribute on the main
sustainsys element and by adding a custom route in the route config.

I think my problem might be the sequence of the routes configured, but will
check tomorrow.

Thanks for responding

**Comment by nicswan** [comment]
Ah, I haven't used the `modulePath` attribute so I didn't realize that's what it did.  Looking at your route, it doesn't seem to account for just the base /AuthServices path (where metadata is generated). For what it's worth, here are my route mappings - I could get them to successfully route to an alternate path (i.e. AuthServices/ instead of Saml2/) using the `modulePath` attribute.

```
routes.MapRoute("AuthIndex", "AuthServices", new { controller = "Saml2", action = "Index" });
routes.MapRoute("AuthAcs", "AuthServices/Acs", new { controller = "Saml2", action = "Acs" });
routes.MapRoute("SignIn", "AuthServices/SignIn", new { controller = "Saml2", action = "SignIn" });
routes.MapRoute("Logout", "AuthServices/Logout", new { controller = "Saml2", action = "Logout" });
```

**Comment by AndersAbel** [comment]
When using the MVC module, things get a bit more complicated  - both the module path and the routing need to be changed if you don't want to go with the default (and the default just changed, sorry for that...)

**Comment by scriptmonkey69** [comment]
Ok all working again thanks to nicswan. 

I have reduced the route to just one definitions. 
`routes.MapRoute("AuthServices", "AuthServices/{action}",
                new {controller = "Saml2", action = "Index|Acs|SignIn|Logout"});`

Thanks for the help with this issue and a big thank you for creating this great library.

**Comment by AndersAbel** [comment]
Thanks for reporting back your findings, that will help if anyone else has the same issue.
