### ISSUE TITLE
Triggering Single Logout from SP

### ISSUE THREAD

**Issue by shaundodimead** [Sustainsys/Saml2#937]
I'm sure this is RTFM but I can't find it - i'm sorry. 

From an ASP.NET MVC application, how does one trigger the single sign out process? I've tried redirecting to SAML2/Logout but this doesn't seem to trigger any activity to the idP.

What's the correct method to get an SP initiated MVC app to trigger a logout on the idP. The identity provider does have a valid logoutUrl set.

In the MVC sample I tried setting

```
 <add entityId="https://stubidp.sustainsys.com/Metadata"
           signOnUrl="https://stubidp.sustainsys.com/"
           logoutUrl="https://stubidp.sustainsys.com/Logout"
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
```

Put SAML2/Logout doesn't seem to call the logoutURL.

I'm sure i'm misunderstanding something obvious

**Comment by AndersAbel** [comment]
Redirect to SAML2/Logout. Then there are a bunch of requirements for federated logout to work, one of them is that you need a servicecertificate configured in your end.

If you enable logging, you should get a message that indicates what is missing for federated logout to be enabled.

**Comment by arthurmmedeiros** [comment]
Doesn't the application configure the certificate automatically when reading the MetaData?

I'm having the same issue here. My code hits the controller, and then it just redirects me to the RedirectURI I set. No request is made to SignOut. What I am missing?



`        [AllowAnonymous]
        [HttpGet]
        [Route("api/logout")]
        public async Task<string> LogoutAdfs()
        {
            string redirectUri = _appSettings.Saml.SpEntityId;

            await HttpContext.SignOutAsync(Saml2Defaults.Scheme, new AuthenticationProperties
            {
                RedirectUri = string.Concat(redirectUri, "/logout")
            });
            var location = HttpContext.Response.Headers["Location"];
            return ReturnUrl();
        }`



Here's my StartUp config:]
`            services
                .AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = Saml2Defaults.Scheme;
                })
                .AddSaml2(Saml2Defaults.Scheme, options =>
                {
                    options.SPOptions.EntityId = new EntityId(appSettings.Saml.SpEntityId);
                    //options.SPOptions.Logger = new SerilogSaml2Adapter();
                    //options.SPOptions.ServiceCertificates.Add(new X509Certificate2("cert_teste_adfs.cer"));
                    options.IdentityProviders.Add(
                        new IdentityProvider(
                            new EntityId(appSettings.Saml.EntityId), options.SPOptions)
                        {
                            LoadMetadata = true,
                            MetadataLocation = appSettings.Saml.MetadataAddress,
                            AllowUnsolicitedAuthnResponse = true,
                            SingleLogoutServiceUrl = new System.Uri("http://localhost:5001"),                          
                   

                        });
                })
                .AddCookie();`
