### ISSUE TITLE
Getting an error while implementing SSO in our web application using ADFS and SAML2.0 (Sustainsys)

### ISSUE THREAD

**Issue by jpgalera** [Sustainsys/Saml2#941]
Hi, I have posted this question on stackoverflow and was wondering if anyone knows a fix for it. https://stackoverflow.com/questions/49634935/getting-an-error-while-implementing-sso-in-our-web-application-using-adfs-and-sa

my Relying Party trust is configured using the federation metadata so i cant edit it

**Comment by tonyeung** [comment]
just need to add the config to web.config and call the url saml2/signin

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
