### ISSUE TITLE
Protected View not redirecting to IDP Login Page getting "HTTP Error 401.0 - Unauthorized" instead

### ISSUE THREAD

**Issue by markmilchuk** [Sustainsys/Saml2#946]
When a user is NOT Authenticated and tries to directly access a protected View, Controller has [Authorize] attribute set, I am getting a "401 Unauthorized" Page. Shouldn't the behavior be that it instead it redirects to the SAML2 IDP Login Page? 

What behavior is defined by Sustainsys OWIN module for accessing a protected view when user is not authenticated?

I know for Microsoft.Owin.Security.OpenIdConnect the behavior is to redirect to the IDP Login Page.

**Comment by AndersAbel** [comment]
That mechanism is actually handled by the cookie middleware, which is responseible for the redirect to the login page. You have to specify the login page url in the cookie middleware's options.
