### ISSUE TITLE
users experience occasional cryptographic exception

### ISSUE THREAD

**Issue by rharting** [Sustainsys/Saml2#949]
Hello, we have developed a SAML authenticated asp .net application around version 0.21.2. The application is hosted on IIS. Occasionally, we have a user report that they are getting the exception shown below. Having the user clear the browser cache will fix the problem, however, we would really like to get to the bottom of the issue so that this never happens.  This doesn't always happen, so it is difficult to find.  Can you offer any ideas? Please let me know if I need to provide more information. Thanks in advance.

**Error occurred during a cryptographic operation.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[CryptographicException: Error occurred during a cryptographic operation.]
System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input) +172
System.IdentityModel.Tokens.SessionSecurityTokenHandler.ApplyTransforms(Byte[] cookie, Boolean outbound) +167
System.IdentityModel.Tokens.SessionSecurityTokenHandler.ReadToken(XmlReader reader, SecurityTokenResolver tokenResolver) +786
System.IdentityModel.Tokens.SessionSecurityTokenHandler.ReadToken(Byte[] token, SecurityTokenResolver tokenResolver) +88
System.IdentityModel.Services.SessionAuthenticationModule.ReadSessionTokenFromCookie(Byte[] sessionCookie) +512
System.IdentityModel.Services.SessionAuthenticationModule.TryReadSessionTokenFromCookie(SessionSecurityToken& sessionToken) +258
System.IdentityModel.Services.SessionAuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs eventArgs) +143
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +88**

**Comment by explunit** [comment]
This does not seem related to the Saml2 library. Possibly it's the SessionAuthenticationModule that's used after the user was authenticated via SAML?

Please reopen if I'm missing something in how this relates to Saml.

**Comment by rharting** [comment]
I'm not sure its not related, but if it is, I'm sure that I just don't have something set up correctly. I'm just hoping someone can offer advice?
We picked the Kentor SAML2 library is because we needed a quick solution to tie into our IdP, and so we don't have a good understanding how it works. 
I was mistaken that clearing browser cache solved issue, it is actually clearing cookies that fixes it. It seems to be related to the FedAuth cookie.  I'm reading this has something to do with Forms Authentication, and so the investigation continues...

**Comment by AndersAbel** [comment]
@explunit is right, the stack trace shows that this is from the SessionAuthenticationModule that handles the cookie on subsequent requests.

Do you run this in a load balanced setup? In that case, have you synchronized the machine keys?

**Comment by pranith12345** [comment]
We are also facing the same Cryptographic exception inconsistently . Below is the StackTrace . 
`|Error in AuthenticateUser|System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
   at Sustainsys.Saml2.HttpModule.HttpRequestBaseExtensions.<>c.<ToHttpRequestData>b__2_1(Byte[] v)
   at Sustainsys.Saml2.WebSso.HttpRequestData.Init(String httpMethod, Uri url, String applicationPath, IEnumerable`1 formData, IEnumerable`1 cookies, Func`2 cookieDecryptor, ClaimsPrincipal user)
   at Sustainsys.Saml2.WebSso.HttpRequestData..ctor(String httpMethod, Uri url, String applicationPath, IEnumerable`1 formData, IEnumerable`1 cookies, Func`2 cookieDecryptor, ClaimsPrincipal user)
   at Sustainsys.Saml2.HttpModule.HttpRequestBaseExtensions.ToHttpRequestData(HttpRequestBase requestBase, Boolean ignoreCookies)
   at Sustainsys.Saml2.HttpModule.HttpRequestBaseExtensions.ToHttpRequestData(HttpRequestBase requestBase)`

We are running in a Load balancer Setup . Sign in request is getting generated from one Server and the SAML response is  reached to another server from the IDP in the Load balancer . MachineKeys are autogenerated . 
Should we synchronize the MachineKeys in the environment .

**Comment by AndersAbel** [comment]
If you have a load balanced setup you need to have the machine keys synchronized yes.
