### ISSUE TITLE
Programmatically generate SP Metadata

### ISSUE THREAD

**Issue by andrecalil** [Sustainsys/Saml2#951]
Hey folks,

I'm sorry if this particular question has been answered before, but I couldn't really find what I'm looking for.

So, I have an ASP.NET MVC app and I leverage the former Kentor.AuthServices library to add SAML2 login to our app. This app is the _service provider_. I'm not using the HttpModule approach, but rather implementing each action as necessary and using the library to parse requests and IdP Metadata.

Now I'd like to **generate the SP Metadata** to fast track our implementation. Is there support for that - either on the former library or on the current one?

Thanks in advance!

**Comment by andrecalil** [comment]
Thanks @explunit I think that's all I needed.

**Comment by saurabh12231978** [comment]
@explunit Is there provision to load 3rd party service provider metadata(which has SPSSODescriptor) ? the thing is I am trying to implement logout functionality with simple setup (3rd party SP, my own kentor stub idp with security implementation and asp.net mvc app as RP); 

we have an sp with acs and logout(both POST) and when i click on mvc app link (to sp logout) i get 404... SSO i am doing as idp flow(unsolicited samlresponse to sp acs and its working)... but not able to figure out how to call sp logout... In kentor all samples logout link goes to authservices/logout..then redirected to idp logout controller and logout response which i also tried posting to sp logout link...but i get just 404.. please guide for SLO ...
