### ISSUE TITLE
Why is RelayState protected in the Saml2RequestBase?

### ISSUE THREAD

**Issue by millent** [Sustainsys/Saml2#954]
https://github.com/Sustainsys/Saml2/blob/2c468b9b8e67dbcce11cbcda2baa5aecd164082d/Sustainsys.Saml2/SAML2P/Saml2RequestBase.cs#L164

Am I correct to use RelayState as a means to pass context information e.g. the redirect url for my web page when the request was not authorized initially? Seems like this is intialized to a random value but can't be set directly - is your expectation that the RelayState should be used only as a lookup while the actual context information is stored via some other state management technique?

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
