### ISSUE TITLE
way to remove the cache metadata

### ISSUE THREAD

**Issue by robertpmansion** [Sustainsys/Saml2#956]
We're generating the SP metadata per subdomain, so for Client 1 should have a generated metadata with entity id as 'https://client1.organisation.com/saml2/sp' and for the Client 2 as 'https://client2.organisation.com/saml2/sp'. What we did is we reinitialize the entity id per subdomain, however, due to the caching instead of getting the metadata for client 2 we're getting the client 1 metadata because we have downloaded the client 1 metadata first. 

Is there an option to remove the cache then reinitialize whenever we visited different subdomain?

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
