### ISSUE TITLE
SP metadata download file name

### ISSUE THREAD

**Issue by Peperud** [Sustainsys/Saml2#957]
If I hit the SP metadata url straight from a browser I get an extension-less file downloaded (name being the last segment of the url).

Is there a way (by Sustainsys means) to influence the file naming (Content-Disposition header etc.)?

Obviously in the machine to machine scenario this doesn't matter, but when people are involved it becomes rather inconvenient.

I can write a piece of middleware to intercept response headers, and add a Content-Disposition header if necessary, but it seems rather inefficient to check every response (for Content-Type header "application/samlmetadata+xml").

**Comment by AndersAbel** [comment]
An http header might hinting of the file name might be possible, but needs to be checked with the Saml2 specs that it is ok.
