### ISSUE TITLE
ASP.Net Core MVC Sample without Identity (just saml2 & cookies)

### ISSUE THREAD

**Issue by klabranche** [Sustainsys/Saml2#959]
I would like to essentially do what the asp.net MVC samples does to handle authentication & authorization in Core MVC.  No identity db, just cookies with saml2 auth.  The only sample we have is using Identity.  We have no need of a backing store for identities.  We just want to have our idp auth the user and send back the claims for the user into roles to use built in authorization. Any samples to do this?

**Comment by klabranche** [comment]
I have since found #879 & #885.  Any idea on when #879 will be fixed?

**Comment by AndersAbel** [comment]
I don't understand. #879 was already fixed by the time you created this issue.

Closing for now, please comment if problem persist and it should be reopened.
