### ISSUE TITLE
How to encrypt a SAMl response with Sustainsys

### ISSUE THREAD

**Issue by svona** [Sustainsys/Saml2#960]
I'm new to SSO and SAML developing an SSO solution between my site and another. I'm also fairly new to login solutions in general. Here's the scenario. I'm creating a Saml2Response without an SP initiated call (no SAML assertion). I was able to successfully SSO into the service provider's sandbox enviornment. Now They want me to encrypt the response before sending it. They are using AES-256 encryption in the partnership. Now my responses are failing. Here is what they sent me.

> research on why the failure may be occurring..
> 
> For the connection we are using the following:
> Signing Algorithm: RSA SHA256
> Encryption Block Algorithm: tripledes
> Encryption Key Algorithm: rsa-v15
> 
> Here is some further background info as well around our encryption support:
>  
> 	Unsupported SAML v2.0 Features
> 		* Single Logout Profile
> 		* For Artifact binding, signing the ArtifactResolveRequest and validating the ArtifactResolveResponse
> 		* Dynamics Federation
> 		* Embedded Certificates
>  
>  
> * Embedded Certificates in this context may refer to certificates used in setting up Federation or Artifacts. 
> * We fully support the SAML SSO assertion containing the certificate info utilized to decrypt the assertion.

> 
> Attributes
> * name = IPD_ID, format = text, Required Attribute = true, Requires Attribute Encryption = false
> 
> * name = group_name, format = text, Required Attribute = true, Requires Attribute Encryption = false
> 
> * name = username_ID, format = text, Required Attribute = true, Requires Attribute Encryption = true
> 
> 

Here is the code I used to encrypt the response

```
public static void EncryptXml(XmlDocument xmlDoc, X509Certificate2 cert)
{
	var eDoc = new EncryptedXml();
	var eData = eDoc.Encrypt(xmlDoc.DocumentElement, cert);
	EncryptedXml.ReplaceElement(xmlDoc.DocumentElement, eData, false);
}
```

Is there a way using Sustainsys to encrypt a Saml2Response? It also looks like they dont want me to encrypt the entire document but certain claims

**Comment by AndersAbel** [comment]
There is no support to generate encrypted responses and focus of this library for now is not to provide Idp functionality.

**Comment by maks-sameergoyal** [comment]
Hello, 

Is support for encrypting responses/requests now available in this library?
