### ISSUE TITLE
Never being redirected or forwarded to adfs login when using owin

### ISSUE THREAD

**Issue by blaur** [Sustainsys/Saml2#961]
Hi guys,

I'm really in need of some help.

I've implemented the OwinMiddleware solution as described here: https://github.com/Sustainsys/Saml2/blob/master/docs/OwinMiddleware.md

It works fine and I can verify that everything comes through in the config in debug mode.

What does not work for me is the redirect. I can only make it work if i navigate to Saml2/SignIn manually.

From the doc on OwinMiddleware it is mentioned that you can use to get it all started:
```
var context = HttpContext.GetOwinContext();
context.Environment.Add("saml2.idp", new EntityId(YOUR_IDP_ENTITY_ID));
```
But I'm wanting to do that immediately after this but I have never getting anything back. Could you explain me why? What am I missing? :D

```
                var Saml2Options = new Saml2AuthenticationOptions(true)
                {
                    Notifications = new Saml2Notifications
                    {
                        AuthenticationRequestCreated = (request, provider, dictionary) =>
                        {
                            Console.WriteLine("HEY");
                        },
                        AcsCommandResultCreated = (result, response) =>
                        {
                            Console.WriteLine("HEY");
                        },
                        SignInCommandResultCreated = (result, dict) =>
                        {
                            //ReConnectAdfs
                            var sc = new SessionConnection_Bll();
                            sc.SetReconnectMethodADFSSaml();
                            Console.WriteLine("HEY");
                        }
                    }
                };
                app.UseSaml2Authentication(Saml2Options);
```

Looking forward to your help!

**Comment by blaur** [comment]
A follow up on this.

For some reason I'm not able to hit the /Saml2/Acs..

Any pointers?

**Comment by blaur** [comment]
I had to call this instead of the one provided in the OWIN example. Probably my inexperience with owin.
```
var appUrl = VirtualPathUtility.ToAbsolute("~/");

HttpContext.Current.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = appUrl }, "Saml2");
```

**Comment by RaghuAnne** [comment]
Hi Blaur,

I have same issue, could you please share your fix. I am able to authenticate against ADFS but sample application not redirecting me from login page. I see SAML response and configured claims in response.
