### ISSUE TITLE
Idp-initiated single signout?

### ISSUE THREAD

**Issue by toadicusrex** [Sustainsys/Saml2#962]
Hi!

First, bless you for this library, it's a godsend.  I've hooked it up to my IdentityServer3 implementation and it's working beautifully, with two small exceptions.  I'm not sure if I just fail at google, but I haven't been able to get a clear answer and so I'm reaching out.  I have another issue as well, but first things first.

Scenario is that we have an application with standalone authentication, which I've configured using IdS3 and our custom database; this drives our API which also hosts the IdS3 instance, and a react/redux App as our front-end.  So the API is kind of an IdP with a SustainSys SP for our clients to plug in their IdPs.

So I have SSO working great, both SP and IdP initiated.  That took me a while to figure out, but it works like a charm now.  SP-initiated SLO works too, and logs the user out of the IdP (testing using Okta).  However for IdP initiated SLO, I expected that when the user logs out of Okta that it would initiate a connection to the SP to notify it that logout has occurred, but I don't see any traffic to the SP at all, and the user stays logged in.

Am I missing some config setting?  I know I missed that I had to add a cert for SLO for the endpoints to be enabled.  Hoping I've just missed something like that.  Thoughts?

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.
