### ISSUE TITLE
Reading IdentityProviders from a database

### ISSUE THREAD

**Issue by MrSmoke** [Sustainsys/Saml2#964]
Looking at the library the best option to accomplish this would be to implement my own `SelectIdentityProvider` however in https://github.com/Sustainsys/Saml2/issues/540 you recommended 
> I'd also recommend to not create a new IdentityProvider object in SelectIdentityProvider but rather return one from the existing IdentityProvider collection.

The reason I wish to load from a database is because I want to add and remove without recycling the application (like others have suggested).

Adding to `options.IdentityProviders` doesn't seem ideal as that would require storing data in 2 locations (it also has the issue of a changing Entity Id since its a dictionary internally) and ensuring its matching.

Is there a reason returning new objects from `SelectIdentityProvider` is not recommended? The only issue I can see with a quick look is that this won't work for logout requests as these use the `IdentityProviders` collection directly.

**Comment by MrSmoke** [comment]
Ideally instead of  `IdentityProviderDictionary` you could probably have `IIdentityProviderStore` and you can implement your own

**Comment by AndersAbel** [comment]
This is one of those issues that makes me feel like it's time for a rewrite, using DI throughout the system. The library has grown (both in features and usage) far beyond what I expected, so it's not designed to be flexible enough for everything people want to do.
I'm closing this issue now, but have ideas of a redesign where this would be one of the things that would be added.

**Comment by parkinsona** [comment]
@AndersAbel , I've had a look through the referenced issues for this and I'm not sure if there is the ability to read providers from the database? And if they can be loaded after startup?

**Comment by AndersAbel** [comment]
@parkinsona Yes, there is now support for that. Implement the `SelectIdentityProvider` and `GetIdentityProvider` notifications. Then you will bypass the built in Identity provider collection entirely.

**Comment by parkinsona** [comment]
@AndersAbel , thanks for getting back to me. I've had a look at both of those notifications, but I'm not 100% sure how each of them work. 

My understanding is that SelectIdentityProvider allows me to add an idp to Options.IdentityProviders when the SignInCommand is run.  And GetIdentityProvider allows you to return an idp that may not be in Options.IdentityProviders?

If that is the case, I'm assuming you require the idp to be passed through in the sign in command. Which I know identityserver is capable of. Although, is my assumption correct, that going down this path, IdentityServer would not show the identity providers on the login screen? 

In terms of implementing them, I'm not sure how to approach this. I looked through the code and saw your test cases, but wasn't sure how to translate that to an application sense.

**Comment by svk12** [comment]
@AndersAbel , can you suggest how to implement the SelectIdentityProvider() and GetIdentityProvider() notifications when idp information in stored and retrieved from database

**Comment by svk12** [comment]
@AndersAbel m using sustainsys alone, no identityserver3

**Comment by RoLYroLLs** [comment]
@svk12 have you figure out how? I'm in the process of figuring out how to add Idps from the DB. Currently added them to `options.IdentityProviders` but after looking at this, it does not seem like the right way. I'm unsure how to implement these `SelectIdentityProvider` and `GetIdentityProvider` notifications

**Comment by AlexOliinyk1** [comment]
@RoLYroLLs @svk12 hello, have you figure out how to resolve it? How I can contact you? thanks

**Comment by IAMHK90** [comment]
@svk12 @AlexOliinyk1 are you able to load Idps from the DB?
