### ISSUE TITLE
Not able to pass the signing keys part of IdentityProvider

### ISSUE THREAD

**Issue by nhcloud** [Sustainsys/Saml2#965]
This used to work with Kentor assembly long ago.  Currently, I am building a SaaS-based system which will pass the signing keys from the Identity Provider from external data source instead of web.config or app.config.  All it needs is another constructor to pass in part of ConfiguredAndLoadedSigningKeysCollection

**Comment by AndersAbel** [comment]
Keys are possible to add/remove from code, so I don't understand the problem.
