### ISSUE TITLE
Cannot Validate in CreateClaims due to missing Signature element 

### ISSUE THREAD

**Issue by blaur** [Sustainsys/Saml2#966]
Hi guys,

Looking for some expert assistance and hope you are able to provide exactly that ;)

We've used this library for ADFS with SAML 2.0 protocol integration. We are now successfully forward to ADFS for login and then redirected back to our page which is all good.

Now we are facing a problem where the signature cannot be validated when creating the claims because the signature is missing from the xml. The error message is:
`The SAML Response is not signed and contains unsigned Assertions. Response cannot be trusted.`

It is thrown from the SAML2Response in this method because "isSignedByAny(...)" is not returning true:
```
        private void ValidateSignature(IOptions options)
        {
            var idpKeys = options.IdentityProviders[Issuer].SigningKeys;

            var minAlgorithm = options.SPOptions.MinIncomingSigningAlgorithm;

            if(!xmlElement.IsSignedByAny(idpKeys, options.SPOptions.ValidateCertificates, minAlgorithm)
                && GetAllAssertionElementNodes(options)
                .Any(a => !a.IsSignedByAny(idpKeys, options.SPOptions.ValidateCertificates, minAlgorithm)))
            {
                throw new Saml2ResponseFailedValidationException("The SAML Response is not signed and contains unsigned Assertions. Response cannot be trusted.");
            }
            options.SPOptions.Logger.WriteVerbose("Signature validation passed for Saml Response " + Id);
        }

```

There is a hard requirement to have a signature is the XML but ADFS do never provide one directly in the XML. The signature is only provided as a part of the response URL... SAMLResponse=......Signature=.....

Any pointers? Am I missing something on the configuration side of things in ADFS?

If I remove the check then everything works perfect so this is the missing step for me.

Best regards

**Comment by AndersAbel** [comment]
Old issue without recent activity, closing.

**Comment by m1is** [comment]
Did you ever find solution to this problem?
