### ISSUE TITLE
Signing keys in 2.0.0-preview01 (current) unsettable

### ISSUE THREAD

**Issue by tsirkin** [Sustainsys/Saml2#967]
I am trying to incorporate Saml2 into Ocelot (https://github.com/ThreeMammals/Ocelot)
Naturally, I was trying 2.0.0-preview01. 
But it looks totally unusable as there is no currently way to load metadata.
And no way to set the IdentityProvider signing keys .
Thus, any assertion throw an exception on an attempt on validation.
Overriding IdentityProvider also does not help as SigningKeys property is not virtual.

**Comment by AndersAbel** [comment]
The branch that 2.0.0-preview01 was built from will be deprecated, so closing this.
