### ISSUE TITLE
Question - Sustainsys.Saml2 with Ocelot

### ISSUE THREAD

**Issue by tsirkin** [Sustainsys/Saml2#968]
I am trying to incorporate Saml2 into Ocelot (https://github.com/ThreeMammals/Ocelot)
Now, first of all, Sustainsys.Saml2 stable requires .Net 4.6 while Ocelot is Core only.
Any experience on incorporating those two?

Again, Ocelot is basically a .Net Core middleware so it theoretically should be possible to put Sustainsys.Saml2 middleware in front of it.
Unfortunately, this naive approach does not work as it is not clear to me how to trigger authentication middleware as there is no "protected" resources per se.

I am trying to register my own middleware and call the SignIn/Logout/Acs commands myself.
But there should be a simpler way is there?
Thanks

**Comment by AndersAbel** [comment]
A .NET Core version is being worked on.
