### ISSUE TITLE
How to configure expiration date of a token for auto logout

### ISSUE THREAD

**Issue by SofyanHamdi** [Sustainsys/Saml2#972]
We are trying to configure our MVC app to logout users and redirect them to a page after 10 minutes of inactivity.  We tried the following example in the web.config but it doesn't do what we expect:

`<authentication mode="Forms">
      <forms loginUrl="~/AuthServices/SignIn" timeout="10" />
</authentication>`

This should just work or isn't it?

**Comment by AndersAbel** [comment]
No, it won't work. The <authentication mode="Forms"> is only used to set the redirect-to-authentication-url. The timeout is set in the config for the SessionAuthenticationModule.

**Comment by Darth-Fx** [comment]
Could you elaborate more on where to set this timeout?

We have the line in the web.config:
<modules>
      <add name="SessionAuthenticationModule" ... (but timeout attribute is not allowed)>

And in the code we setup the configuration by setting up a SPOptions and adding a IdentityProvider to it.
Then we use this SpOptions and set:
Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.Options = options;
Sustainsys.Saml2.Mvc.Saml2Controller.Options = options;

All goes well, but we can't seem to set a timeout.
Can this be managed by setting some property from SPOptions maybe?

Thanks in advance!
