### ISSUE TITLE
Sign authentication request with another certificate if signature validation failed

### ISSUE THREAD

**Issue by nfang001** [Sustainsys/Saml2#979]
Hello,

Is it possible to send the same request signed by another certificate if the request failed the IdP signature validation the first time?

Thanks!

**Comment by explunit** [comment]
I've never heard of anything like that and I suspect it wouldn't be found in the SAML standard. However, you can publish multiple public keys in your metadata and the other party is supposed to consider all of them valid (e.g. for a rollover scenario).

**Comment by nfang001** [comment]
Hi @explunit, thanks for the comment!

We are currently updating our signing certificate. The plan I came up with was the same as you mentioned. We will publish both certificate keys and have our clients trust the new certificate while the old one will still be used for signing during the transition period. Once all clients have trusted the new certificate or on the certificate expiry date, we will then switch to use the new certificate.

We expect client IdP to be able to validate requests from us against both certificates, but is it possible that the IdP can only trust one signing signature at one time? If so, can we make it so we are able to send requests signed by different certificates and proceed with response from the valid request? And this is how the posted question was brought up.

Thanks!

**Comment by explunit** [comment]
In my experience, if the other party can only configure a single certificate then you have to closely coordinate the timing. I'm not aware of any way to do a retry process.

**Comment by nfang001** [comment]
@explunit  Will it make a difference in the rollover process if the certificate is issued by a trusted CA?

**Comment by explunit** [comment]
It would depend on the capabilities of the other party's SAML implementation. Most products directly use specific certificates (either obtained from metadata or communicated separately during setup) but I see that some do support chain trust, e.g https://ping.force.com/Support/PingIdentityArticle?id=kA340000000PMW5CAO

**Comment by nfang001** [comment]
@explunit I think I have a better idea now. Thank you very much for your help!
