### ISSUE TITLE
IIS Managed Pipeline Mode (HttpModule)

### ISSUE THREAD

**Issue by MikeAllenC** [Sustainsys/Saml2#982]
Hi there,
I've just managed to get Sustainsys.Saml2.HttpModule up and running in an application after a bit of a fight. The application uses the Classic Managed Pipeline Mode. To get the HttpModule to handle requests to URL's like /Saml2, I had to switch it to Integrated. Without doing so, IIS (Express) simply returned a 404 error. I'm not yet sure whether there's a requirement for the application to run in Classic mode, but if there is, can Sustainsys.Saml2.HttpModule be configured to work?

**Comment by AndersAbel** [comment]
You need to enable [rammfar](https://identityserver.github.io/Documentation/docsv2/configuration/overview.html)
