### ISSUE TITLE
.Net Core 2.x

### ISSUE THREAD

**Issue by BrianLytle** [Sustainsys/Saml2#984]
Has anyone successfully implemented this with .Net Core 2.x?

**Comment by sunilrav** [comment]
I am having an issue with this too. Currently, stuck on this.

` warning NU1701: Package 'Sustainsys.Saml2.AspNetCore2 0.24.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.`

**Comment by ftavares** [comment]
For Core 2.x use the version 2.0 preview

**Comment by BrianLytle** [comment]
Can you be more specific? How do I get that version?

~ Brian

**Comment by ftavares** [comment]
On Visual Studio when you are searching for a nuget package you have a option to Include PreReleases and then you will have this version available.

Or you can do it through .Net CLI or Nuget CLI : https://www.nuget.org/packages/Sustainsys.Saml2/2.0.0-preview01

**Comment by BrianLytle** [comment]
Ahhhh...Thanks!

~ Brian

**Comment by timhenn** [comment]
@BrianLytle , 
Were you able to implement a solution using either 0.24.0 or the 2.0.0 preview?  I'd love to see some of the key configuration code and the postback handler.  I've had no success loading the SAML response I'm getting back.

Tim

**Comment by BrianLytle** [comment]
I gave up on it.

My client purchased a ComponentSpace product. I am now using that.

~ Brian

**Comment by kwaazaar** [comment]
I hear others using ComponentSpace as well. I don't get the code on this library: for AzureAD or ADFS everything works with just a few lines of code. For SAML2 this seems to be impossible...

**Comment by timhenn** [comment]
Thanks for the response, I'm already moving down the ComponentSpace direction as I have very limited time to get things working.  I suspected the code I inherited never worked and thats turning out to be true.

**Comment by Red-F** [comment]
The 2.0.0-preview01 version has a dependency on .Net Framework 4.5 **Microsoft.IdentityModel.Tokens.Saml**.

This effectively prevents using this package within Linux based containers.

**Comment by mdw211** [comment]
according to https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens.Saml/

.NETFramework 4.5
Microsoft.IdentityModel.Tokens (>= 5.2.4)
Microsoft.IdentityModel.Xml (>= 5.2.4)

.NETFramework 4.5.1
Microsoft.IdentityModel.Tokens (>= 5.2.4)
Microsoft.IdentityModel.Xml (>= 5.2.4)

.NETStandard 1.4
Microsoft.IdentityModel.Tokens (>= 5.2.4)
Microsoft.IdentityModel.Xml (>= 5.2.4)
NETStandard.Library (>= 1.6.1)

so it should work fine with .NETStandard 2.0 without pulling in .Net Framework 4.5.  What exactly is the issue you are encountering?

**Comment by Red-F** [comment]
Thanks for the fast reply. I have to re-create my initial setup. Since I am about to leave for two weeks that will have to wait. I get back on this when I'm at work again.
