### ISSUE TITLE
Identityserver4

### ISSUE THREAD

**Issue by gary-b** [Sustainsys/Saml2#991]
We're considering idsrv4 for auth in our saas app. We have multiple customers who will want their users to login with identities stored in their ad servers. One of these uses saml 2.

Is there a production ready solution using SustainSys SAML2 project for SAML2 support with IdentityServer4, running on either .net core or the full .net framework now? If not, would you hazard a guess at a timeline?

Best Regards

**Comment by AndersAbel** [comment]
The Sustainsys.Saml2.AspNetCore2 package is production ready for the full .NET Framework. Work is under way for a production ready .NET Core version.
