### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by SlaveMast3r** [Sustainsys/Saml2#996]
Hello, I have one question. Is this project still supported? Asking because we're considering use IdentityServer4 for auth and we need SAML2 support, but this project looks without development last few months. And not sure if time investment will be not wasted.

**Comment by antgel** [comment]
Happily following this. I see that the recent commits aren't that meaningful. Maybe it works brilliantly, but the large numbers of open Issues and PRs are a bit worrying. I also see in https://github.com/Sustainsys/Saml2/issues/984 people gave up and used ComponentSpace?

Respectfully pinging @explunit and @AndersAbel to understand more about the overall project state, whether professional services are available, etc.

**Comment by AndersAbel** [comment]
Short answer: No, the project is not abandoned and it is still supported.

Even though the issue tracker has not been watched, customers that have signed up for commercial support do get next-day responses to e-mails and fixes to bugs. @antgel commercial services are available, please mail me at anders.abel@sustainsys.com for details about those.

Long answer: The lack of activity that you are seeing, is an effect of work-life-opensource-balance. When I'm working, I'm trying to find a balance between investing in this project (non-paid), doing commercial support/development (paid) and other non-related consulting work (well paid). From March to June, I was busy with another project (not at all related to security/authentication) but that paid my bills. Right now I am into the "life" part of the balance - travelling during the summer with my family. When I'm back, there is substantial full time work planned on the project. The current master branch will (finally) be bumped to a 1.0.0 release (with a small bug fix affecting signed AuthnRequests with ASP.NET Core 2.0). Then #939 will be reviewed and merged and a 2.0.0 release will be done, targeting .NET Standard 2.0. Going forward from that, there are things I would like to rewrite and improve, but that will have to be a later project.

**Comment by antgel** [comment]
Thanks for the feedback, you'll have mail. :)
