### ISSUE TITLE
OutboundSigningAlgorithm issue

### ISSUE THREAD

**Issue by SlaveMast3r** [Sustainsys/Saml2#999]
Hello, 

I have a problem related to signing saml request. Using **.NET Core 2.0** and nugets **Sustainsys.Saml2 (2.0.0-preview01)**, **Sustainsys.Saml2.AspNetCore2 (2.0.0-preview01)**.

Problem is I always receive error inside `Sustainsys.Saml2(netcoreapp2.0)` method `Kentor.AuthServices.WebSso.Saml2RedirectBinding.AddSignature(string queryString, ISaml2Message message)`. This line cause issue because whatever I set as signingAlgorithm it will return null:

    var signatureDescription = (SignatureDescription)CryptoConfig.CreateFromName(signingAlgorithmUrl); //return null

Register SAML authentication block of code:

    services.AddAuthentication()
            .AddSaml2(options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.SPOptions.EntityId = new Saml2NameIdentifier(samlIdentityUrl);
                options.SPOptions.RequestedAuthnContext = authContext;
                options.SPOptions.ServiceCertificates.Add(new ServiceCertificate()
                {
                    Certificate = new X509Certificate2(clientPrivateKey),
                    Use = CertificateUse.Both
                });

                var idp = new IdentityProvider(new EntityId(samlMetadataUrl), options.SPOptions)
                {
                    SingleSignOnServiceUrl = new Uri(samlSignOnUrl),
                    WantAuthnRequestsSigned = true,
                    OutboundSigningAlgorithm = signingAlgorithm,
                    Binding = Saml2BindingType.HttpRedirect
                };

                idp.SigningKeys.AddConfiguredKey(new X509Certificate2(serverPublicKey));
                options.IdentityProviders.Add(idp);
            });

**OutboundSigningAlgorithm** values (string) I tried:

- http://www.w3.org/2000/09/xmldsig#rsa-sha1
- http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 (default)
- http://www.w3.org/2001/04/xmldsig-more#rsa-sha512

**Comment by AndersAbel** [comment]
The branch used to create 2.0.0-preview-01 will be deprecated in favour of #939, so closing this as won't fix.
